// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module image_accelerator_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img_gray_433_dout,
        img_gray_433_empty_n,
        img_gray_433_read,
        img_out_434_din,
        img_out_434_full_n,
        img_out_434_write,
        p_read,
        p_read1,
        p_read2,
        p_read3
);

parameter    ap_ST_fsm_state1 = 77'd1;
parameter    ap_ST_fsm_state2 = 77'd2;
parameter    ap_ST_fsm_state3 = 77'd4;
parameter    ap_ST_fsm_state4 = 77'd8;
parameter    ap_ST_fsm_state5 = 77'd16;
parameter    ap_ST_fsm_state6 = 77'd32;
parameter    ap_ST_fsm_state7 = 77'd64;
parameter    ap_ST_fsm_state8 = 77'd128;
parameter    ap_ST_fsm_state9 = 77'd256;
parameter    ap_ST_fsm_state10 = 77'd512;
parameter    ap_ST_fsm_state11 = 77'd1024;
parameter    ap_ST_fsm_state12 = 77'd2048;
parameter    ap_ST_fsm_state13 = 77'd4096;
parameter    ap_ST_fsm_state14 = 77'd8192;
parameter    ap_ST_fsm_state15 = 77'd16384;
parameter    ap_ST_fsm_state16 = 77'd32768;
parameter    ap_ST_fsm_state17 = 77'd65536;
parameter    ap_ST_fsm_state18 = 77'd131072;
parameter    ap_ST_fsm_state19 = 77'd262144;
parameter    ap_ST_fsm_state20 = 77'd524288;
parameter    ap_ST_fsm_state21 = 77'd1048576;
parameter    ap_ST_fsm_state22 = 77'd2097152;
parameter    ap_ST_fsm_state23 = 77'd4194304;
parameter    ap_ST_fsm_state24 = 77'd8388608;
parameter    ap_ST_fsm_state25 = 77'd16777216;
parameter    ap_ST_fsm_state26 = 77'd33554432;
parameter    ap_ST_fsm_state27 = 77'd67108864;
parameter    ap_ST_fsm_state28 = 77'd134217728;
parameter    ap_ST_fsm_state29 = 77'd268435456;
parameter    ap_ST_fsm_state30 = 77'd536870912;
parameter    ap_ST_fsm_state31 = 77'd1073741824;
parameter    ap_ST_fsm_state32 = 77'd2147483648;
parameter    ap_ST_fsm_state33 = 77'd4294967296;
parameter    ap_ST_fsm_state34 = 77'd8589934592;
parameter    ap_ST_fsm_state35 = 77'd17179869184;
parameter    ap_ST_fsm_state36 = 77'd34359738368;
parameter    ap_ST_fsm_state37 = 77'd68719476736;
parameter    ap_ST_fsm_state38 = 77'd137438953472;
parameter    ap_ST_fsm_state39 = 77'd274877906944;
parameter    ap_ST_fsm_state40 = 77'd549755813888;
parameter    ap_ST_fsm_state41 = 77'd1099511627776;
parameter    ap_ST_fsm_state42 = 77'd2199023255552;
parameter    ap_ST_fsm_state43 = 77'd4398046511104;
parameter    ap_ST_fsm_state44 = 77'd8796093022208;
parameter    ap_ST_fsm_state45 = 77'd17592186044416;
parameter    ap_ST_fsm_state46 = 77'd35184372088832;
parameter    ap_ST_fsm_state47 = 77'd70368744177664;
parameter    ap_ST_fsm_state48 = 77'd140737488355328;
parameter    ap_ST_fsm_state49 = 77'd281474976710656;
parameter    ap_ST_fsm_state50 = 77'd562949953421312;
parameter    ap_ST_fsm_state51 = 77'd1125899906842624;
parameter    ap_ST_fsm_state52 = 77'd2251799813685248;
parameter    ap_ST_fsm_state53 = 77'd4503599627370496;
parameter    ap_ST_fsm_state54 = 77'd9007199254740992;
parameter    ap_ST_fsm_state55 = 77'd18014398509481984;
parameter    ap_ST_fsm_state56 = 77'd36028797018963968;
parameter    ap_ST_fsm_state57 = 77'd72057594037927936;
parameter    ap_ST_fsm_state58 = 77'd144115188075855872;
parameter    ap_ST_fsm_state59 = 77'd288230376151711744;
parameter    ap_ST_fsm_state60 = 77'd576460752303423488;
parameter    ap_ST_fsm_state61 = 77'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 77'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 77'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 77'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 77'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 77'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 77'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 77'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 77'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 77'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 77'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 77'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 77'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 77'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 77'd18889465931478580854784;
parameter    ap_ST_fsm_pp1_stage0 = 77'd37778931862957161709568;
parameter    ap_ST_fsm_state87 = 77'd75557863725914323419136;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] img_gray_433_dout;
input   img_gray_433_empty_n;
output   img_gray_433_read;
output  [7:0] img_out_434_din;
input   img_out_434_full_n;
output   img_out_434_write;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg img_gray_433_read;
reg img_out_434_write;

(* fsm_encoding = "none" *) reg   [76:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    img_gray_433_blk_n;
reg    ap_enable_reg_pp1_iter2;
wire    ap_block_pp1_stage0;
reg    img_out_434_blk_n;
reg    ap_enable_reg_pp1_iter10;
reg   [0:0] DDR_wr_en_1_reg_2153;
reg   [0:0] DDR_wr_en_1_reg_2153_pp1_iter9_reg;
reg   [0:0] icmp_ln809_reg_2182;
reg   [0:0] icmp_ln809_reg_2182_pp1_iter9_reg;
reg   [15:0] output_buffer_index_start_V_5_reg_263;
wire    ap_CS_fsm_state36;
wire   [16:0] zext_ln29_2_fu_293_p1;
reg   [16:0] zext_ln29_2_reg_1726;
wire   [31:0] zext_ln29_1_fu_296_p1;
reg   [31:0] zext_ln29_1_reg_1731;
wire   [31:0] grp_fu_287_p2;
reg   [31:0] out_div_3_reg_1737;
wire   [8:0] dim3_V_1_fu_299_p2;
wire    ap_CS_fsm_state37;
wire    ap_CS_fsm_state38;
wire    ap_CS_fsm_state39;
wire   [0:0] cmp_i_i937_i_fu_389_p2;
reg   [0:0] cmp_i_i937_i_reg_1860;
wire    ap_CS_fsm_state73;
wire   [31:0] grp_fu_383_p2;
reg   [31:0] out_div_4_reg_1869;
wire    ap_CS_fsm_state74;
wire   [16:0] trunc_ln213_fu_398_p1;
reg   [16:0] trunc_ln213_reg_1877;
wire   [31:0] shl_ln213_fu_402_p2;
reg   [31:0] shl_ln213_reg_1882;
wire   [32:0] rhs_4_fu_407_p1;
reg   [32:0] rhs_4_reg_1887;
wire   [0:0] bit_select_i_i90_i_fu_425_p2;
reg   [0:0] bit_select_i_i90_i_reg_1892;
wire   [16:0] sub162_i_fu_431_p2;
reg   [16:0] sub162_i_reg_1897;
wire   [16:0] sub158_i_fu_436_p2;
reg   [16:0] sub158_i_reg_1903;
wire   [32:0] lhs_V_6_fu_442_p1;
reg   [32:0] lhs_V_6_reg_1908;
wire   [0:0] rev_fu_454_p2;
reg   [0:0] rev_reg_1913;
wire   [0:0] cmp10531_fu_460_p2;
reg   [0:0] cmp10531_reg_1918;
wire   [0:0] empty_49_fu_471_p2;
reg   [0:0] empty_49_reg_1922;
wire   [0:0] sel_tmp_fu_477_p2;
reg   [0:0] sel_tmp_reg_1927;
wire   [15:0] row_index_V_1_fu_487_p2;
reg   [15:0] row_index_V_1_reg_1933;
wire    ap_CS_fsm_state75;
wire   [0:0] icmp_ln686_fu_493_p2;
wire   [0:0] cmp_i_i109_i_fu_502_p2;
reg   [0:0] cmp_i_i109_i_reg_1942;
wire   [15:0] weight_value_V_fu_507_p1;
reg   [15:0] weight_value_V_reg_1947;
wire   [15:0] output_buffer_index_next_V_fu_510_p2;
reg   [15:0] output_buffer_index_next_V_reg_1956;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter0;
wire    ap_block_state76_pp1_stage0_iter0;
wire    ap_block_state77_pp1_stage0_iter1;
reg    ap_block_state78_pp1_stage0_iter2;
wire    ap_block_state79_pp1_stage0_iter3;
wire    ap_block_state80_pp1_stage0_iter4;
wire    ap_block_state81_pp1_stage0_iter5;
wire    ap_block_state82_pp1_stage0_iter6;
wire    ap_block_state83_pp1_stage0_iter7;
wire    ap_block_state84_pp1_stage0_iter8;
wire    ap_block_state85_pp1_stage0_iter9;
reg    ap_predicate_op522_write_state86;
reg    ap_block_state86_pp1_stage0_iter10;
reg    ap_block_pp1_stage0_11001;
wire   [0:0] icmp_ln692_fu_516_p2;
reg   [0:0] icmp_ln692_reg_1962;
reg   [0:0] icmp_ln692_reg_1962_pp1_iter1_reg;
reg   [0:0] icmp_ln692_reg_1962_pp1_iter2_reg;
reg   [0:0] icmp_ln692_reg_1962_pp1_iter3_reg;
reg   [0:0] icmp_ln692_reg_1962_pp1_iter4_reg;
reg   [0:0] icmp_ln692_reg_1962_pp1_iter5_reg;
reg   [0:0] icmp_ln692_reg_1962_pp1_iter6_reg;
reg   [0:0] icmp_ln692_reg_1962_pp1_iter7_reg;
reg   [0:0] icmp_ln692_reg_1962_pp1_iter8_reg;
wire   [0:0] cmp108_fu_527_p2;
reg   [0:0] cmp108_reg_1966;
reg   [0:0] cmp108_reg_1966_pp1_iter1_reg;
reg   [0:0] cmp108_reg_1966_pp1_iter2_reg;
reg   [0:0] cmp108_reg_1966_pp1_iter3_reg;
reg   [0:0] cmp108_reg_1966_pp1_iter4_reg;
reg   [0:0] cmp108_reg_1966_pp1_iter5_reg;
reg   [0:0] cmp108_reg_1966_pp1_iter6_reg;
reg   [0:0] cmp108_reg_1966_pp1_iter7_reg;
reg   [0:0] cmp108_reg_1966_pp1_iter8_reg;
wire   [31:0] p_Val2_5_fu_538_p3;
reg   [31:0] p_Val2_5_reg_1975;
wire   [15:0] index_fract_value_V_fu_557_p1;
reg   [15:0] index_fract_value_V_reg_1982;
reg   [15:0] index_fract_value_V_reg_1982_pp1_iter1_reg;
wire   [15:0] sub_value_V_fu_561_p2;
reg   [15:0] sub_value_V_reg_1992;
reg   [15:0] sub_value_V_reg_1992_pp1_iter1_reg;
reg   [15:0] output_buffer_index_start_V_reg_1998;
wire   [15:0] sub_value_V_1_fu_580_p2;
reg   [15:0] sub_value_V_1_reg_2005;
wire   [0:0] icmp_ln878_2_fu_585_p2;
reg   [0:0] icmp_ln878_2_reg_2010;
reg   [15:0] output_buffer_index_next_V_1_reg_2015;
wire   [0:0] out_index_val_V_fu_653_p1;
reg   [0:0] out_index_val_V_reg_2021;
reg   [0:0] out_index_val_V_reg_2021_pp1_iter2_reg;
reg   [0:0] out_index_val_V_reg_2021_pp1_iter3_reg;
reg   [0:0] out_index_val_V_reg_2021_pp1_iter4_reg;
reg   [0:0] out_index_val_V_reg_2021_pp1_iter5_reg;
reg   [0:0] out_index_val_V_reg_2021_pp1_iter6_reg;
reg   [0:0] out_index_val_V_reg_2021_pp1_iter7_reg;
reg   [0:0] out_index_val_V_reg_2021_pp1_iter8_reg;
wire   [15:0] output_buffer_index_next_V_5_fu_686_p3;
reg   [15:0] output_buffer_index_next_V_5_reg_2034;
wire   [0:0] t1_fu_740_p2;
reg   [0:0] t1_reg_2041;
wire   [16:0] ret_3_fu_750_p2;
reg   [16:0] ret_3_reg_2046;
wire   [0:0] icmp_ln870_9_fu_762_p2;
reg   [0:0] icmp_ln870_9_reg_2051;
wire   [0:0] icmp_ln886_2_fu_776_p2;
reg   [0:0] icmp_ln886_2_reg_2056;
wire   [31:0] overlap_next_pixel_V_fu_790_p2;
reg   [31:0] overlap_next_pixel_V_reg_2061;
wire   [16:0] ret_6_fu_795_p2;
reg   [16:0] ret_6_reg_2066;
wire   [0:0] icmp_ln204_fu_801_p2;
reg   [0:0] icmp_ln204_reg_2071;
reg   [0:0] icmp_ln204_reg_2071_pp1_iter2_reg;
reg   [0:0] icmp_ln204_reg_2071_pp1_iter3_reg;
reg   [0:0] icmp_ln204_reg_2071_pp1_iter4_reg;
reg   [0:0] icmp_ln204_reg_2071_pp1_iter5_reg;
reg   [0:0] icmp_ln204_reg_2071_pp1_iter6_reg;
reg   [0:0] icmp_ln204_reg_2071_pp1_iter7_reg;
wire   [0:0] icmp_ln218_1_fu_806_p2;
reg   [0:0] icmp_ln218_1_reg_2081;
wire   [0:0] icmp_ln870_11_fu_811_p2;
reg   [0:0] icmp_ln870_11_reg_2086;
wire   [0:0] xor_ln890_fu_889_p2;
reg   [0:0] xor_ln890_reg_2091;
reg   [0:0] xor_ln890_reg_2091_pp1_iter3_reg;
reg   [0:0] xor_ln890_reg_2091_pp1_iter4_reg;
wire   [0:0] and_ln218_1_fu_905_p2;
reg   [0:0] and_ln218_1_reg_2096;
reg   [0:0] and_ln218_1_reg_2096_pp1_iter3_reg;
reg   [0:0] and_ln218_1_reg_2096_pp1_iter4_reg;
reg   [0:0] and_ln218_1_reg_2096_pp1_iter5_reg;
reg   [0:0] and_ln218_1_reg_2096_pp1_iter6_reg;
reg   [0:0] and_ln218_1_reg_2096_pp1_iter7_reg;
reg   [0:0] and_ln218_1_reg_2096_pp1_iter8_reg;
reg   [0:0] and_ln218_1_reg_2096_pp1_iter9_reg;
wire   [15:0] p_Result_s_fu_995_p1;
reg   [15:0] p_Result_s_reg_2122;
wire   [0:0] icmp_ln576_fu_1033_p2;
reg   [0:0] icmp_ln576_reg_2128;
wire   [0:0] icmp_ln886_4_fu_1039_p2;
reg   [0:0] icmp_ln886_4_reg_2133;
wire   [0:0] icmp_ln878_4_fu_1083_p2;
reg   [0:0] icmp_ln878_4_reg_2138;
wire   [32:0] ret_11_fu_1092_p2;
reg   [32:0] ret_11_reg_2143;
reg   [0:0] Yaxis_overlap_en_load_reg_2148;
reg   [0:0] Yaxis_overlap_en_load_reg_2148_pp1_iter6_reg;
reg   [0:0] Yaxis_overlap_en_load_reg_2148_pp1_iter7_reg;
reg   [0:0] Yaxis_overlap_en_load_reg_2148_pp1_iter8_reg;
wire   [0:0] DDR_wr_en_1_fu_1156_p2;
reg   [0:0] DDR_wr_en_1_reg_2153_pp1_iter6_reg;
reg   [0:0] DDR_wr_en_1_reg_2153_pp1_iter7_reg;
reg   [0:0] DDR_wr_en_1_reg_2153_pp1_iter8_reg;
wire   [31:0] zext_ln1345_fu_1197_p1;
wire   [31:0] zext_ln1345_1_fu_1201_p1;
wire   [31:0] zext_ln1345_2_fu_1214_p1;
wire   [31:0] zext_ln1345_3_fu_1218_p1;
wire   [0:0] icmp_ln809_fu_1245_p2;
reg   [0:0] icmp_ln809_reg_2182_pp1_iter7_reg;
reg   [0:0] icmp_ln809_reg_2182_pp1_iter8_reg;
wire   [0:0] p_Result_4_fu_1274_p1;
reg   [0:0] p_Result_4_reg_2186;
reg   [15:0] procBlock_out_V_reg_2194;
reg   [15:0] data_mux_out_V_1_reg_2200;
reg   [15:0] procBlock_out_V_2_reg_2206;
reg   [15:0] data_mux_out_overlap_V_1_reg_2212;
wire   [0:0] or_ln489_fu_1319_p2;
reg   [0:0] or_ln489_reg_2218;
reg   [8:0] ouput_buffer_V_0_0_addr_1_reg_2224;
reg   [8:0] ouput_buffer_V_0_0_addr_1_reg_2224_pp1_iter9_reg;
wire   [15:0] temp_sum_V_fu_1587_p2;
reg   [15:0] temp_sum_V_reg_2230;
wire   [15:0] buffer_data_temp_fu_1600_p3;
reg   [15:0] buffer_data_temp_reg_2236;
reg    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state76;
reg    ap_enable_reg_pp1_iter1;
reg    ap_enable_reg_pp1_iter3;
reg    ap_enable_reg_pp1_iter4;
reg    ap_enable_reg_pp1_iter5;
reg    ap_enable_reg_pp1_iter6;
reg    ap_enable_reg_pp1_iter7;
reg    ap_enable_reg_pp1_iter8;
reg    ap_enable_reg_pp1_iter9;
reg   [8:0] ouput_buffer_V_0_0_address0;
reg    ouput_buffer_V_0_0_ce0;
reg    ouput_buffer_V_0_0_we0;
reg   [15:0] ouput_buffer_V_0_0_d0;
wire   [8:0] ouput_buffer_V_0_0_address1;
reg    ouput_buffer_V_0_0_ce1;
wire   [15:0] ouput_buffer_V_0_0_q1;
reg   [8:0] dim3_V_reg_241;
wire   [0:0] icmp_ln878_fu_305_p2;
reg   [15:0] row_index_V_reg_252;
wire    ap_CS_fsm_state87;
reg   [15:0] ap_phi_mux_output_buffer_index_start_V_5_phi_fu_267_p4;
wire   [63:0] conv_i396_fu_311_p1;
wire   [63:0] conv_i82_i_fu_1324_p1;
reg   [31:0] Xindex_output_next_V_fu_132;
wire   [31:0] p_Val2_s_fu_550_p3;
reg   [31:0] Yindex_output_V_1_fu_136;
wire   [31:0] Yindex_output_V_4_fu_1061_p3;
reg   [31:0] Yindex_output_prev_V_fu_140;
wire   [31:0] Yindex_output_prev_V_2_fu_1068_p3;
reg   [15:0] write_col_index_V_fu_144;
wire   [15:0] write_col_index_V_2_fu_1345_p3;
reg   [15:0] ouput_index_write_counter_V_fu_148;
wire   [15:0] ouput_index_write_counter_V_2_fu_953_p3;
reg   [31:0] out_col_index_fu_152;
wire   [31:0] select_ln811_fu_1259_p3;
reg   [0:0] Yaxis_overlap_en_fu_156;
wire   [0:0] Yaxis_overlap_en_1_fu_1231_p2;
reg   [31:0] p_Val2_1_fu_160;
reg   [15:0] data_previous_V_fu_164;
wire   [15:0] DDR_write0_temp_V_fu_1465_p3;
reg   [15:0] data_previous_V_2_fu_168;
wire   [15:0] DDR_write1_temp_V_fu_1564_p3;
reg   [15:0] data_previous_overlap_V_fu_172;
wire   [15:0] update_overlap_4_fu_1473_p3;
reg   [15:0] data_previous_overlap_V_2_fu_176;
wire   [15:0] update_overlap_5_fu_1572_p3;
reg    ap_block_pp1_stage0_01001;
wire   [31:0] grp_fu_287_p0;
wire   [15:0] grp_fu_287_p1;
wire   [31:0] grp_fu_323_p0;
wire   [15:0] grp_fu_323_p1;
wire   [31:0] grp_fu_383_p0;
wire   [15:0] grp_fu_383_p1;
wire   [31:0] grp_fu_323_p2;
wire   [0:0] tmp_fu_410_p3;
wire   [16:0] tmp_5_fu_417_p3;
wire   [16:0] zext_ln29_4_fu_395_p1;
wire   [0:0] tmp_6_fu_446_p3;
wire   [16:0] empty_fu_465_p2;
wire   [16:0] zext_ln686_fu_498_p1;
wire   [31:0] add_ln691_fu_533_p2;
wire   [31:0] Xindex_output_next_V_1_fu_545_p2;
wire   [15:0] index_fract_value_V_1_fu_576_p1;
wire   [0:0] icmp_ln886_fu_618_p2;
wire   [0:0] and_ln72_fu_628_p2;
wire   [0:0] icmp_ln878_1_fu_614_p2;
wire   [0:0] and_ln72_1_fu_633_p2;
wire   [15:0] output_buffer_index_start_V_2_fu_623_p2;
wire   [15:0] output_buffer_index_start_V_3_fu_639_p3;
wire   [15:0] output_buffer_index_start_V_6_fu_646_p3;
wire   [0:0] icmp_ln886_1_fu_661_p2;
wire   [0:0] and_ln89_fu_676_p2;
wire   [0:0] and_ln89_1_fu_681_p2;
wire   [15:0] output_buffer_index_next_V_2_fu_666_p2;
wire   [15:0] output_buffer_index_next_V_3_fu_671_p3;
wire   [31:0] ret_fu_694_p2;
wire   [31:0] ret_1_fu_698_p2;
wire   [15:0] int_bits_Xindex_out_previous_V_fu_704_p4;
wire   [15:0] int_bits_Xindex_out_previous_V_2_fu_714_p3;
wire   [31:0] ret_2_fu_725_p2;
wire   [15:0] int_bits_Xindex_out_V_fu_730_p4;
wire   [16:0] zext_ln215_fu_746_p1;
wire   [16:0] rhs_1_fu_721_p1;
wire   [16:0] zext_ln1346_fu_657_p1;
wire   [16:0] ret_4_fu_756_p2;
wire   [32:0] zext_ln215_1_fu_768_p1;
wire   [32:0] ret_5_fu_771_p2;
wire   [31:0] r_fu_782_p3;
wire   [16:0] zext_ln692_fu_610_p1;
wire   [31:0] zext_ln878_fu_824_p1;
wire   [0:0] icmp_ln878_3_fu_827_p2;
wire   [0:0] icmp_ln870_fu_819_p2;
wire   [0:0] and_ln870_1_fu_837_p2;
wire   [0:0] and_ln870_fu_832_p2;
wire   [0:0] t2_fu_842_p2;
wire   [0:0] or_ln138_fu_848_p2;
wire   [16:0] zext_ln870_fu_858_p1;
wire   [0:0] icmp_ln870_10_fu_861_p2;
wire   [0:0] icmp_ln886_3_fu_866_p2;
wire   [0:0] and_ln166_fu_871_p2;
wire   [0:0] icmp_ln890_1_fu_884_p2;
wire   [0:0] icmp_ln218_fu_895_p2;
wire   [0:0] and_ln218_fu_900_p2;
wire   [0:0] icmp_ln237_fu_910_p2;
wire   [15:0] select_ln239_fu_922_p3;
wire   [0:0] or_ln237_fu_914_p2;
wire   [16:0] Wx_V_0_0_1_fu_919_p1;
wire   [16:0] zext_ln239_fu_927_p1;
wire   [15:0] ouput_index_write_counter_V_1_fu_939_p2;
wire   [15:0] select_ln752_fu_945_p3;
wire   [15:0] Wx_for_Nplus1_Procblock_fu_877_p3;
wire   [0:0] or_ln138_1_fu_853_p2;
wire   [16:0] select_ln237_fu_931_p3;
wire   [7:0] in_data_V_fu_964_p3;
wire   [15:0] p_Result_3_fu_999_p1;
wire   [16:0] zext_ln674_1_fu_1003_p1;
wire   [15:0] p_Result_1_fu_1013_p4;
wire   [15:0] p_Result_2_fu_1023_p4;
wire   [16:0] Yindex_output_prev_precision_error_V_fu_1007_p2;
wire   [31:0] Yindex_output_V_fu_1051_p2;
wire   [31:0] Yindex_output_prev_V_1_fu_1056_p2;
wire   [15:0] p_Result_9_fu_1075_p1;
wire   [31:0] zext_ln674_2_fu_1079_p1;
wire   [32:0] zext_ln215_2_fu_1088_p1;
wire   [16:0] zext_ln674_fu_1110_p1;
wire   [16:0] Yindex_output_precision_error_V_fu_1113_p2;
wire   [0:0] icmp_ln890_fu_1119_p2;
wire   [0:0] or_ln201_1_fu_1134_p2;
wire   [0:0] or_ln201_fu_1129_p2;
wire   [0:0] or_ln201_2_fu_1139_p2;
wire   [0:0] and_ln201_fu_1145_p2;
wire   [0:0] or_ln204_fu_1125_p2;
wire   [0:0] DDR_wr_en_tmp_fu_1150_p2;
wire   [15:0] trunc_ln357_fu_1161_p1;
wire   [16:0] zext_ln213_fu_1164_p1;
wire   [16:0] sub_ln213_fu_1168_p2;
wire   [23:0] grp_fu_1643_p3;
wire   [16:0] Wy0_fu_1174_p3;
wire   [15:0] r_1_fu_1188_p4;
wire   [23:0] grp_fu_1652_p2;
wire   [15:0] r_3_fu_1205_p4;
wire   [15:0] Wy1_fu_1181_p3;
wire   [0:0] and_ln878_fu_1227_p2;
wire   [0:0] icmp_ln886_5_fu_1222_p2;
wire   [31:0] out_col_index_1_fu_1253_p2;
wire   [31:0] grp_fu_1659_p3;
wire   [31:0] grp_fu_1668_p2;
wire   [31:0] grp_fu_1675_p3;
wire   [31:0] grp_fu_1684_p2;
wire   [0:0] out_buffer_wr_en_fu_1278_p2;
wire   [15:0] write_col_index_V_1_fu_1332_p2;
wire   [15:0] select_ln819_fu_1338_p3;
wire   [0:0] xor_ln870_fu_1374_p2;
wire   [1:0] p_Result_5_fu_1379_p3;
wire   [1:0] p_Result_6_fu_1387_p3;
wire   [1:0] data_mux_out_status_V_2_fu_1395_p3;
wire   [15:0] data_previous_V_4_fu_1412_p3;
wire   [15:0] data_mux_out_V_2_fu_1402_p3;
wire   [15:0] data_previous_overlap_V_4_fu_1419_p3;
wire   [15:0] data_mux_out_overlap_V_2_fu_1407_p3;
wire   [0:0] icmp_ln874_fu_1426_p2;
wire   [15:0] add_ln208_1_fu_1438_p2;
wire   [15:0] add_ln208_fu_1432_p2;
wire   [0:0] cmp72_i_fu_1369_p2;
wire   [0:0] and_ln488_fu_1460_p2;
wire   [15:0] update_fu_1452_p3;
wire   [15:0] update_overlap_fu_1444_p3;
wire   [1:0] p_Result_7_fu_1481_p3;
wire   [1:0] p_Result_8_fu_1488_p3;
wire   [1:0] data_mux_out_status_V_5_fu_1495_p3;
wire   [15:0] data_previous_V_5_fu_1512_p3;
wire   [15:0] data_mux_out_V_3_fu_1502_p3;
wire   [15:0] data_previous_overlap_V_5_fu_1519_p3;
wire   [15:0] data_mux_out_overlap_V_3_fu_1507_p3;
wire   [0:0] icmp_ln874_1_fu_1526_p2;
wire   [15:0] add_ln208_3_fu_1538_p2;
wire   [15:0] add_ln208_2_fu_1532_p2;
wire   [0:0] and_ln488_1_fu_1560_p2;
wire   [15:0] update_1_fu_1552_p3;
wire   [15:0] update_overlap_2_fu_1544_p3;
wire   [15:0] DDR_write0_temp_V_1_fu_1580_p3;
wire   [15:0] select_ln530_fu_1593_p3;
wire   [15:0] sum_rounding_V_fu_1627_p2;
wire   [16:0] grp_fu_1643_p0;
wire   [7:0] grp_fu_1643_p1;
wire   [8:0] grp_fu_1643_p2;
wire   [15:0] grp_fu_1652_p0;
wire   [7:0] grp_fu_1652_p1;
wire   [15:0] grp_fu_1659_p0;
wire   [16:0] grp_fu_1659_p1;
wire   [16:0] grp_fu_1659_p2;
wire   [15:0] grp_fu_1668_p0;
wire   [16:0] grp_fu_1668_p1;
wire   [15:0] grp_fu_1675_p0;
wire   [15:0] grp_fu_1675_p1;
wire   [16:0] grp_fu_1675_p2;
wire   [15:0] grp_fu_1684_p0;
wire   [15:0] grp_fu_1684_p1;
reg    grp_fu_287_ap_start;
wire    grp_fu_287_ap_done;
reg    grp_fu_323_ap_start;
wire    grp_fu_323_ap_done;
reg    grp_fu_383_ap_start;
wire    grp_fu_383_ap_done;
reg    grp_fu_1643_ce;
reg    grp_fu_1652_ce;
reg    grp_fu_1659_ce;
reg    grp_fu_1668_ce;
reg    grp_fu_1675_ce;
reg    grp_fu_1684_ce;
reg   [76:0] ap_NS_fsm;
reg    ap_block_pp1;
wire    ap_enable_operation_462;
reg    ap_enable_state84_pp1_iter8_stage0;
wire    ap_enable_operation_507;
reg    ap_enable_state85_pp1_iter9_stage0;
reg    ap_predicate_op517_store_state86;
reg    ap_enable_operation_517;
reg    ap_enable_state86_pp1_iter10_stage0;
reg    ap_enable_operation_521;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
wire   [23:0] grp_fu_1643_p00;
wire   [23:0] grp_fu_1643_p10;
wire   [23:0] grp_fu_1652_p00;
wire   [23:0] grp_fu_1652_p10;
wire   [31:0] grp_fu_287_p10;
wire   [31:0] grp_fu_383_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 77'd1;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter10 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter3 = 1'b0;
#0 ap_enable_reg_pp1_iter4 = 1'b0;
#0 ap_enable_reg_pp1_iter5 = 1'b0;
#0 ap_enable_reg_pp1_iter6 = 1'b0;
#0 ap_enable_reg_pp1_iter7 = 1'b0;
#0 ap_enable_reg_pp1_iter8 = 1'b0;
#0 ap_enable_reg_pp1_iter9 = 1'b0;
end

image_accelerator_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_ouput_buffer_V_0_0 #(
    .DataWidth( 16 ),
    .AddressRange( 480 ),
    .AddressWidth( 9 ))
ouput_buffer_V_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ouput_buffer_V_0_0_address0),
    .ce0(ouput_buffer_V_0_0_ce0),
    .we0(ouput_buffer_V_0_0_we0),
    .d0(ouput_buffer_V_0_0_d0),
    .address1(ouput_buffer_V_0_0_address1),
    .ce1(ouput_buffer_V_0_0_ce1),
    .q1(ouput_buffer_V_0_0_q1)
);

image_accelerator_udiv_32ns_16ns_32_36_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
udiv_32ns_16ns_32_36_seq_1_U40(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_287_ap_start),
    .done(grp_fu_287_ap_done),
    .din0(grp_fu_287_p0),
    .din1(grp_fu_287_p1),
    .ce(1'b1),
    .dout(grp_fu_287_p2)
);

image_accelerator_udiv_32ns_16ns_32_36_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
udiv_32ns_16ns_32_36_seq_1_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_323_ap_start),
    .done(grp_fu_323_ap_done),
    .din0(grp_fu_323_p0),
    .din1(grp_fu_323_p1),
    .ce(1'b1),
    .dout(grp_fu_323_p2)
);

image_accelerator_udiv_32ns_16ns_32_36_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
udiv_32ns_16ns_32_36_seq_1_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_383_ap_start),
    .done(grp_fu_383_ap_done),
    .din0(grp_fu_383_p0),
    .din1(grp_fu_383_p1),
    .ce(1'b1),
    .dout(grp_fu_383_p2)
);

image_accelerator_mac_muladd_17ns_8ns_9ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 24 ))
mac_muladd_17ns_8ns_9ns_24_4_1_U43(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1643_p0),
    .din1(grp_fu_1643_p1),
    .din2(grp_fu_1643_p2),
    .ce(grp_fu_1643_ce),
    .dout(grp_fu_1643_p3)
);

image_accelerator_mul_mul_16ns_8ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_mul_16ns_8ns_24_4_1_U44(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1652_p0),
    .din1(grp_fu_1652_p1),
    .ce(grp_fu_1652_ce),
    .dout(grp_fu_1652_p2)
);

image_accelerator_mac_muladd_16ns_17ns_17ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 17 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 32 ))
mac_muladd_16ns_17ns_17ns_32_4_1_U45(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1659_p0),
    .din1(grp_fu_1659_p1),
    .din2(grp_fu_1659_p2),
    .ce(grp_fu_1659_ce),
    .dout(grp_fu_1659_p3)
);

image_accelerator_mul_mul_16ns_17ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 32 ))
mul_mul_16ns_17ns_32_4_1_U46(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1668_p0),
    .din1(grp_fu_1668_p1),
    .ce(grp_fu_1668_ce),
    .dout(grp_fu_1668_p2)
);

image_accelerator_mac_muladd_16ns_16ns_17ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 32 ))
mac_muladd_16ns_16ns_17ns_32_4_1_U47(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1675_p0),
    .din1(grp_fu_1675_p1),
    .din2(grp_fu_1675_p2),
    .ce(grp_fu_1675_ce),
    .dout(grp_fu_1675_p3)
);

image_accelerator_mul_mul_16ns_16ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_mul_16ns_16ns_32_4_1_U48(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1684_p0),
    .din1(grp_fu_1684_p1),
    .ce(grp_fu_1684_ce),
    .dout(grp_fu_1684_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp1_exit_iter0_state76) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((icmp_ln686_fu_493_p2 == 1'd0) & (cmp10531_reg_1918 == 1'd0) & (1'b1 == ap_CS_fsm_state75))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp1_exit_iter0_state76)) begin
                ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state76);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter10 <= ap_enable_reg_pp1_iter9;
        end else if (((icmp_ln686_fu_493_p2 == 1'd0) & (cmp10531_reg_1918 == 1'd0) & (1'b1 == ap_CS_fsm_state75))) begin
            ap_enable_reg_pp1_iter10 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter5 <= ap_enable_reg_pp1_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter6 <= ap_enable_reg_pp1_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter7 <= ap_enable_reg_pp1_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter8 <= ap_enable_reg_pp1_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter9 <= ap_enable_reg_pp1_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        Yaxis_overlap_en_fu_156 <= 1'd0;
    end else if (((ap_enable_reg_pp1_iter5 == 1'b1) & (icmp_ln692_reg_1962_pp1_iter4_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        Yaxis_overlap_en_fu_156 <= Yaxis_overlap_en_1_fu_1231_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state74)) begin
        Yindex_output_V_1_fu_136 <= grp_fu_383_p2;
    end else if (((ap_enable_reg_pp1_iter4 == 1'b1) & (icmp_ln692_reg_1962_pp1_iter3_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        Yindex_output_V_1_fu_136 <= Yindex_output_V_4_fu_1061_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        Yindex_output_prev_V_fu_140 <= 32'd0;
    end else if (((ap_enable_reg_pp1_iter4 == 1'b1) & (icmp_ln692_reg_1962_pp1_iter3_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        Yindex_output_prev_V_fu_140 <= Yindex_output_prev_V_2_fu_1068_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        data_previous_V_2_fu_168 <= 16'd0;
    end else if (((ap_enable_reg_pp1_iter9 == 1'b1) & (icmp_ln692_reg_1962_pp1_iter8_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        data_previous_V_2_fu_168 <= DDR_write1_temp_V_fu_1564_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        data_previous_V_fu_164 <= 16'd0;
    end else if (((ap_enable_reg_pp1_iter9 == 1'b1) & (icmp_ln692_reg_1962_pp1_iter8_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        data_previous_V_fu_164 <= DDR_write0_temp_V_fu_1465_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        data_previous_overlap_V_2_fu_176 <= 16'd0;
    end else if (((ap_enable_reg_pp1_iter9 == 1'b1) & (icmp_ln692_reg_1962_pp1_iter8_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        data_previous_overlap_V_2_fu_176 <= update_overlap_5_fu_1572_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        data_previous_overlap_V_fu_172 <= 16'd0;
    end else if (((ap_enable_reg_pp1_iter9 == 1'b1) & (icmp_ln692_reg_1962_pp1_iter8_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        data_previous_overlap_V_fu_172 <= update_overlap_4_fu_1473_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln878_fu_305_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state37))) begin
        dim3_V_reg_241 <= dim3_V_1_fu_299_p2;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        dim3_V_reg_241 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        ouput_index_write_counter_V_fu_148 <= 16'd1;
    end else if (((icmp_ln692_reg_1962_pp1_iter1_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        ouput_index_write_counter_V_fu_148 <= ouput_index_write_counter_V_2_fu_953_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        out_col_index_fu_152 <= 32'd0;
    end else if (((ap_enable_reg_pp1_iter6 == 1'b1) & (1'd1 == DDR_wr_en_1_reg_2153) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        out_col_index_fu_152 <= select_ln811_fu_1259_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln692_reg_1962 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        output_buffer_index_start_V_5_reg_263 <= output_buffer_index_next_V_reg_1956;
    end else if (((icmp_ln686_fu_493_p2 == 1'd0) & (cmp10531_reg_1918 == 1'd0) & (1'b1 == ap_CS_fsm_state75))) begin
        output_buffer_index_start_V_5_reg_263 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state87)) begin
        row_index_V_reg_252 <= row_index_V_1_reg_1933;
    end else if ((1'b1 == ap_CS_fsm_state74)) begin
        row_index_V_reg_252 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        write_col_index_V_fu_144 <= 16'd0;
    end else if (((ap_enable_reg_pp1_iter8 == 1'b1) & (icmp_ln692_reg_1962_pp1_iter7_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        write_col_index_V_fu_144 <= write_col_index_V_2_fu_1345_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp1_stage0_11001)) begin
        DDR_wr_en_1_reg_2153 <= DDR_wr_en_1_fu_1156_p2;
        DDR_wr_en_1_reg_2153_pp1_iter6_reg <= DDR_wr_en_1_reg_2153;
        DDR_wr_en_1_reg_2153_pp1_iter7_reg <= DDR_wr_en_1_reg_2153_pp1_iter6_reg;
        DDR_wr_en_1_reg_2153_pp1_iter8_reg <= DDR_wr_en_1_reg_2153_pp1_iter7_reg;
        DDR_wr_en_1_reg_2153_pp1_iter9_reg <= DDR_wr_en_1_reg_2153_pp1_iter8_reg;
        Yaxis_overlap_en_load_reg_2148 <= Yaxis_overlap_en_fu_156;
        Yaxis_overlap_en_load_reg_2148_pp1_iter6_reg <= Yaxis_overlap_en_load_reg_2148;
        Yaxis_overlap_en_load_reg_2148_pp1_iter7_reg <= Yaxis_overlap_en_load_reg_2148_pp1_iter6_reg;
        Yaxis_overlap_en_load_reg_2148_pp1_iter8_reg <= Yaxis_overlap_en_load_reg_2148_pp1_iter7_reg;
        and_ln218_1_reg_2096 <= and_ln218_1_fu_905_p2;
        and_ln218_1_reg_2096_pp1_iter3_reg <= and_ln218_1_reg_2096;
        and_ln218_1_reg_2096_pp1_iter4_reg <= and_ln218_1_reg_2096_pp1_iter3_reg;
        and_ln218_1_reg_2096_pp1_iter5_reg <= and_ln218_1_reg_2096_pp1_iter4_reg;
        and_ln218_1_reg_2096_pp1_iter6_reg <= and_ln218_1_reg_2096_pp1_iter5_reg;
        and_ln218_1_reg_2096_pp1_iter7_reg <= and_ln218_1_reg_2096_pp1_iter6_reg;
        and_ln218_1_reg_2096_pp1_iter8_reg <= and_ln218_1_reg_2096_pp1_iter7_reg;
        and_ln218_1_reg_2096_pp1_iter9_reg <= and_ln218_1_reg_2096_pp1_iter8_reg;
        cmp108_reg_1966_pp1_iter2_reg <= cmp108_reg_1966_pp1_iter1_reg;
        cmp108_reg_1966_pp1_iter3_reg <= cmp108_reg_1966_pp1_iter2_reg;
        cmp108_reg_1966_pp1_iter4_reg <= cmp108_reg_1966_pp1_iter3_reg;
        cmp108_reg_1966_pp1_iter5_reg <= cmp108_reg_1966_pp1_iter4_reg;
        cmp108_reg_1966_pp1_iter6_reg <= cmp108_reg_1966_pp1_iter5_reg;
        cmp108_reg_1966_pp1_iter7_reg <= cmp108_reg_1966_pp1_iter6_reg;
        cmp108_reg_1966_pp1_iter8_reg <= cmp108_reg_1966_pp1_iter7_reg;
        data_mux_out_V_1_reg_2200 <= {{grp_fu_1668_p2[31:16]}};
        data_mux_out_overlap_V_1_reg_2212 <= {{grp_fu_1684_p2[31:16]}};
        icmp_ln204_reg_2071_pp1_iter2_reg <= icmp_ln204_reg_2071;
        icmp_ln204_reg_2071_pp1_iter3_reg <= icmp_ln204_reg_2071_pp1_iter2_reg;
        icmp_ln204_reg_2071_pp1_iter4_reg <= icmp_ln204_reg_2071_pp1_iter3_reg;
        icmp_ln204_reg_2071_pp1_iter5_reg <= icmp_ln204_reg_2071_pp1_iter4_reg;
        icmp_ln204_reg_2071_pp1_iter6_reg <= icmp_ln204_reg_2071_pp1_iter5_reg;
        icmp_ln204_reg_2071_pp1_iter7_reg <= icmp_ln204_reg_2071_pp1_iter6_reg;
        icmp_ln576_reg_2128 <= icmp_ln576_fu_1033_p2;
        icmp_ln692_reg_1962_pp1_iter2_reg <= icmp_ln692_reg_1962_pp1_iter1_reg;
        icmp_ln692_reg_1962_pp1_iter3_reg <= icmp_ln692_reg_1962_pp1_iter2_reg;
        icmp_ln692_reg_1962_pp1_iter4_reg <= icmp_ln692_reg_1962_pp1_iter3_reg;
        icmp_ln692_reg_1962_pp1_iter5_reg <= icmp_ln692_reg_1962_pp1_iter4_reg;
        icmp_ln692_reg_1962_pp1_iter6_reg <= icmp_ln692_reg_1962_pp1_iter5_reg;
        icmp_ln692_reg_1962_pp1_iter7_reg <= icmp_ln692_reg_1962_pp1_iter6_reg;
        icmp_ln692_reg_1962_pp1_iter8_reg <= icmp_ln692_reg_1962_pp1_iter7_reg;
        icmp_ln809_reg_2182_pp1_iter7_reg <= icmp_ln809_reg_2182;
        icmp_ln809_reg_2182_pp1_iter8_reg <= icmp_ln809_reg_2182_pp1_iter7_reg;
        icmp_ln809_reg_2182_pp1_iter9_reg <= icmp_ln809_reg_2182_pp1_iter8_reg;
        icmp_ln886_4_reg_2133 <= icmp_ln886_4_fu_1039_p2;
        or_ln489_reg_2218 <= or_ln489_fu_1319_p2;
        ouput_buffer_V_0_0_addr_1_reg_2224 <= conv_i82_i_fu_1324_p1;
        ouput_buffer_V_0_0_addr_1_reg_2224_pp1_iter9_reg <= ouput_buffer_V_0_0_addr_1_reg_2224;
        out_index_val_V_reg_2021_pp1_iter2_reg <= out_index_val_V_reg_2021;
        out_index_val_V_reg_2021_pp1_iter3_reg <= out_index_val_V_reg_2021_pp1_iter2_reg;
        out_index_val_V_reg_2021_pp1_iter4_reg <= out_index_val_V_reg_2021_pp1_iter3_reg;
        out_index_val_V_reg_2021_pp1_iter5_reg <= out_index_val_V_reg_2021_pp1_iter4_reg;
        out_index_val_V_reg_2021_pp1_iter6_reg <= out_index_val_V_reg_2021_pp1_iter5_reg;
        out_index_val_V_reg_2021_pp1_iter7_reg <= out_index_val_V_reg_2021_pp1_iter6_reg;
        out_index_val_V_reg_2021_pp1_iter8_reg <= out_index_val_V_reg_2021_pp1_iter7_reg;
        p_Result_4_reg_2186 <= p_Result_4_fu_1274_p1;
        p_Result_s_reg_2122 <= p_Result_s_fu_995_p1;
        procBlock_out_V_2_reg_2206 <= {{grp_fu_1675_p3[31:16]}};
        procBlock_out_V_reg_2194 <= {{grp_fu_1659_p3[31:16]}};
        temp_sum_V_reg_2230 <= temp_sum_V_fu_1587_p2;
        xor_ln890_reg_2091 <= xor_ln890_fu_889_p2;
        xor_ln890_reg_2091_pp1_iter3_reg <= xor_ln890_reg_2091;
        xor_ln890_reg_2091_pp1_iter4_reg <= xor_ln890_reg_2091_pp1_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln692_fu_516_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        Xindex_output_next_V_fu_132 <= p_Val2_s_fu_550_p3;
        p_Val2_1_fu_160 <= p_Val2_5_fu_538_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state74)) begin
        bit_select_i_i90_i_reg_1892 <= bit_select_i_i90_i_fu_425_p2;
        cmp10531_reg_1918 <= cmp10531_fu_460_p2;
        empty_49_reg_1922 <= empty_49_fu_471_p2;
        lhs_V_6_reg_1908[31 : 0] <= lhs_V_6_fu_442_p1[31 : 0];
        out_div_4_reg_1869 <= grp_fu_383_p2;
        rev_reg_1913 <= rev_fu_454_p2;
        rhs_4_reg_1887[31 : 0] <= rhs_4_fu_407_p1[31 : 0];
        sel_tmp_reg_1927 <= sel_tmp_fu_477_p2;
        shl_ln213_reg_1882[31 : 1] <= shl_ln213_fu_402_p2[31 : 1];
        sub158_i_reg_1903 <= sub158_i_fu_436_p2;
        sub162_i_reg_1897 <= sub162_i_fu_431_p2;
        trunc_ln213_reg_1877 <= trunc_ln213_fu_398_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == DDR_wr_en_1_reg_2153_pp1_iter8_reg) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        buffer_data_temp_reg_2236 <= buffer_data_temp_fu_1600_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln692_fu_516_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        cmp108_reg_1966 <= cmp108_fu_527_p2;
        icmp_ln878_2_reg_2010 <= icmp_ln878_2_fu_585_p2;
        index_fract_value_V_reg_1982 <= index_fract_value_V_fu_557_p1;
        output_buffer_index_next_V_1_reg_2015 <= {{p_Val2_s_fu_550_p3[31:16]}};
        output_buffer_index_start_V_reg_1998 <= {{p_Val2_5_fu_538_p3[31:16]}};
        p_Val2_5_reg_1975 <= p_Val2_5_fu_538_p3;
        sub_value_V_1_reg_2005 <= sub_value_V_1_fu_580_p2;
        sub_value_V_reg_1992 <= sub_value_V_fu_561_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        cmp108_reg_1966_pp1_iter1_reg <= cmp108_reg_1966;
        icmp_ln204_reg_2071 <= icmp_ln204_fu_801_p2;
        icmp_ln218_1_reg_2081 <= icmp_ln218_1_fu_806_p2;
        icmp_ln692_reg_1962 <= icmp_ln692_fu_516_p2;
        icmp_ln692_reg_1962_pp1_iter1_reg <= icmp_ln692_reg_1962;
        icmp_ln870_11_reg_2086 <= icmp_ln870_11_fu_811_p2;
        icmp_ln870_9_reg_2051 <= icmp_ln870_9_fu_762_p2;
        icmp_ln886_2_reg_2056 <= icmp_ln886_2_fu_776_p2;
        index_fract_value_V_reg_1982_pp1_iter1_reg <= index_fract_value_V_reg_1982;
        out_index_val_V_reg_2021 <= out_index_val_V_fu_653_p1;
        output_buffer_index_next_V_5_reg_2034 <= output_buffer_index_next_V_5_fu_686_p3;
        overlap_next_pixel_V_reg_2061 <= overlap_next_pixel_V_fu_790_p2;
        ret_3_reg_2046 <= ret_3_fu_750_p2;
        ret_6_reg_2066 <= ret_6_fu_795_p2;
        sub_value_V_reg_1992_pp1_iter1_reg <= sub_value_V_reg_1992;
        t1_reg_2041 <= t1_fu_740_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln686_fu_493_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state75))) begin
        cmp_i_i109_i_reg_1942 <= cmp_i_i109_i_fu_502_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state73)) begin
        cmp_i_i937_i_reg_1860 <= cmp_i_i937_i_fu_389_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == DDR_wr_en_1_reg_2153) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        icmp_ln809_reg_2182 <= icmp_ln809_fu_1245_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln692_reg_1962_pp1_iter3_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        icmp_ln878_4_reg_2138 <= icmp_ln878_4_fu_1083_p2;
        ret_11_reg_2143 <= ret_11_fu_1092_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        out_div_3_reg_1737 <= grp_fu_287_p2;
        zext_ln29_1_reg_1731[15 : 0] <= zext_ln29_1_fu_296_p1[15 : 0];
        zext_ln29_2_reg_1726[15 : 0] <= zext_ln29_2_fu_293_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        output_buffer_index_next_V_reg_1956 <= output_buffer_index_next_V_fu_510_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state75)) begin
        row_index_V_1_reg_1933 <= row_index_V_1_fu_487_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln686_fu_493_p2 == 1'd0) & (cmp10531_reg_1918 == 1'd0) & (1'b1 == ap_CS_fsm_state75))) begin
        weight_value_V_reg_1947 <= weight_value_V_fu_507_p1;
    end
end

always @ (*) begin
    if ((icmp_ln692_fu_516_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state76 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state76 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln686_fu_493_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state75)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter9 == 1'b0) & (ap_enable_reg_pp1_iter8 == 1'b0) & (ap_enable_reg_pp1_iter7 == 1'b0) & (ap_enable_reg_pp1_iter6 == 1'b0) & (ap_enable_reg_pp1_iter5 == 1'b0) & (ap_enable_reg_pp1_iter4 == 1'b0) & (ap_enable_reg_pp1_iter3 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0) & (ap_enable_reg_pp1_iter10 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln692_reg_1962 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        ap_phi_mux_output_buffer_index_start_V_5_phi_fu_267_p4 = output_buffer_index_next_V_reg_1956;
    end else begin
        ap_phi_mux_output_buffer_index_start_V_5_phi_fu_267_p4 = output_buffer_index_start_V_5_reg_263;
    end
end

always @ (*) begin
    if (((icmp_ln686_fu_493_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state75))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        grp_fu_1643_ce = 1'b1;
    end else begin
        grp_fu_1643_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        grp_fu_1652_ce = 1'b1;
    end else begin
        grp_fu_1652_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        grp_fu_1659_ce = 1'b1;
    end else begin
        grp_fu_1659_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        grp_fu_1668_ce = 1'b1;
    end else begin
        grp_fu_1668_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        grp_fu_1675_ce = 1'b1;
    end else begin
        grp_fu_1675_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        grp_fu_1684_ce = 1'b1;
    end else begin
        grp_fu_1684_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_287_ap_start = 1'b1;
    end else begin
        grp_fu_287_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        grp_fu_323_ap_start = 1'b1;
    end else begin
        grp_fu_323_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        grp_fu_383_ap_start = 1'b1;
    end else begin
        grp_fu_383_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        img_gray_433_blk_n = img_gray_433_empty_n;
    end else begin
        img_gray_433_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        img_gray_433_read = 1'b1;
    end else begin
        img_gray_433_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln809_reg_2182_pp1_iter9_reg == 1'd1) & (1'd1 == DDR_wr_en_1_reg_2153_pp1_iter9_reg) & (ap_enable_reg_pp1_iter10 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        img_out_434_blk_n = img_out_434_full_n;
    end else begin
        img_out_434_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op522_write_state86 == 1'b1) & (ap_enable_reg_pp1_iter10 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        img_out_434_write = 1'b1;
    end else begin
        img_out_434_write = 1'b0;
    end
end

always @ (*) begin
    if ((((1'd0 == and_ln218_1_reg_2096_pp1_iter9_reg) & (1'd0 == DDR_wr_en_1_reg_2153_pp1_iter9_reg) & (ap_enable_reg_pp1_iter10 == 1'b1) & (1'b0 == ap_block_pp1_stage0)) | ((1'd1 == DDR_wr_en_1_reg_2153_pp1_iter9_reg) & (ap_enable_reg_pp1_iter10 == 1'b1) & (1'b0 == ap_block_pp1_stage0)))) begin
        ouput_buffer_V_0_0_address0 = ouput_buffer_V_0_0_addr_1_reg_2224_pp1_iter9_reg;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        ouput_buffer_V_0_0_address0 = conv_i396_fu_311_p1;
    end else begin
        ouput_buffer_V_0_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state37) | ((1'd0 == and_ln218_1_reg_2096_pp1_iter9_reg) & (1'd0 == DDR_wr_en_1_reg_2153_pp1_iter9_reg) & (ap_enable_reg_pp1_iter10 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((1'd1 == DDR_wr_en_1_reg_2153_pp1_iter9_reg) & (ap_enable_reg_pp1_iter10 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        ouput_buffer_V_0_0_ce0 = 1'b1;
    end else begin
        ouput_buffer_V_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter8 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        ouput_buffer_V_0_0_ce1 = 1'b1;
    end else begin
        ouput_buffer_V_0_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == DDR_wr_en_1_reg_2153_pp1_iter9_reg) & (ap_enable_reg_pp1_iter10 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        ouput_buffer_V_0_0_d0 = buffer_data_temp_reg_2236;
    end else if (((1'd0 == and_ln218_1_reg_2096_pp1_iter9_reg) & (1'd0 == DDR_wr_en_1_reg_2153_pp1_iter9_reg) & (ap_enable_reg_pp1_iter10 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        ouput_buffer_V_0_0_d0 = temp_sum_V_reg_2230;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        ouput_buffer_V_0_0_d0 = 16'd0;
    end else begin
        ouput_buffer_V_0_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'd0 == and_ln218_1_reg_2096_pp1_iter9_reg) & (1'd0 == DDR_wr_en_1_reg_2153_pp1_iter9_reg) & (ap_enable_reg_pp1_iter10 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((icmp_ln878_fu_305_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state37)) | ((1'd1 == DDR_wr_en_1_reg_2153_pp1_iter9_reg) & (ap_enable_reg_pp1_iter10 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        ouput_buffer_V_0_0_we0 = 1'b1;
    end else begin
        ouput_buffer_V_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            if (((icmp_ln878_fu_305_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state37))) begin
                ap_NS_fsm = ap_ST_fsm_state37;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            if (((icmp_ln686_fu_493_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state75))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((icmp_ln686_fu_493_p2 == 1'd0) & (cmp10531_reg_1918 == 1'd0) & (1'b1 == ap_CS_fsm_state75))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state87;
            end
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((ap_enable_reg_pp1_iter1 == 1'b0) & (icmp_ln692_fu_516_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone)) & ~((ap_enable_reg_pp1_iter9 == 1'b0) & (ap_enable_reg_pp1_iter10 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if ((((ap_enable_reg_pp1_iter9 == 1'b0) & (ap_enable_reg_pp1_iter10 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone)) | ((ap_enable_reg_pp1_iter1 == 1'b0) & (icmp_ln692_fu_516_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state87;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state87 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign DDR_wr_en_1_fu_1156_p2 = (empty_49_reg_1922 | DDR_wr_en_tmp_fu_1150_p2);

assign DDR_wr_en_tmp_fu_1150_p2 = (or_ln204_fu_1125_p2 & and_ln201_fu_1145_p2);

assign DDR_write0_temp_V_1_fu_1580_p3 = ((p_Result_4_reg_2186[0:0] == 1'b1) ? update_1_fu_1552_p3 : update_fu_1452_p3);

assign DDR_write0_temp_V_fu_1465_p3 = ((and_ln488_fu_1460_p2[0:0] == 1'b1) ? 16'd0 : update_fu_1452_p3);

assign DDR_write1_temp_V_fu_1564_p3 = ((and_ln488_1_fu_1560_p2[0:0] == 1'b1) ? 16'd0 : update_1_fu_1552_p3);

assign Wx_V_0_0_1_fu_919_p1 = out_div_3_reg_1737[16:0];

assign Wx_for_Nplus1_Procblock_fu_877_p3 = ((and_ln166_fu_871_p2[0:0] == 1'b1) ? index_fract_value_V_reg_1982_pp1_iter1_reg : 16'd0);

assign Wy0_fu_1174_p3 = ((Yaxis_overlap_en_fu_156[0:0] == 1'b1) ? sub_ln213_fu_1168_p2 : trunc_ln213_reg_1877);

assign Wy1_fu_1181_p3 = ((Yaxis_overlap_en_fu_156[0:0] == 1'b1) ? p_Result_s_reg_2122 : 16'd0);

assign Xindex_output_next_V_1_fu_545_p2 = (Xindex_output_next_V_fu_132 + out_div_3_reg_1737);

assign Yaxis_overlap_en_1_fu_1231_p2 = (icmp_ln886_5_fu_1222_p2 & and_ln878_fu_1227_p2);

assign Yindex_output_V_4_fu_1061_p3 = ((icmp_ln204_reg_2071_pp1_iter3_reg[0:0] == 1'b1) ? Yindex_output_V_fu_1051_p2 : Yindex_output_V_1_fu_136);

assign Yindex_output_V_fu_1051_p2 = (Yindex_output_V_1_fu_136 + out_div_4_reg_1869);

assign Yindex_output_precision_error_V_fu_1113_p2 = ($signed(17'd65536) - $signed(zext_ln674_fu_1110_p1));

assign Yindex_output_prev_V_1_fu_1056_p2 = (Yindex_output_prev_V_fu_140 + out_div_4_reg_1869);

assign Yindex_output_prev_V_2_fu_1068_p3 = ((icmp_ln204_reg_2071_pp1_iter3_reg[0:0] == 1'b1) ? Yindex_output_prev_V_1_fu_1056_p2 : Yindex_output_prev_V_fu_140);

assign Yindex_output_prev_precision_error_V_fu_1007_p2 = ($signed(17'd65536) - $signed(zext_ln674_1_fu_1003_p1));

assign add_ln208_1_fu_1438_p2 = (data_previous_overlap_V_4_fu_1419_p3 + data_mux_out_overlap_V_2_fu_1407_p3);

assign add_ln208_2_fu_1532_p2 = (data_previous_V_5_fu_1512_p3 + data_mux_out_V_3_fu_1502_p3);

assign add_ln208_3_fu_1538_p2 = (data_previous_overlap_V_5_fu_1519_p3 + data_mux_out_overlap_V_3_fu_1507_p3);

assign add_ln208_fu_1432_p2 = (data_previous_V_4_fu_1412_p3 + data_mux_out_V_2_fu_1402_p3);

assign add_ln691_fu_533_p2 = (p_Val2_1_fu_160 + out_div_3_reg_1737);

assign and_ln166_fu_871_p2 = (icmp_ln886_3_fu_866_p2 & icmp_ln870_10_fu_861_p2);

assign and_ln201_fu_1145_p2 = (or_ln201_2_fu_1139_p2 & icmp_ln886_4_reg_2133);

assign and_ln218_1_fu_905_p2 = (icmp_ln218_1_reg_2081 & and_ln218_fu_900_p2);

assign and_ln218_fu_900_p2 = (icmp_ln218_fu_895_p2 & bit_select_i_i90_i_reg_1892);

assign and_ln488_1_fu_1560_p2 = (p_Result_4_reg_2186 & or_ln489_reg_2218);

assign and_ln488_fu_1460_p2 = (or_ln489_reg_2218 & cmp72_i_fu_1369_p2);

assign and_ln72_1_fu_633_p2 = (icmp_ln878_1_fu_614_p2 & and_ln72_fu_628_p2);

assign and_ln72_fu_628_p2 = (sel_tmp_reg_1927 & icmp_ln886_fu_618_p2);

assign and_ln870_1_fu_837_p2 = (icmp_ln886_2_reg_2056 & icmp_ln870_fu_819_p2);

assign and_ln870_fu_832_p2 = (icmp_ln878_3_fu_827_p2 & icmp_ln870_9_reg_2051);

assign and_ln878_fu_1227_p2 = (rev_reg_1913 & icmp_ln878_4_reg_2138);

assign and_ln89_1_fu_681_p2 = (icmp_ln878_2_reg_2010 & and_ln89_fu_676_p2);

assign and_ln89_fu_676_p2 = (sel_tmp_reg_1927 & icmp_ln886_1_fu_661_p2);

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd75];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state73 = ap_CS_fsm[32'd72];

assign ap_CS_fsm_state74 = ap_CS_fsm[32'd73];

assign ap_CS_fsm_state75 = ap_CS_fsm[32'd74];

assign ap_CS_fsm_state87 = ap_CS_fsm[32'd76];

always @ (*) begin
    ap_block_pp1 = ((1'b1 == ap_block_pp1_stage0_subdone) & (ap_ST_fsm_pp1_stage0 == ap_CS_fsm));
end

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_01001 = (((ap_predicate_op522_write_state86 == 1'b1) & (ap_enable_reg_pp1_iter10 == 1'b1) & (img_out_434_full_n == 1'b0)) | ((img_gray_433_empty_n == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_pp1_stage0_11001 = (((ap_predicate_op522_write_state86 == 1'b1) & (ap_enable_reg_pp1_iter10 == 1'b1) & (img_out_434_full_n == 1'b0)) | ((img_gray_433_empty_n == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = (((ap_predicate_op522_write_state86 == 1'b1) & (ap_enable_reg_pp1_iter10 == 1'b1) & (img_out_434_full_n == 1'b0)) | ((img_gray_433_empty_n == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b1)));
end

assign ap_block_state76_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state77_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state78_pp1_stage0_iter2 = (img_gray_433_empty_n == 1'b0);
end

assign ap_block_state79_pp1_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state80_pp1_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state81_pp1_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state82_pp1_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state83_pp1_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state84_pp1_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state85_pp1_stage0_iter9 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state86_pp1_stage0_iter10 = ((ap_predicate_op522_write_state86 == 1'b1) & (img_out_434_full_n == 1'b0));
end

assign ap_enable_operation_462 = (1'b1 == 1'b1);

assign ap_enable_operation_507 = (1'b1 == 1'b1);

always @ (*) begin
    ap_enable_operation_517 = (ap_predicate_op517_store_state86 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_521 = (1'd1 == DDR_wr_en_1_reg_2153_pp1_iter9_reg);
end

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

always @ (*) begin
    ap_enable_state84_pp1_iter8_stage0 = ((ap_enable_reg_pp1_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0));
end

always @ (*) begin
    ap_enable_state85_pp1_iter9_stage0 = ((ap_enable_reg_pp1_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0));
end

always @ (*) begin
    ap_enable_state86_pp1_iter10_stage0 = ((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter10 == 1'b1));
end

always @ (*) begin
    ap_predicate_op517_store_state86 = ((1'd0 == and_ln218_1_reg_2096_pp1_iter9_reg) & (1'd0 == DDR_wr_en_1_reg_2153_pp1_iter9_reg));
end

always @ (*) begin
    ap_predicate_op522_write_state86 = ((icmp_ln809_reg_2182_pp1_iter9_reg == 1'd1) & (1'd1 == DDR_wr_en_1_reg_2153_pp1_iter9_reg));
end

assign bit_select_i_i90_i_fu_425_p2 = ((tmp_5_fu_417_p3 == 17'd0) ? 1'b1 : 1'b0);

assign buffer_data_temp_fu_1600_p3 = ((Yaxis_overlap_en_load_reg_2148_pp1_iter8_reg[0:0] == 1'b1) ? select_ln530_fu_1593_p3 : 16'd0);

assign cmp10531_fu_460_p2 = ((p_read1 == 16'd0) ? 1'b1 : 1'b0);

assign cmp108_fu_527_p2 = ((ap_phi_mux_output_buffer_index_start_V_5_phi_fu_267_p4 == 16'd0) ? 1'b1 : 1'b0);

assign cmp72_i_fu_1369_p2 = (p_Result_4_reg_2186 ^ 1'd1);

assign cmp_i_i109_i_fu_502_p2 = ((zext_ln686_fu_498_p1 == sub158_i_reg_1903) ? 1'b1 : 1'b0);

assign cmp_i_i937_i_fu_389_p2 = ((grp_fu_323_p2 == 32'd65536) ? 1'b1 : 1'b0);

assign conv_i396_fu_311_p1 = dim3_V_reg_241;

assign conv_i82_i_fu_1324_p1 = write_col_index_V_fu_144;

assign data_mux_out_V_2_fu_1402_p3 = ((out_index_val_V_reg_2021_pp1_iter8_reg[0:0] == 1'b1) ? data_mux_out_V_1_reg_2200 : procBlock_out_V_reg_2194);

assign data_mux_out_V_3_fu_1502_p3 = ((out_index_val_V_reg_2021_pp1_iter8_reg[0:0] == 1'b1) ? procBlock_out_V_reg_2194 : data_mux_out_V_1_reg_2200);

assign data_mux_out_overlap_V_2_fu_1407_p3 = ((out_index_val_V_reg_2021_pp1_iter8_reg[0:0] == 1'b1) ? data_mux_out_overlap_V_1_reg_2212 : procBlock_out_V_2_reg_2206);

assign data_mux_out_overlap_V_3_fu_1507_p3 = ((out_index_val_V_reg_2021_pp1_iter8_reg[0:0] == 1'b1) ? procBlock_out_V_2_reg_2206 : data_mux_out_overlap_V_1_reg_2212);

assign data_mux_out_status_V_2_fu_1395_p3 = ((out_index_val_V_reg_2021_pp1_iter8_reg[0:0] == 1'b1) ? p_Result_5_fu_1379_p3 : p_Result_6_fu_1387_p3);

assign data_mux_out_status_V_5_fu_1495_p3 = ((out_index_val_V_reg_2021_pp1_iter8_reg[0:0] == 1'b1) ? p_Result_7_fu_1481_p3 : p_Result_8_fu_1488_p3);

assign data_previous_V_4_fu_1412_p3 = ((cmp108_reg_1966_pp1_iter8_reg[0:0] == 1'b1) ? 16'd0 : data_previous_V_fu_164);

assign data_previous_V_5_fu_1512_p3 = ((cmp108_reg_1966_pp1_iter8_reg[0:0] == 1'b1) ? 16'd0 : data_previous_V_2_fu_168);

assign data_previous_overlap_V_4_fu_1419_p3 = ((cmp108_reg_1966_pp1_iter8_reg[0:0] == 1'b1) ? 16'd0 : data_previous_overlap_V_fu_172);

assign data_previous_overlap_V_5_fu_1519_p3 = ((cmp108_reg_1966_pp1_iter8_reg[0:0] == 1'b1) ? 16'd0 : data_previous_overlap_V_2_fu_176);

assign dim3_V_1_fu_299_p2 = (dim3_V_reg_241 + 9'd1);

assign empty_49_fu_471_p2 = ((empty_fu_465_p2 != 17'd0) ? 1'b1 : 1'b0);

assign empty_fu_465_p2 = (trunc_ln213_fu_398_p1 & tmp_5_fu_417_p3);

assign grp_fu_1643_p0 = grp_fu_1643_p00;

assign grp_fu_1643_p00 = select_ln237_fu_931_p3;

assign grp_fu_1643_p1 = grp_fu_1643_p10;

assign grp_fu_1643_p10 = in_data_V_fu_964_p3;

assign grp_fu_1643_p2 = 24'd128;

assign grp_fu_1652_p0 = grp_fu_1652_p00;

assign grp_fu_1652_p00 = Wx_for_Nplus1_Procblock_fu_877_p3;

assign grp_fu_1652_p1 = grp_fu_1652_p10;

assign grp_fu_1652_p10 = img_gray_433_dout;

assign grp_fu_1659_p0 = zext_ln1345_1_fu_1201_p1;

assign grp_fu_1659_p1 = zext_ln1345_fu_1197_p1;

assign grp_fu_1659_p2 = 32'd32768;

assign grp_fu_1668_p0 = zext_ln1345_2_fu_1214_p1;

assign grp_fu_1668_p1 = zext_ln1345_fu_1197_p1;

assign grp_fu_1675_p0 = zext_ln1345_1_fu_1201_p1;

assign grp_fu_1675_p1 = zext_ln1345_3_fu_1218_p1;

assign grp_fu_1675_p2 = 32'd32768;

assign grp_fu_1684_p0 = zext_ln1345_2_fu_1214_p1;

assign grp_fu_1684_p1 = zext_ln1345_3_fu_1218_p1;

assign grp_fu_287_p0 = {{p_read3}, {16'd0}};

assign grp_fu_287_p1 = grp_fu_287_p10;

assign grp_fu_287_p10 = p_read1;

assign grp_fu_323_p0 = {{p_read1}, {16'd0}};

assign grp_fu_323_p1 = zext_ln29_1_reg_1731;

assign grp_fu_383_p0 = {{p_read2}, {16'd0}};

assign grp_fu_383_p1 = grp_fu_383_p10;

assign grp_fu_383_p10 = p_read;

assign icmp_ln204_fu_801_p2 = ((zext_ln692_fu_610_p1 == sub162_i_reg_1897) ? 1'b1 : 1'b0);

assign icmp_ln218_1_fu_806_p2 = ((zext_ln692_fu_610_p1 != sub162_i_reg_1897) ? 1'b1 : 1'b0);

assign icmp_ln218_fu_895_p2 = ((ouput_index_write_counter_V_fu_148 > output_buffer_index_next_V_5_reg_2034) ? 1'b1 : 1'b0);

assign icmp_ln237_fu_910_p2 = ((index_fract_value_V_reg_1982_pp1_iter1_reg > weight_value_V_reg_1947) ? 1'b1 : 1'b0);

assign icmp_ln576_fu_1033_p2 = ((p_Result_1_fu_1013_p4 != p_Result_2_fu_1023_p4) ? 1'b1 : 1'b0);

assign icmp_ln686_fu_493_p2 = ((row_index_V_reg_252 == p_read) ? 1'b1 : 1'b0);

assign icmp_ln692_fu_516_p2 = ((ap_phi_mux_output_buffer_index_start_V_5_phi_fu_267_p4 == p_read1) ? 1'b1 : 1'b0);

assign icmp_ln809_fu_1245_p2 = (($signed(out_col_index_fu_152) < $signed(zext_ln29_1_reg_1731)) ? 1'b1 : 1'b0);

assign icmp_ln870_10_fu_861_p2 = ((ret_6_reg_2066 == zext_ln870_fu_858_p1) ? 1'b1 : 1'b0);

assign icmp_ln870_11_fu_811_p2 = ((output_buffer_index_start_V_6_fu_646_p3 == output_buffer_index_start_V_reg_1998) ? 1'b1 : 1'b0);

assign icmp_ln870_9_fu_762_p2 = ((zext_ln1346_fu_657_p1 == ret_4_fu_756_p2) ? 1'b1 : 1'b0);

assign icmp_ln870_fu_819_p2 = ((ret_3_reg_2046 == 17'd1) ? 1'b1 : 1'b0);

assign icmp_ln874_1_fu_1526_p2 = ((data_mux_out_status_V_5_fu_1495_p3 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln874_fu_1426_p2 = ((data_mux_out_status_V_2_fu_1395_p3 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln878_1_fu_614_p2 = ((index_fract_value_V_reg_1982 < weight_value_V_reg_1947) ? 1'b1 : 1'b0);

assign icmp_ln878_2_fu_585_p2 = ((index_fract_value_V_1_fu_576_p1 < weight_value_V_reg_1947) ? 1'b1 : 1'b0);

assign icmp_ln878_3_fu_827_p2 = ((zext_ln878_fu_824_p1 < out_div_3_reg_1737) ? 1'b1 : 1'b0);

assign icmp_ln878_4_fu_1083_p2 = ((zext_ln674_2_fu_1079_p1 < out_div_4_reg_1869) ? 1'b1 : 1'b0);

assign icmp_ln878_fu_305_p2 = ((dim3_V_reg_241 == 9'd480) ? 1'b1 : 1'b0);

assign icmp_ln886_1_fu_661_p2 = ((sub_value_V_1_reg_2005 > 16'd65) ? 1'b1 : 1'b0);

assign icmp_ln886_2_fu_776_p2 = (($signed(ret_5_fu_771_p2) > $signed(33'd65)) ? 1'b1 : 1'b0);

assign icmp_ln886_3_fu_866_p2 = ((overlap_next_pixel_V_reg_2061 > 32'd65) ? 1'b1 : 1'b0);

assign icmp_ln886_4_fu_1039_p2 = ((Yindex_output_prev_precision_error_V_fu_1007_p2 > 17'd65) ? 1'b1 : 1'b0);

assign icmp_ln886_5_fu_1222_p2 = (($signed(ret_11_reg_2143) > $signed(33'd65)) ? 1'b1 : 1'b0);

assign icmp_ln886_fu_618_p2 = ((sub_value_V_reg_1992 > 16'd65) ? 1'b1 : 1'b0);

assign icmp_ln890_1_fu_884_p2 = ((output_buffer_index_next_V_5_reg_2034 < ouput_index_write_counter_V_fu_148) ? 1'b1 : 1'b0);

assign icmp_ln890_fu_1119_p2 = ((Yindex_output_precision_error_V_fu_1113_p2 < 17'd66) ? 1'b1 : 1'b0);

assign img_out_434_din = {{sum_rounding_V_fu_1627_p2[15:8]}};

assign in_data_V_fu_964_p3 = ((or_ln138_1_fu_853_p2[0:0] == 1'b1) ? img_gray_433_dout : 8'd0);

assign index_fract_value_V_1_fu_576_p1 = p_Val2_s_fu_550_p3[15:0];

assign index_fract_value_V_fu_557_p1 = p_Val2_5_fu_538_p3[15:0];

assign int_bits_Xindex_out_V_fu_730_p4 = {{ret_2_fu_725_p2[31:16]}};

assign int_bits_Xindex_out_previous_V_2_fu_714_p3 = ((cmp108_reg_1966[0:0] == 1'b1) ? 16'd0 : int_bits_Xindex_out_previous_V_fu_704_p4);

assign int_bits_Xindex_out_previous_V_fu_704_p4 = {{ret_1_fu_698_p2[31:16]}};

assign lhs_V_6_fu_442_p1 = grp_fu_383_p2;

assign or_ln138_1_fu_853_p2 = (t1_reg_2041 | or_ln138_fu_848_p2);

assign or_ln138_fu_848_p2 = (t2_fu_842_p2 | cmp_i_i937_i_reg_1860);

assign or_ln201_1_fu_1134_p2 = (cmp_i_i109_i_reg_1942 | Yaxis_overlap_en_fu_156);

assign or_ln201_2_fu_1139_p2 = (or_ln201_fu_1129_p2 | or_ln201_1_fu_1134_p2);

assign or_ln201_fu_1129_p2 = (icmp_ln890_fu_1119_p2 | icmp_ln576_reg_2128);

assign or_ln204_fu_1125_p2 = (xor_ln890_reg_2091_pp1_iter4_reg | icmp_ln204_reg_2071_pp1_iter4_reg);

assign or_ln237_fu_914_p2 = (icmp_ln237_fu_910_p2 | cmp_i_i937_i_reg_1860);

assign or_ln489_fu_1319_p2 = (out_buffer_wr_en_fu_1278_p2 | DDR_wr_en_1_reg_2153_pp1_iter7_reg);

assign ouput_buffer_V_0_0_address1 = conv_i82_i_fu_1324_p1;

assign ouput_index_write_counter_V_1_fu_939_p2 = (ouput_index_write_counter_V_fu_148 + 16'd1);

assign ouput_index_write_counter_V_2_fu_953_p3 = ((icmp_ln204_reg_2071[0:0] == 1'b1) ? 16'd1 : select_ln752_fu_945_p3);

assign out_buffer_wr_en_fu_1278_p2 = (1'd1 ^ and_ln218_1_reg_2096_pp1_iter7_reg);

assign out_col_index_1_fu_1253_p2 = (out_col_index_fu_152 + 32'd1);

assign out_index_val_V_fu_653_p1 = output_buffer_index_start_V_6_fu_646_p3[0:0];

assign output_buffer_index_next_V_2_fu_666_p2 = ($signed(output_buffer_index_next_V_1_reg_2015) + $signed(16'd65535));

assign output_buffer_index_next_V_3_fu_671_p3 = ((cmp_i_i937_i_reg_1860[0:0] == 1'b1) ? output_buffer_index_next_V_reg_1956 : output_buffer_index_next_V_1_reg_2015);

assign output_buffer_index_next_V_5_fu_686_p3 = ((and_ln89_1_fu_681_p2[0:0] == 1'b1) ? output_buffer_index_next_V_2_fu_666_p2 : output_buffer_index_next_V_3_fu_671_p3);

assign output_buffer_index_next_V_fu_510_p2 = (ap_phi_mux_output_buffer_index_start_V_5_phi_fu_267_p4 + 16'd1);

assign output_buffer_index_start_V_2_fu_623_p2 = ($signed(output_buffer_index_start_V_reg_1998) + $signed(16'd65535));

assign output_buffer_index_start_V_3_fu_639_p3 = ((and_ln72_1_fu_633_p2[0:0] == 1'b1) ? output_buffer_index_start_V_2_fu_623_p2 : output_buffer_index_start_V_reg_1998);

assign output_buffer_index_start_V_6_fu_646_p3 = ((cmp_i_i937_i_reg_1860[0:0] == 1'b1) ? output_buffer_index_start_V_5_reg_263 : output_buffer_index_start_V_3_fu_639_p3);

assign overlap_next_pixel_V_fu_790_p2 = (r_fu_782_p3 - p_Val2_5_reg_1975);

assign p_Result_1_fu_1013_p4 = {{Yindex_output_V_1_fu_136[31:16]}};

assign p_Result_2_fu_1023_p4 = {{Yindex_output_prev_V_fu_140[31:16]}};

assign p_Result_3_fu_999_p1 = Yindex_output_prev_V_fu_140[15:0];

assign p_Result_4_fu_1274_p1 = write_col_index_V_fu_144[0:0];

assign p_Result_5_fu_1379_p3 = {{1'd1}, {xor_ln870_fu_1374_p2}};

assign p_Result_6_fu_1387_p3 = {{1'd0}, {xor_ln870_fu_1374_p2}};

assign p_Result_7_fu_1481_p3 = {{1'd0}, {out_index_val_V_reg_2021_pp1_iter8_reg}};

assign p_Result_8_fu_1488_p3 = {{1'd1}, {out_index_val_V_reg_2021_pp1_iter8_reg}};

assign p_Result_9_fu_1075_p1 = Yindex_output_V_4_fu_1061_p3[15:0];

assign p_Result_s_fu_995_p1 = Yindex_output_V_1_fu_136[15:0];

assign p_Val2_5_fu_538_p3 = ((cmp108_fu_527_p2[0:0] == 1'b1) ? out_div_3_reg_1737 : add_ln691_fu_533_p2);

assign p_Val2_s_fu_550_p3 = ((cmp108_fu_527_p2[0:0] == 1'b1) ? shl_ln213_reg_1882 : Xindex_output_next_V_1_fu_545_p2);

assign r_1_fu_1188_p4 = {{grp_fu_1643_p3[23:8]}};

assign r_3_fu_1205_p4 = {{grp_fu_1652_p2[23:8]}};

assign r_fu_782_p3 = {{output_buffer_index_next_V_5_fu_686_p3}, {16'd0}};

assign ret_11_fu_1092_p2 = (lhs_V_6_reg_1908 - zext_ln215_2_fu_1088_p1);

assign ret_1_fu_698_p2 = ($signed(ret_fu_694_p2) + $signed(32'd4294967231));

assign ret_2_fu_725_p2 = ($signed(p_Val2_5_reg_1975) + $signed(32'd4294967231));

assign ret_3_fu_750_p2 = (zext_ln215_fu_746_p1 - rhs_1_fu_721_p1);

assign ret_4_fu_756_p2 = ($signed(zext_ln215_fu_746_p1) + $signed(17'd131071));

assign ret_5_fu_771_p2 = (rhs_4_reg_1887 - zext_ln215_1_fu_768_p1);

assign ret_6_fu_795_p2 = (zext_ln1346_fu_657_p1 + 17'd1);

assign ret_fu_694_p2 = (p_Val2_5_reg_1975 - out_div_3_reg_1737);

assign rev_fu_454_p2 = (tmp_6_fu_446_p3 ^ 1'd1);

assign rhs_1_fu_721_p1 = int_bits_Xindex_out_previous_V_2_fu_714_p3;

assign rhs_4_fu_407_p1 = out_div_3_reg_1737;

assign row_index_V_1_fu_487_p2 = (row_index_V_reg_252 + 16'd1);

assign sel_tmp_fu_477_p2 = (cmp_i_i937_i_reg_1860 ^ 1'd1);

assign select_ln237_fu_931_p3 = ((or_ln237_fu_914_p2[0:0] == 1'b1) ? Wx_V_0_0_1_fu_919_p1 : zext_ln239_fu_927_p1);

assign select_ln239_fu_922_p3 = ((icmp_ln870_11_reg_2086[0:0] == 1'b1) ? index_fract_value_V_reg_1982_pp1_iter1_reg : sub_value_V_reg_1992_pp1_iter1_reg);

assign select_ln530_fu_1593_p3 = ((p_Result_4_reg_2186[0:0] == 1'b1) ? update_overlap_2_fu_1544_p3 : update_overlap_fu_1444_p3);

assign select_ln752_fu_945_p3 = ((xor_ln890_fu_889_p2[0:0] == 1'b1) ? ouput_index_write_counter_V_1_fu_939_p2 : ouput_index_write_counter_V_fu_148);

assign select_ln811_fu_1259_p3 = ((icmp_ln204_reg_2071_pp1_iter5_reg[0:0] == 1'b1) ? 32'd0 : out_col_index_1_fu_1253_p2);

assign select_ln819_fu_1338_p3 = ((and_ln218_1_reg_2096_pp1_iter7_reg[0:0] == 1'b1) ? write_col_index_V_fu_144 : write_col_index_V_1_fu_1332_p2);

assign shl_ln213_fu_402_p2 = out_div_3_reg_1737 << 32'd1;

assign sub158_i_fu_436_p2 = ($signed(zext_ln29_4_fu_395_p1) + $signed(17'd131071));

assign sub162_i_fu_431_p2 = ($signed(zext_ln29_2_reg_1726) + $signed(17'd131071));

assign sub_ln213_fu_1168_p2 = (zext_ln213_fu_1164_p1 - zext_ln674_fu_1110_p1);

assign sub_value_V_1_fu_580_p2 = (weight_value_V_reg_1947 - index_fract_value_V_1_fu_576_p1);

assign sub_value_V_fu_561_p2 = (weight_value_V_reg_1947 - index_fract_value_V_fu_557_p1);

assign sum_rounding_V_fu_1627_p2 = (temp_sum_V_reg_2230 + 16'd128);

assign t1_fu_740_p2 = ((output_buffer_index_start_V_6_fu_646_p3 == int_bits_Xindex_out_V_fu_730_p4) ? 1'b1 : 1'b0);

assign t2_fu_842_p2 = (and_ln870_fu_832_p2 & and_ln870_1_fu_837_p2);

assign temp_sum_V_fu_1587_p2 = (ouput_buffer_V_0_0_q1 + DDR_write0_temp_V_1_fu_1580_p3);

assign tmp_5_fu_417_p3 = {{tmp_fu_410_p3}, {16'd0}};

assign tmp_6_fu_446_p3 = grp_fu_383_p2[32'd16];

assign tmp_fu_410_p3 = out_div_3_reg_1737[32'd16];

assign trunc_ln213_fu_398_p1 = grp_fu_383_p2[16:0];

assign trunc_ln357_fu_1161_p1 = out_div_4_reg_1869[15:0];

assign update_1_fu_1552_p3 = ((icmp_ln874_1_fu_1526_p2[0:0] == 1'b1) ? data_previous_V_5_fu_1512_p3 : add_ln208_2_fu_1532_p2);

assign update_fu_1452_p3 = ((icmp_ln874_fu_1426_p2[0:0] == 1'b1) ? data_previous_V_4_fu_1412_p3 : add_ln208_fu_1432_p2);

assign update_overlap_2_fu_1544_p3 = ((icmp_ln874_1_fu_1526_p2[0:0] == 1'b1) ? data_previous_overlap_V_5_fu_1519_p3 : add_ln208_3_fu_1538_p2);

assign update_overlap_4_fu_1473_p3 = ((and_ln488_fu_1460_p2[0:0] == 1'b1) ? 16'd0 : update_overlap_fu_1444_p3);

assign update_overlap_5_fu_1572_p3 = ((and_ln488_1_fu_1560_p2[0:0] == 1'b1) ? 16'd0 : update_overlap_2_fu_1544_p3);

assign update_overlap_fu_1444_p3 = ((icmp_ln874_fu_1426_p2[0:0] == 1'b1) ? data_previous_overlap_V_4_fu_1419_p3 : add_ln208_1_fu_1438_p2);

assign weight_value_V_fu_507_p1 = out_div_3_reg_1737[15:0];

assign write_col_index_V_1_fu_1332_p2 = (write_col_index_V_fu_144 + 16'd1);

assign write_col_index_V_2_fu_1345_p3 = ((icmp_ln204_reg_2071_pp1_iter7_reg[0:0] == 1'b1) ? 16'd0 : select_ln819_fu_1338_p3);

assign xor_ln870_fu_1374_p2 = (out_index_val_V_reg_2021_pp1_iter8_reg ^ 1'd1);

assign xor_ln890_fu_889_p2 = (icmp_ln890_1_fu_884_p2 ^ 1'd1);

assign zext_ln1345_1_fu_1201_p1 = r_1_fu_1188_p4;

assign zext_ln1345_2_fu_1214_p1 = r_3_fu_1205_p4;

assign zext_ln1345_3_fu_1218_p1 = Wy1_fu_1181_p3;

assign zext_ln1345_fu_1197_p1 = Wy0_fu_1174_p3;

assign zext_ln1346_fu_657_p1 = output_buffer_index_start_V_6_fu_646_p3;

assign zext_ln213_fu_1164_p1 = trunc_ln357_fu_1161_p1;

assign zext_ln215_1_fu_768_p1 = index_fract_value_V_reg_1982;

assign zext_ln215_2_fu_1088_p1 = p_Result_9_fu_1075_p1;

assign zext_ln215_fu_746_p1 = int_bits_Xindex_out_V_fu_730_p4;

assign zext_ln239_fu_927_p1 = select_ln239_fu_922_p3;

assign zext_ln29_1_fu_296_p1 = p_read3;

assign zext_ln29_2_fu_293_p1 = p_read1;

assign zext_ln29_4_fu_395_p1 = p_read;

assign zext_ln674_1_fu_1003_p1 = p_Result_3_fu_999_p1;

assign zext_ln674_2_fu_1079_p1 = p_Result_9_fu_1075_p1;

assign zext_ln674_fu_1110_p1 = p_Result_s_reg_2122;

assign zext_ln686_fu_498_p1 = row_index_V_reg_252;

assign zext_ln692_fu_610_p1 = output_buffer_index_start_V_5_reg_263;

assign zext_ln870_fu_858_p1 = output_buffer_index_next_V_5_reg_2034;

assign zext_ln878_fu_824_p1 = index_fract_value_V_reg_1982_pp1_iter1_reg;

always @ (posedge ap_clk) begin
    zext_ln29_2_reg_1726[16] <= 1'b0;
    zext_ln29_1_reg_1731[31:16] <= 16'b0000000000000000;
    shl_ln213_reg_1882[0] <= 1'b0;
    rhs_4_reg_1887[32] <= 1'b0;
    lhs_V_6_reg_1908[32] <= 1'b0;
end

endmodule //image_accelerator_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s
