// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module image_accelerator_CoreProcessUpArea (
        ap_clk,
        ap_rst,
        A0,
        B0,
        A1,
        B1,
        Wx,
        Wy,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [7:0] A0;
input  [7:0] B0;
input  [7:0] A1;
input  [7:0] B1;
input  [31:0] Wx;
input  [31:0] Wy;
output  [7:0] ap_return;
input   ap_ce;

reg[7:0] ap_return;

reg   [31:0] Wy_read_reg_212;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] Wy_read_reg_212_pp0_iter1_reg;
reg   [31:0] Wx_read_reg_217;
reg   [31:0] Wx_read_reg_217_pp0_iter1_reg;
reg   [7:0] B1_read_reg_222;
reg   [7:0] A1_read_reg_227;
reg   [7:0] B0_read_reg_233;
reg   [7:0] A0_read_reg_238;
reg   [7:0] A0_read_reg_238_pp0_iter1_reg;
reg   [7:0] A0_read_reg_238_pp0_iter2_reg;
reg   [7:0] A0_read_reg_238_pp0_iter3_reg;
reg   [7:0] A0_read_reg_238_pp0_iter4_reg;
wire   [9:0] val0_fu_117_p2;
reg  signed [9:0] val0_reg_254;
wire   [8:0] val1_fu_123_p2;
reg  signed [8:0] val1_reg_259;
wire   [8:0] val2_fu_129_p2;
reg  signed [8:0] val2_reg_264;
reg   [31:0] trunc_ln_reg_269;
wire   [39:0] grp_fu_157_p2;
reg   [39:0] mul_ln40_reg_304;
wire   [39:0] grp_fu_166_p2;
reg   [39:0] mul_ln40_1_reg_309;
reg   [39:0] mul_ln40_1_reg_309_pp0_iter4_reg;
wire   [39:0] grp_fu_175_p2;
reg   [39:0] mul_ln40_2_reg_314;
wire   [39:0] add_ln52_1_fu_181_p2;
reg   [39:0] add_ln52_1_reg_319;
wire    ap_block_pp0_stage0;
wire   [31:0] grp_fu_80_p0;
wire   [31:0] grp_fu_80_p1;
wire   [8:0] zext_ln43_fu_86_p1;
wire   [8:0] zext_ln43_2_fu_92_p1;
wire   [8:0] sub_ln43_fu_101_p2;
wire  signed [9:0] sext_ln43_fu_107_p1;
wire   [9:0] zext_ln43_4_fu_98_p1;
wire   [9:0] sub_ln43_1_fu_111_p2;
wire   [9:0] zext_ln43_1_fu_89_p1;
wire   [8:0] zext_ln43_3_fu_95_p1;
wire   [63:0] grp_fu_80_p2;
wire   [31:0] grp_fu_157_p0;
wire   [31:0] grp_fu_166_p0;
wire   [31:0] grp_fu_175_p0;
wire   [39:0] P4_fu_185_p3;
wire   [39:0] add_ln52_fu_192_p2;
wire   [39:0] add_ln52_2_fu_197_p2;
reg    grp_fu_80_ce;
reg    grp_fu_157_ce;
reg    grp_fu_166_ce;
reg    grp_fu_175_ce;
reg    ap_ce_reg;
reg   [7:0] A0_int_reg;
reg   [7:0] B0_int_reg;
reg   [7:0] A1_int_reg;
reg   [7:0] B1_int_reg;
reg   [31:0] Wx_int_reg;
reg   [31:0] Wy_int_reg;
reg   [7:0] ap_return_int_reg;
wire   [39:0] grp_fu_157_p00;
wire   [39:0] grp_fu_166_p00;
wire   [39:0] grp_fu_175_p00;
wire   [63:0] grp_fu_80_p00;
wire   [63:0] grp_fu_80_p10;

image_accelerator_mul_32ns_32ns_64_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_2_0_U68(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_80_p0),
    .din1(grp_fu_80_p1),
    .ce(grp_fu_80_ce),
    .dout(grp_fu_80_p2)
);

image_accelerator_mul_32ns_10s_40_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 40 ))
mul_32ns_10s_40_2_0_U69(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_157_p0),
    .din1(val0_reg_254),
    .ce(grp_fu_157_ce),
    .dout(grp_fu_157_p2)
);

image_accelerator_mul_32ns_9s_40_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 40 ))
mul_32ns_9s_40_2_0_U70(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_166_p0),
    .din1(val1_reg_259),
    .ce(grp_fu_166_ce),
    .dout(grp_fu_166_p2)
);

image_accelerator_mul_32ns_9s_40_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 40 ))
mul_32ns_9s_40_2_0_U71(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_175_p0),
    .din1(val2_reg_264),
    .ce(grp_fu_175_ce),
    .dout(grp_fu_175_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        A0_int_reg <= A0;
        A1_int_reg <= A1;
        B0_int_reg <= B0;
        B1_int_reg <= B1;
        Wx_int_reg <= Wx;
        Wy_int_reg <= Wy;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        A0_read_reg_238 <= A0_int_reg;
        A0_read_reg_238_pp0_iter1_reg <= A0_read_reg_238;
        A0_read_reg_238_pp0_iter2_reg <= A0_read_reg_238_pp0_iter1_reg;
        A0_read_reg_238_pp0_iter3_reg <= A0_read_reg_238_pp0_iter2_reg;
        A0_read_reg_238_pp0_iter4_reg <= A0_read_reg_238_pp0_iter3_reg;
        A1_read_reg_227 <= A1_int_reg;
        B0_read_reg_233 <= B0_int_reg;
        B1_read_reg_222 <= B1_int_reg;
        Wx_read_reg_217 <= Wx_int_reg;
        Wx_read_reg_217_pp0_iter1_reg <= Wx_read_reg_217;
        Wy_read_reg_212 <= Wy_int_reg;
        Wy_read_reg_212_pp0_iter1_reg <= Wy_read_reg_212;
        add_ln52_1_reg_319 <= add_ln52_1_fu_181_p2;
        mul_ln40_1_reg_309 <= grp_fu_166_p2;
        mul_ln40_1_reg_309_pp0_iter4_reg <= mul_ln40_1_reg_309;
        mul_ln40_2_reg_314 <= grp_fu_175_p2;
        mul_ln40_reg_304 <= grp_fu_157_p2;
        trunc_ln_reg_269 <= {{grp_fu_80_p2[63:32]}};
        val0_reg_254 <= val0_fu_117_p2;
        val1_reg_259 <= val1_fu_123_p2;
        val2_reg_264 <= val2_fu_129_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= {{add_ln52_2_fu_197_p2[39:32]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = {{add_ln52_2_fu_197_p2[39:32]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_157_ce = 1'b1;
    end else begin
        grp_fu_157_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_166_ce = 1'b1;
    end else begin
        grp_fu_166_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_175_ce = 1'b1;
    end else begin
        grp_fu_175_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_80_ce = 1'b1;
    end else begin
        grp_fu_80_ce = 1'b0;
    end
end

assign P4_fu_185_p3 = {{A0_read_reg_238_pp0_iter4_reg}, {32'd0}};

assign add_ln52_1_fu_181_p2 = (mul_ln40_2_reg_314 + mul_ln40_reg_304);

assign add_ln52_2_fu_197_p2 = (add_ln52_1_reg_319 + add_ln52_fu_192_p2);

assign add_ln52_fu_192_p2 = (mul_ln40_1_reg_309_pp0_iter4_reg + P4_fu_185_p3);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign grp_fu_157_p0 = grp_fu_157_p00;

assign grp_fu_157_p00 = trunc_ln_reg_269;

assign grp_fu_166_p0 = grp_fu_166_p00;

assign grp_fu_166_p00 = Wx_read_reg_217_pp0_iter1_reg;

assign grp_fu_175_p0 = grp_fu_175_p00;

assign grp_fu_175_p00 = Wy_read_reg_212_pp0_iter1_reg;

assign grp_fu_80_p0 = grp_fu_80_p00;

assign grp_fu_80_p00 = Wy_int_reg;

assign grp_fu_80_p1 = grp_fu_80_p10;

assign grp_fu_80_p10 = Wx_int_reg;

assign sext_ln43_fu_107_p1 = $signed(sub_ln43_fu_101_p2);

assign sub_ln43_1_fu_111_p2 = ($signed(sext_ln43_fu_107_p1) - $signed(zext_ln43_4_fu_98_p1));

assign sub_ln43_fu_101_p2 = (zext_ln43_fu_86_p1 - zext_ln43_2_fu_92_p1);

assign val0_fu_117_p2 = (sub_ln43_1_fu_111_p2 + zext_ln43_1_fu_89_p1);

assign val1_fu_123_p2 = (zext_ln43_2_fu_92_p1 - zext_ln43_fu_86_p1);

assign val2_fu_129_p2 = (zext_ln43_3_fu_95_p1 - zext_ln43_fu_86_p1);

assign zext_ln43_1_fu_89_p1 = B1_read_reg_222;

assign zext_ln43_2_fu_92_p1 = B0_read_reg_233;

assign zext_ln43_3_fu_95_p1 = A1_read_reg_227;

assign zext_ln43_4_fu_98_p1 = A1_read_reg_227;

assign zext_ln43_fu_86_p1 = A0_read_reg_238;

endmodule //image_accelerator_CoreProcessUpArea
