// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="image_accelerator_image_accelerator,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.268000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=9920,HLS_SYN_LUT=10602,HLS_VERSION=2020_2}" *)

module image_accelerator (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        video_in_TDATA,
        video_in_TKEEP,
        video_in_TSTRB,
        video_in_TUSER,
        video_in_TLAST,
        video_in_TID,
        video_in_TDEST,
        video_out_TDATA,
        video_out_TKEEP,
        video_out_TSTRB,
        video_out_TUSER,
        video_out_TLAST,
        video_out_TID,
        video_out_TDEST,
        video_in_TVALID,
        video_in_TREADY,
        video_out_TVALID,
        video_out_TREADY
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input  [23:0] video_in_TDATA;
input  [2:0] video_in_TKEEP;
input  [2:0] video_in_TSTRB;
input  [0:0] video_in_TUSER;
input  [0:0] video_in_TLAST;
input  [0:0] video_in_TID;
input  [0:0] video_in_TDEST;
output  [7:0] video_out_TDATA;
output  [0:0] video_out_TKEEP;
output  [0:0] video_out_TSTRB;
output  [0:0] video_out_TUSER;
output  [0:0] video_out_TLAST;
output  [0:0] video_out_TID;
output  [0:0] video_out_TDEST;
input   video_in_TVALID;
output   video_in_TREADY;
output   video_out_TVALID;
input   video_out_TREADY;

 reg    ap_rst_n_inv;
wire   [31:0] in_rows;
wire   [31:0] in_cols;
wire   [31:0] out_rows;
wire   [31:0] out_cols;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    Block_split1_proc_U0_ap_start;
wire    Block_split1_proc_U0_start_full_n;
wire    Block_split1_proc_U0_ap_done;
wire    Block_split1_proc_U0_ap_continue;
wire    Block_split1_proc_U0_ap_idle;
wire    Block_split1_proc_U0_ap_ready;
wire    Block_split1_proc_U0_start_out;
wire    Block_split1_proc_U0_start_write;
wire   [31:0] Block_split1_proc_U0_img_in_rows_out_din;
wire    Block_split1_proc_U0_img_in_rows_out_write;
wire   [31:0] Block_split1_proc_U0_img_in_cols_out_din;
wire    Block_split1_proc_U0_img_in_cols_out_write;
wire   [31:0] Block_split1_proc_U0_img_gray_rows_out_din;
wire    Block_split1_proc_U0_img_gray_rows_out_write;
wire   [31:0] Block_split1_proc_U0_img_gray_cols_out_din;
wire    Block_split1_proc_U0_img_gray_cols_out_write;
wire   [31:0] Block_split1_proc_U0_img_out_rows_out_din;
wire    Block_split1_proc_U0_img_out_rows_out_write;
wire   [31:0] Block_split1_proc_U0_img_out_cols_out_din;
wire    Block_split1_proc_U0_img_out_cols_out_write;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_start;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_done;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_continue;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_idle;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_start_out;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_start_write;
wire   [23:0] AXIvideo2xfMat_24_9_1080_1920_1_U0_img_in_432_din;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_img_in_432_write;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_video_in_TREADY;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_read;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_read;
wire   [31:0] AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_out_din;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_out_write;
wire   [31:0] AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_out_din;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_out_write;
wire    rgb2gray_9_0_1080_1920_1_U0_ap_start;
wire    rgb2gray_9_0_1080_1920_1_U0_ap_done;
wire    rgb2gray_9_0_1080_1920_1_U0_ap_continue;
wire    rgb2gray_9_0_1080_1920_1_U0_ap_idle;
wire    rgb2gray_9_0_1080_1920_1_U0_ap_ready;
wire    rgb2gray_9_0_1080_1920_1_U0_img_in_432_read;
wire   [7:0] rgb2gray_9_0_1080_1920_1_U0_img_gray_433_din;
wire    rgb2gray_9_0_1080_1920_1_U0_img_gray_433_write;
wire    rgb2gray_9_0_1080_1920_1_U0_p_src_rows_read;
wire    rgb2gray_9_0_1080_1920_1_U0_p_src_cols_read;
wire    resize_2_0_1080_1920_270_480_1_4_U0_ap_start;
wire    resize_2_0_1080_1920_270_480_1_4_U0_ap_done;
wire    resize_2_0_1080_1920_270_480_1_4_U0_ap_continue;
wire    resize_2_0_1080_1920_270_480_1_4_U0_ap_idle;
wire    resize_2_0_1080_1920_270_480_1_4_U0_ap_ready;
wire    resize_2_0_1080_1920_270_480_1_4_U0_start_out;
wire    resize_2_0_1080_1920_270_480_1_4_U0_start_write;
wire    resize_2_0_1080_1920_270_480_1_4_U0_img_gray_433_read;
wire   [7:0] resize_2_0_1080_1920_270_480_1_4_U0_img_out_434_din;
wire    resize_2_0_1080_1920_270_480_1_4_U0_img_out_434_write;
wire    resize_2_0_1080_1920_270_480_1_4_U0_p_src_rows_read;
wire    resize_2_0_1080_1920_270_480_1_4_U0_p_src_cols_read;
wire    resize_2_0_1080_1920_270_480_1_4_U0_p_dst_rows_read;
wire    resize_2_0_1080_1920_270_480_1_4_U0_p_dst_cols_read;
wire   [31:0] resize_2_0_1080_1920_270_480_1_4_U0_p_dst_rows_out_din;
wire    resize_2_0_1080_1920_270_480_1_4_U0_p_dst_rows_out_write;
wire   [31:0] resize_2_0_1080_1920_270_480_1_4_U0_p_dst_cols_out_din;
wire    resize_2_0_1080_1920_270_480_1_4_U0_p_dst_cols_out_write;
wire    xfMat2AXIvideo_8_0_270_480_1_U0_ap_start;
wire    xfMat2AXIvideo_8_0_270_480_1_U0_ap_done;
wire    xfMat2AXIvideo_8_0_270_480_1_U0_ap_continue;
wire    xfMat2AXIvideo_8_0_270_480_1_U0_ap_idle;
wire    xfMat2AXIvideo_8_0_270_480_1_U0_ap_ready;
wire    xfMat2AXIvideo_8_0_270_480_1_U0_img_out_434_read;
wire    xfMat2AXIvideo_8_0_270_480_1_U0_img_1_read;
wire    xfMat2AXIvideo_8_0_270_480_1_U0_img_2_read;
wire   [7:0] xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TDATA;
wire    xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TVALID;
wire   [0:0] xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TKEEP;
wire   [0:0] xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TSTRB;
wire   [0:0] xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TUSER;
wire   [0:0] xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TLAST;
wire   [0:0] xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TID;
wire   [0:0] xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TDEST;
wire    ap_sync_continue;
wire    img_in_rows_c_full_n;
wire   [31:0] img_in_rows_c_dout;
wire    img_in_rows_c_empty_n;
wire    img_in_cols_c_full_n;
wire   [31:0] img_in_cols_c_dout;
wire    img_in_cols_c_empty_n;
wire    img_gray_rows_c_full_n;
wire   [31:0] img_gray_rows_c_dout;
wire    img_gray_rows_c_empty_n;
wire    img_gray_cols_c_full_n;
wire   [31:0] img_gray_cols_c_dout;
wire    img_gray_cols_c_empty_n;
wire    img_out_rows_c_full_n;
wire   [31:0] img_out_rows_c_dout;
wire    img_out_rows_c_empty_n;
wire    img_out_cols_c_full_n;
wire   [31:0] img_out_cols_c_dout;
wire    img_out_cols_c_empty_n;
wire    img_in_data_full_n;
wire   [23:0] img_in_data_dout;
wire    img_in_data_empty_n;
wire    img_in_rows_c11_full_n;
wire   [31:0] img_in_rows_c11_dout;
wire    img_in_rows_c11_empty_n;
wire    img_in_cols_c12_full_n;
wire   [31:0] img_in_cols_c12_dout;
wire    img_in_cols_c12_empty_n;
wire    img_gray_data_full_n;
wire   [7:0] img_gray_data_dout;
wire    img_gray_data_empty_n;
wire    img_out_data_full_n;
wire   [7:0] img_out_data_dout;
wire    img_out_data_empty_n;
wire    img_out_rows_c13_full_n;
wire   [31:0] img_out_rows_c13_dout;
wire    img_out_rows_c13_empty_n;
wire    img_out_cols_c14_full_n;
wire   [31:0] img_out_cols_c14_dout;
wire    img_out_cols_c14_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_din;
wire    start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_full_n;
wire   [0:0] start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_dout;
wire    start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_empty_n;
wire   [0:0] start_for_resize_2_0_1080_1920_270_480_1_4_U0_din;
wire    start_for_resize_2_0_1080_1920_270_480_1_4_U0_full_n;
wire   [0:0] start_for_resize_2_0_1080_1920_270_480_1_4_U0_dout;
wire    start_for_resize_2_0_1080_1920_270_480_1_4_U0_empty_n;
wire   [0:0] start_for_rgb2gray_9_0_1080_1920_1_U0_din;
wire    start_for_rgb2gray_9_0_1080_1920_1_U0_full_n;
wire   [0:0] start_for_rgb2gray_9_0_1080_1920_1_U0_dout;
wire    start_for_rgb2gray_9_0_1080_1920_1_U0_empty_n;
wire    rgb2gray_9_0_1080_1920_1_U0_start_full_n;
wire    rgb2gray_9_0_1080_1920_1_U0_start_write;
wire   [0:0] start_for_xfMat2AXIvideo_8_0_270_480_1_U0_din;
wire    start_for_xfMat2AXIvideo_8_0_270_480_1_U0_full_n;
wire   [0:0] start_for_xfMat2AXIvideo_8_0_270_480_1_U0_dout;
wire    start_for_xfMat2AXIvideo_8_0_270_480_1_U0_empty_n;
wire    xfMat2AXIvideo_8_0_270_480_1_U0_start_full_n;
wire    xfMat2AXIvideo_8_0_270_480_1_U0_start_write;

image_accelerator_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .in_rows(in_rows),
    .in_cols(in_cols),
    .out_rows(out_rows),
    .out_cols(out_cols),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

image_accelerator_Block_split1_proc Block_split1_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_split1_proc_U0_ap_start),
    .start_full_n(Block_split1_proc_U0_start_full_n),
    .ap_done(Block_split1_proc_U0_ap_done),
    .ap_continue(Block_split1_proc_U0_ap_continue),
    .ap_idle(Block_split1_proc_U0_ap_idle),
    .ap_ready(Block_split1_proc_U0_ap_ready),
    .start_out(Block_split1_proc_U0_start_out),
    .start_write(Block_split1_proc_U0_start_write),
    .in_rows(in_rows),
    .in_cols(in_cols),
    .out_rows(out_rows),
    .out_cols(out_cols),
    .img_in_rows_out_din(Block_split1_proc_U0_img_in_rows_out_din),
    .img_in_rows_out_full_n(img_in_rows_c_full_n),
    .img_in_rows_out_write(Block_split1_proc_U0_img_in_rows_out_write),
    .img_in_cols_out_din(Block_split1_proc_U0_img_in_cols_out_din),
    .img_in_cols_out_full_n(img_in_cols_c_full_n),
    .img_in_cols_out_write(Block_split1_proc_U0_img_in_cols_out_write),
    .img_gray_rows_out_din(Block_split1_proc_U0_img_gray_rows_out_din),
    .img_gray_rows_out_full_n(img_gray_rows_c_full_n),
    .img_gray_rows_out_write(Block_split1_proc_U0_img_gray_rows_out_write),
    .img_gray_cols_out_din(Block_split1_proc_U0_img_gray_cols_out_din),
    .img_gray_cols_out_full_n(img_gray_cols_c_full_n),
    .img_gray_cols_out_write(Block_split1_proc_U0_img_gray_cols_out_write),
    .img_out_rows_out_din(Block_split1_proc_U0_img_out_rows_out_din),
    .img_out_rows_out_full_n(img_out_rows_c_full_n),
    .img_out_rows_out_write(Block_split1_proc_U0_img_out_rows_out_write),
    .img_out_cols_out_din(Block_split1_proc_U0_img_out_cols_out_din),
    .img_out_cols_out_full_n(img_out_cols_c_full_n),
    .img_out_cols_out_write(Block_split1_proc_U0_img_out_cols_out_write)
);

image_accelerator_AXIvideo2xfMat_24_9_1080_1920_1_s AXIvideo2xfMat_24_9_1080_1920_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_start),
    .start_full_n(start_for_rgb2gray_9_0_1080_1920_1_U0_full_n),
    .ap_done(AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_done),
    .ap_continue(AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_continue),
    .ap_idle(AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_idle),
    .ap_ready(AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready),
    .start_out(AXIvideo2xfMat_24_9_1080_1920_1_U0_start_out),
    .start_write(AXIvideo2xfMat_24_9_1080_1920_1_U0_start_write),
    .img_in_432_din(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_in_432_din),
    .img_in_432_full_n(img_in_data_full_n),
    .img_in_432_write(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_in_432_write),
    .video_in_TDATA(video_in_TDATA),
    .video_in_TVALID(video_in_TVALID),
    .video_in_TREADY(AXIvideo2xfMat_24_9_1080_1920_1_U0_video_in_TREADY),
    .video_in_TKEEP(video_in_TKEEP),
    .video_in_TSTRB(video_in_TSTRB),
    .video_in_TUSER(video_in_TUSER),
    .video_in_TLAST(video_in_TLAST),
    .video_in_TID(video_in_TID),
    .video_in_TDEST(video_in_TDEST),
    .img_1_dout(img_in_rows_c_dout),
    .img_1_empty_n(img_in_rows_c_empty_n),
    .img_1_read(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_read),
    .img_2_dout(img_in_cols_c_dout),
    .img_2_empty_n(img_in_cols_c_empty_n),
    .img_2_read(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_read),
    .img_1_out_din(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_out_din),
    .img_1_out_full_n(img_in_rows_c11_full_n),
    .img_1_out_write(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_out_write),
    .img_2_out_din(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_out_din),
    .img_2_out_full_n(img_in_cols_c12_full_n),
    .img_2_out_write(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_out_write)
);

image_accelerator_rgb2gray_9_0_1080_1920_1_s rgb2gray_9_0_1080_1920_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(rgb2gray_9_0_1080_1920_1_U0_ap_start),
    .ap_done(rgb2gray_9_0_1080_1920_1_U0_ap_done),
    .ap_continue(rgb2gray_9_0_1080_1920_1_U0_ap_continue),
    .ap_idle(rgb2gray_9_0_1080_1920_1_U0_ap_idle),
    .ap_ready(rgb2gray_9_0_1080_1920_1_U0_ap_ready),
    .img_in_432_dout(img_in_data_dout),
    .img_in_432_empty_n(img_in_data_empty_n),
    .img_in_432_read(rgb2gray_9_0_1080_1920_1_U0_img_in_432_read),
    .img_gray_433_din(rgb2gray_9_0_1080_1920_1_U0_img_gray_433_din),
    .img_gray_433_full_n(img_gray_data_full_n),
    .img_gray_433_write(rgb2gray_9_0_1080_1920_1_U0_img_gray_433_write),
    .p_src_rows_dout(img_in_rows_c11_dout),
    .p_src_rows_empty_n(img_in_rows_c11_empty_n),
    .p_src_rows_read(rgb2gray_9_0_1080_1920_1_U0_p_src_rows_read),
    .p_src_cols_dout(img_in_cols_c12_dout),
    .p_src_cols_empty_n(img_in_cols_c12_empty_n),
    .p_src_cols_read(rgb2gray_9_0_1080_1920_1_U0_p_src_cols_read)
);

image_accelerator_resize_2_0_1080_1920_270_480_1_4_s resize_2_0_1080_1920_270_480_1_4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(resize_2_0_1080_1920_270_480_1_4_U0_ap_start),
    .start_full_n(start_for_xfMat2AXIvideo_8_0_270_480_1_U0_full_n),
    .ap_done(resize_2_0_1080_1920_270_480_1_4_U0_ap_done),
    .ap_continue(resize_2_0_1080_1920_270_480_1_4_U0_ap_continue),
    .ap_idle(resize_2_0_1080_1920_270_480_1_4_U0_ap_idle),
    .ap_ready(resize_2_0_1080_1920_270_480_1_4_U0_ap_ready),
    .start_out(resize_2_0_1080_1920_270_480_1_4_U0_start_out),
    .start_write(resize_2_0_1080_1920_270_480_1_4_U0_start_write),
    .img_gray_433_dout(img_gray_data_dout),
    .img_gray_433_empty_n(img_gray_data_empty_n),
    .img_gray_433_read(resize_2_0_1080_1920_270_480_1_4_U0_img_gray_433_read),
    .img_out_434_din(resize_2_0_1080_1920_270_480_1_4_U0_img_out_434_din),
    .img_out_434_full_n(img_out_data_full_n),
    .img_out_434_write(resize_2_0_1080_1920_270_480_1_4_U0_img_out_434_write),
    .p_src_rows_dout(img_gray_rows_c_dout),
    .p_src_rows_empty_n(img_gray_rows_c_empty_n),
    .p_src_rows_read(resize_2_0_1080_1920_270_480_1_4_U0_p_src_rows_read),
    .p_src_cols_dout(img_gray_cols_c_dout),
    .p_src_cols_empty_n(img_gray_cols_c_empty_n),
    .p_src_cols_read(resize_2_0_1080_1920_270_480_1_4_U0_p_src_cols_read),
    .p_dst_rows_dout(img_out_rows_c_dout),
    .p_dst_rows_empty_n(img_out_rows_c_empty_n),
    .p_dst_rows_read(resize_2_0_1080_1920_270_480_1_4_U0_p_dst_rows_read),
    .p_dst_cols_dout(img_out_cols_c_dout),
    .p_dst_cols_empty_n(img_out_cols_c_empty_n),
    .p_dst_cols_read(resize_2_0_1080_1920_270_480_1_4_U0_p_dst_cols_read),
    .p_dst_rows_out_din(resize_2_0_1080_1920_270_480_1_4_U0_p_dst_rows_out_din),
    .p_dst_rows_out_full_n(img_out_rows_c13_full_n),
    .p_dst_rows_out_write(resize_2_0_1080_1920_270_480_1_4_U0_p_dst_rows_out_write),
    .p_dst_cols_out_din(resize_2_0_1080_1920_270_480_1_4_U0_p_dst_cols_out_din),
    .p_dst_cols_out_full_n(img_out_cols_c14_full_n),
    .p_dst_cols_out_write(resize_2_0_1080_1920_270_480_1_4_U0_p_dst_cols_out_write)
);

image_accelerator_xfMat2AXIvideo_8_0_270_480_1_s xfMat2AXIvideo_8_0_270_480_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(xfMat2AXIvideo_8_0_270_480_1_U0_ap_start),
    .ap_done(xfMat2AXIvideo_8_0_270_480_1_U0_ap_done),
    .ap_continue(xfMat2AXIvideo_8_0_270_480_1_U0_ap_continue),
    .ap_idle(xfMat2AXIvideo_8_0_270_480_1_U0_ap_idle),
    .ap_ready(xfMat2AXIvideo_8_0_270_480_1_U0_ap_ready),
    .img_out_434_dout(img_out_data_dout),
    .img_out_434_empty_n(img_out_data_empty_n),
    .img_out_434_read(xfMat2AXIvideo_8_0_270_480_1_U0_img_out_434_read),
    .img_1_dout(img_out_rows_c13_dout),
    .img_1_empty_n(img_out_rows_c13_empty_n),
    .img_1_read(xfMat2AXIvideo_8_0_270_480_1_U0_img_1_read),
    .img_2_dout(img_out_cols_c14_dout),
    .img_2_empty_n(img_out_cols_c14_empty_n),
    .img_2_read(xfMat2AXIvideo_8_0_270_480_1_U0_img_2_read),
    .video_out_TDATA(xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TDATA),
    .video_out_TVALID(xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TVALID),
    .video_out_TREADY(video_out_TREADY),
    .video_out_TKEEP(xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TKEEP),
    .video_out_TSTRB(xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TSTRB),
    .video_out_TUSER(xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TUSER),
    .video_out_TLAST(xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TLAST),
    .video_out_TID(xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TID),
    .video_out_TDEST(xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TDEST)
);

image_accelerator_fifo_w32_d2_S img_in_rows_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_split1_proc_U0_img_in_rows_out_din),
    .if_full_n(img_in_rows_c_full_n),
    .if_write(Block_split1_proc_U0_img_in_rows_out_write),
    .if_dout(img_in_rows_c_dout),
    .if_empty_n(img_in_rows_c_empty_n),
    .if_read(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_read)
);

image_accelerator_fifo_w32_d2_S img_in_cols_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_split1_proc_U0_img_in_cols_out_din),
    .if_full_n(img_in_cols_c_full_n),
    .if_write(Block_split1_proc_U0_img_in_cols_out_write),
    .if_dout(img_in_cols_c_dout),
    .if_empty_n(img_in_cols_c_empty_n),
    .if_read(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_read)
);

image_accelerator_fifo_w32_d4_S img_gray_rows_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_split1_proc_U0_img_gray_rows_out_din),
    .if_full_n(img_gray_rows_c_full_n),
    .if_write(Block_split1_proc_U0_img_gray_rows_out_write),
    .if_dout(img_gray_rows_c_dout),
    .if_empty_n(img_gray_rows_c_empty_n),
    .if_read(resize_2_0_1080_1920_270_480_1_4_U0_p_src_rows_read)
);

image_accelerator_fifo_w32_d4_S img_gray_cols_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_split1_proc_U0_img_gray_cols_out_din),
    .if_full_n(img_gray_cols_c_full_n),
    .if_write(Block_split1_proc_U0_img_gray_cols_out_write),
    .if_dout(img_gray_cols_c_dout),
    .if_empty_n(img_gray_cols_c_empty_n),
    .if_read(resize_2_0_1080_1920_270_480_1_4_U0_p_src_cols_read)
);

image_accelerator_fifo_w32_d4_S img_out_rows_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_split1_proc_U0_img_out_rows_out_din),
    .if_full_n(img_out_rows_c_full_n),
    .if_write(Block_split1_proc_U0_img_out_rows_out_write),
    .if_dout(img_out_rows_c_dout),
    .if_empty_n(img_out_rows_c_empty_n),
    .if_read(resize_2_0_1080_1920_270_480_1_4_U0_p_dst_rows_read)
);

image_accelerator_fifo_w32_d4_S img_out_cols_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_split1_proc_U0_img_out_cols_out_din),
    .if_full_n(img_out_cols_c_full_n),
    .if_write(Block_split1_proc_U0_img_out_cols_out_write),
    .if_dout(img_out_cols_c_dout),
    .if_empty_n(img_out_cols_c_empty_n),
    .if_read(resize_2_0_1080_1920_270_480_1_4_U0_p_dst_cols_read)
);

image_accelerator_fifo_w24_d2_S img_in_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_in_432_din),
    .if_full_n(img_in_data_full_n),
    .if_write(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_in_432_write),
    .if_dout(img_in_data_dout),
    .if_empty_n(img_in_data_empty_n),
    .if_read(rgb2gray_9_0_1080_1920_1_U0_img_in_432_read)
);

image_accelerator_fifo_w32_d2_S img_in_rows_c11_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_out_din),
    .if_full_n(img_in_rows_c11_full_n),
    .if_write(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_out_write),
    .if_dout(img_in_rows_c11_dout),
    .if_empty_n(img_in_rows_c11_empty_n),
    .if_read(rgb2gray_9_0_1080_1920_1_U0_p_src_rows_read)
);

image_accelerator_fifo_w32_d2_S img_in_cols_c12_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_out_din),
    .if_full_n(img_in_cols_c12_full_n),
    .if_write(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_out_write),
    .if_dout(img_in_cols_c12_dout),
    .if_empty_n(img_in_cols_c12_empty_n),
    .if_read(rgb2gray_9_0_1080_1920_1_U0_p_src_cols_read)
);

image_accelerator_fifo_w8_d2_S img_gray_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(rgb2gray_9_0_1080_1920_1_U0_img_gray_433_din),
    .if_full_n(img_gray_data_full_n),
    .if_write(rgb2gray_9_0_1080_1920_1_U0_img_gray_433_write),
    .if_dout(img_gray_data_dout),
    .if_empty_n(img_gray_data_empty_n),
    .if_read(resize_2_0_1080_1920_270_480_1_4_U0_img_gray_433_read)
);

image_accelerator_fifo_w8_d2_S img_out_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(resize_2_0_1080_1920_270_480_1_4_U0_img_out_434_din),
    .if_full_n(img_out_data_full_n),
    .if_write(resize_2_0_1080_1920_270_480_1_4_U0_img_out_434_write),
    .if_dout(img_out_data_dout),
    .if_empty_n(img_out_data_empty_n),
    .if_read(xfMat2AXIvideo_8_0_270_480_1_U0_img_out_434_read)
);

image_accelerator_fifo_w32_d2_S img_out_rows_c13_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(resize_2_0_1080_1920_270_480_1_4_U0_p_dst_rows_out_din),
    .if_full_n(img_out_rows_c13_full_n),
    .if_write(resize_2_0_1080_1920_270_480_1_4_U0_p_dst_rows_out_write),
    .if_dout(img_out_rows_c13_dout),
    .if_empty_n(img_out_rows_c13_empty_n),
    .if_read(xfMat2AXIvideo_8_0_270_480_1_U0_img_1_read)
);

image_accelerator_fifo_w32_d2_S img_out_cols_c14_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(resize_2_0_1080_1920_270_480_1_4_U0_p_dst_cols_out_din),
    .if_full_n(img_out_cols_c14_full_n),
    .if_write(resize_2_0_1080_1920_270_480_1_4_U0_p_dst_cols_out_write),
    .if_dout(img_out_cols_c14_dout),
    .if_empty_n(img_out_cols_c14_empty_n),
    .if_read(xfMat2AXIvideo_8_0_270_480_1_U0_img_2_read)
);

image_accelerator_start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0 start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_din),
    .if_full_n(start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_full_n),
    .if_write(Block_split1_proc_U0_start_write),
    .if_dout(start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_dout),
    .if_empty_n(start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_empty_n),
    .if_read(AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready)
);

image_accelerator_start_for_resize_2_0_1080_1920_270_480_1_4_U0 start_for_resize_2_0_1080_1920_270_480_1_4_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_resize_2_0_1080_1920_270_480_1_4_U0_din),
    .if_full_n(start_for_resize_2_0_1080_1920_270_480_1_4_U0_full_n),
    .if_write(Block_split1_proc_U0_start_write),
    .if_dout(start_for_resize_2_0_1080_1920_270_480_1_4_U0_dout),
    .if_empty_n(start_for_resize_2_0_1080_1920_270_480_1_4_U0_empty_n),
    .if_read(resize_2_0_1080_1920_270_480_1_4_U0_ap_ready)
);

image_accelerator_start_for_rgb2gray_9_0_1080_1920_1_U0 start_for_rgb2gray_9_0_1080_1920_1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_rgb2gray_9_0_1080_1920_1_U0_din),
    .if_full_n(start_for_rgb2gray_9_0_1080_1920_1_U0_full_n),
    .if_write(AXIvideo2xfMat_24_9_1080_1920_1_U0_start_write),
    .if_dout(start_for_rgb2gray_9_0_1080_1920_1_U0_dout),
    .if_empty_n(start_for_rgb2gray_9_0_1080_1920_1_U0_empty_n),
    .if_read(rgb2gray_9_0_1080_1920_1_U0_ap_ready)
);

image_accelerator_start_for_xfMat2AXIvideo_8_0_270_480_1_U0 start_for_xfMat2AXIvideo_8_0_270_480_1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xfMat2AXIvideo_8_0_270_480_1_U0_din),
    .if_full_n(start_for_xfMat2AXIvideo_8_0_270_480_1_U0_full_n),
    .if_write(resize_2_0_1080_1920_270_480_1_4_U0_start_write),
    .if_dout(start_for_xfMat2AXIvideo_8_0_270_480_1_U0_dout),
    .if_empty_n(start_for_xfMat2AXIvideo_8_0_270_480_1_U0_empty_n),
    .if_read(xfMat2AXIvideo_8_0_270_480_1_U0_ap_ready)
);

assign AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_continue = 1'b1;

assign AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_start = start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_empty_n;

assign Block_split1_proc_U0_ap_continue = 1'b1;

assign Block_split1_proc_U0_ap_start = ap_start;

assign Block_split1_proc_U0_start_full_n = (start_for_resize_2_0_1080_1920_270_480_1_4_U0_full_n & start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_full_n);

assign ap_done = xfMat2AXIvideo_8_0_270_480_1_U0_ap_done;

assign ap_idle = (xfMat2AXIvideo_8_0_270_480_1_U0_ap_idle & rgb2gray_9_0_1080_1920_1_U0_ap_idle & resize_2_0_1080_1920_270_480_1_4_U0_ap_idle & Block_split1_proc_U0_ap_idle & AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_idle);

assign ap_ready = Block_split1_proc_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b1;

assign ap_sync_done = xfMat2AXIvideo_8_0_270_480_1_U0_ap_done;

assign ap_sync_ready = Block_split1_proc_U0_ap_ready;

assign resize_2_0_1080_1920_270_480_1_4_U0_ap_continue = 1'b1;

assign resize_2_0_1080_1920_270_480_1_4_U0_ap_start = start_for_resize_2_0_1080_1920_270_480_1_4_U0_empty_n;

assign rgb2gray_9_0_1080_1920_1_U0_ap_continue = 1'b1;

assign rgb2gray_9_0_1080_1920_1_U0_ap_start = start_for_rgb2gray_9_0_1080_1920_1_U0_empty_n;

assign rgb2gray_9_0_1080_1920_1_U0_start_full_n = 1'b1;

assign rgb2gray_9_0_1080_1920_1_U0_start_write = 1'b0;

assign start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_din = 1'b1;

assign start_for_resize_2_0_1080_1920_270_480_1_4_U0_din = 1'b1;

assign start_for_rgb2gray_9_0_1080_1920_1_U0_din = 1'b1;

assign start_for_xfMat2AXIvideo_8_0_270_480_1_U0_din = 1'b1;

assign video_in_TREADY = AXIvideo2xfMat_24_9_1080_1920_1_U0_video_in_TREADY;

assign video_out_TDATA = xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TDATA;

assign video_out_TDEST = xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TDEST;

assign video_out_TID = xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TID;

assign video_out_TKEEP = xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TKEEP;

assign video_out_TLAST = xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TLAST;

assign video_out_TSTRB = xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TSTRB;

assign video_out_TUSER = xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TUSER;

assign video_out_TVALID = xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TVALID;

assign xfMat2AXIvideo_8_0_270_480_1_U0_ap_continue = 1'b1;

assign xfMat2AXIvideo_8_0_270_480_1_U0_ap_start = start_for_xfMat2AXIvideo_8_0_270_480_1_U0_empty_n;

assign xfMat2AXIvideo_8_0_270_480_1_U0_start_full_n = 1'b1;

assign xfMat2AXIvideo_8_0_270_480_1_U0_start_write = 1'b0;


// synthesis translate_off
`include "image_accelerator_hls_deadlock_detector.vh"
// synthesis translate_on

endmodule //image_accelerator

