# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/imgProc/attempt4/hdmi_input/hdmi_input.srcs/sources_1/bd/hdmi_in_bd/ip/hdmi_in_bd_xbar_1/hdmi_in_bd_xbar_1.xci
# IP: The module: 'hdmi_in_bd_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/imgProc/attempt4/hdmi_input/hdmi_input.gen/sources_1/bd/hdmi_in_bd/ip/hdmi_in_bd_xbar_1/hdmi_in_bd_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_in_bd_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/imgProc/attempt4/hdmi_input/hdmi_input.srcs/sources_1/bd/hdmi_in_bd/ip/hdmi_in_bd_xbar_1/hdmi_in_bd_xbar_1.xci
# IP: The module: 'hdmi_in_bd_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/imgProc/attempt4/hdmi_input/hdmi_input.gen/sources_1/bd/hdmi_in_bd/ip/hdmi_in_bd_xbar_1/hdmi_in_bd_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_in_bd_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
