-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity image_accelerator is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    video_in_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    video_in_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    video_in_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    video_in_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    video_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    video_in_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    video_in_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    video_out_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    video_out_TKEEP : OUT STD_LOGIC_VECTOR (0 downto 0);
    video_out_TSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    video_out_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    video_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    video_out_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    video_out_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    video_in_TVALID : IN STD_LOGIC;
    video_in_TREADY : OUT STD_LOGIC;
    video_out_TVALID : OUT STD_LOGIC;
    video_out_TREADY : IN STD_LOGIC );
end;


architecture behav of image_accelerator is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "image_accelerator_image_accelerator,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.268000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=9920,HLS_SYN_LUT=10602,HLS_VERSION=2020_2}";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_S_AXI_WSTRB_WIDTH : INTEGER range 63 downto 0 := 4;
    constant C_S_AXI_ADDR_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal in_rows : STD_LOGIC_VECTOR (31 downto 0);
    signal in_cols : STD_LOGIC_VECTOR (31 downto 0);
    signal out_rows : STD_LOGIC_VECTOR (31 downto 0);
    signal out_cols : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal Block_split1_proc_U0_ap_start : STD_LOGIC;
    signal Block_split1_proc_U0_start_full_n : STD_LOGIC;
    signal Block_split1_proc_U0_ap_done : STD_LOGIC;
    signal Block_split1_proc_U0_ap_continue : STD_LOGIC;
    signal Block_split1_proc_U0_ap_idle : STD_LOGIC;
    signal Block_split1_proc_U0_ap_ready : STD_LOGIC;
    signal Block_split1_proc_U0_start_out : STD_LOGIC;
    signal Block_split1_proc_U0_start_write : STD_LOGIC;
    signal Block_split1_proc_U0_img_in_rows_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_split1_proc_U0_img_in_rows_out_write : STD_LOGIC;
    signal Block_split1_proc_U0_img_in_cols_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_split1_proc_U0_img_in_cols_out_write : STD_LOGIC;
    signal Block_split1_proc_U0_img_gray_rows_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_split1_proc_U0_img_gray_rows_out_write : STD_LOGIC;
    signal Block_split1_proc_U0_img_gray_cols_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_split1_proc_U0_img_gray_cols_out_write : STD_LOGIC;
    signal Block_split1_proc_U0_img_out_rows_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_split1_proc_U0_img_out_rows_out_write : STD_LOGIC;
    signal Block_split1_proc_U0_img_out_cols_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal Block_split1_proc_U0_img_out_cols_out_write : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_start : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_done : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_continue : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_idle : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_start_out : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_start_write : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_img_in_432_din : STD_LOGIC_VECTOR (23 downto 0);
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_img_in_432_write : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_video_in_TREADY : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_read : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_read : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_out_write : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_out_write : STD_LOGIC;
    signal rgb2gray_9_0_1080_1920_1_U0_ap_start : STD_LOGIC;
    signal rgb2gray_9_0_1080_1920_1_U0_ap_done : STD_LOGIC;
    signal rgb2gray_9_0_1080_1920_1_U0_ap_continue : STD_LOGIC;
    signal rgb2gray_9_0_1080_1920_1_U0_ap_idle : STD_LOGIC;
    signal rgb2gray_9_0_1080_1920_1_U0_ap_ready : STD_LOGIC;
    signal rgb2gray_9_0_1080_1920_1_U0_img_in_432_read : STD_LOGIC;
    signal rgb2gray_9_0_1080_1920_1_U0_img_gray_433_din : STD_LOGIC_VECTOR (7 downto 0);
    signal rgb2gray_9_0_1080_1920_1_U0_img_gray_433_write : STD_LOGIC;
    signal rgb2gray_9_0_1080_1920_1_U0_p_src_rows_read : STD_LOGIC;
    signal rgb2gray_9_0_1080_1920_1_U0_p_src_cols_read : STD_LOGIC;
    signal resize_2_0_1080_1920_270_480_1_4_U0_ap_start : STD_LOGIC;
    signal resize_2_0_1080_1920_270_480_1_4_U0_ap_done : STD_LOGIC;
    signal resize_2_0_1080_1920_270_480_1_4_U0_ap_continue : STD_LOGIC;
    signal resize_2_0_1080_1920_270_480_1_4_U0_ap_idle : STD_LOGIC;
    signal resize_2_0_1080_1920_270_480_1_4_U0_ap_ready : STD_LOGIC;
    signal resize_2_0_1080_1920_270_480_1_4_U0_start_out : STD_LOGIC;
    signal resize_2_0_1080_1920_270_480_1_4_U0_start_write : STD_LOGIC;
    signal resize_2_0_1080_1920_270_480_1_4_U0_img_gray_433_read : STD_LOGIC;
    signal resize_2_0_1080_1920_270_480_1_4_U0_img_out_434_din : STD_LOGIC_VECTOR (7 downto 0);
    signal resize_2_0_1080_1920_270_480_1_4_U0_img_out_434_write : STD_LOGIC;
    signal resize_2_0_1080_1920_270_480_1_4_U0_p_src_rows_read : STD_LOGIC;
    signal resize_2_0_1080_1920_270_480_1_4_U0_p_src_cols_read : STD_LOGIC;
    signal resize_2_0_1080_1920_270_480_1_4_U0_p_dst_rows_read : STD_LOGIC;
    signal resize_2_0_1080_1920_270_480_1_4_U0_p_dst_cols_read : STD_LOGIC;
    signal resize_2_0_1080_1920_270_480_1_4_U0_p_dst_rows_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal resize_2_0_1080_1920_270_480_1_4_U0_p_dst_rows_out_write : STD_LOGIC;
    signal resize_2_0_1080_1920_270_480_1_4_U0_p_dst_cols_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal resize_2_0_1080_1920_270_480_1_4_U0_p_dst_cols_out_write : STD_LOGIC;
    signal xfMat2AXIvideo_8_0_270_480_1_U0_ap_start : STD_LOGIC;
    signal xfMat2AXIvideo_8_0_270_480_1_U0_ap_done : STD_LOGIC;
    signal xfMat2AXIvideo_8_0_270_480_1_U0_ap_continue : STD_LOGIC;
    signal xfMat2AXIvideo_8_0_270_480_1_U0_ap_idle : STD_LOGIC;
    signal xfMat2AXIvideo_8_0_270_480_1_U0_ap_ready : STD_LOGIC;
    signal xfMat2AXIvideo_8_0_270_480_1_U0_img_out_434_read : STD_LOGIC;
    signal xfMat2AXIvideo_8_0_270_480_1_U0_img_1_read : STD_LOGIC;
    signal xfMat2AXIvideo_8_0_270_480_1_U0_img_2_read : STD_LOGIC;
    signal xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TVALID : STD_LOGIC;
    signal xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TKEEP : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sync_continue : STD_LOGIC;
    signal img_in_rows_c_full_n : STD_LOGIC;
    signal img_in_rows_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_in_rows_c_empty_n : STD_LOGIC;
    signal img_in_cols_c_full_n : STD_LOGIC;
    signal img_in_cols_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_in_cols_c_empty_n : STD_LOGIC;
    signal img_gray_rows_c_full_n : STD_LOGIC;
    signal img_gray_rows_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_gray_rows_c_empty_n : STD_LOGIC;
    signal img_gray_cols_c_full_n : STD_LOGIC;
    signal img_gray_cols_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_gray_cols_c_empty_n : STD_LOGIC;
    signal img_out_rows_c_full_n : STD_LOGIC;
    signal img_out_rows_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_out_rows_c_empty_n : STD_LOGIC;
    signal img_out_cols_c_full_n : STD_LOGIC;
    signal img_out_cols_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_out_cols_c_empty_n : STD_LOGIC;
    signal img_in_data_full_n : STD_LOGIC;
    signal img_in_data_dout : STD_LOGIC_VECTOR (23 downto 0);
    signal img_in_data_empty_n : STD_LOGIC;
    signal img_in_rows_c11_full_n : STD_LOGIC;
    signal img_in_rows_c11_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_in_rows_c11_empty_n : STD_LOGIC;
    signal img_in_cols_c12_full_n : STD_LOGIC;
    signal img_in_cols_c12_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_in_cols_c12_empty_n : STD_LOGIC;
    signal img_gray_data_full_n : STD_LOGIC;
    signal img_gray_data_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_gray_data_empty_n : STD_LOGIC;
    signal img_out_data_full_n : STD_LOGIC;
    signal img_out_data_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_out_data_empty_n : STD_LOGIC;
    signal img_out_rows_c13_full_n : STD_LOGIC;
    signal img_out_rows_c13_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_out_rows_c13_empty_n : STD_LOGIC;
    signal img_out_cols_c14_full_n : STD_LOGIC;
    signal img_out_cols_c14_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_out_cols_c14_empty_n : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_full_n : STD_LOGIC;
    signal start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_empty_n : STD_LOGIC;
    signal start_for_resize_2_0_1080_1920_270_480_1_4_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_resize_2_0_1080_1920_270_480_1_4_U0_full_n : STD_LOGIC;
    signal start_for_resize_2_0_1080_1920_270_480_1_4_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_resize_2_0_1080_1920_270_480_1_4_U0_empty_n : STD_LOGIC;
    signal start_for_rgb2gray_9_0_1080_1920_1_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_rgb2gray_9_0_1080_1920_1_U0_full_n : STD_LOGIC;
    signal start_for_rgb2gray_9_0_1080_1920_1_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_rgb2gray_9_0_1080_1920_1_U0_empty_n : STD_LOGIC;
    signal rgb2gray_9_0_1080_1920_1_U0_start_full_n : STD_LOGIC;
    signal rgb2gray_9_0_1080_1920_1_U0_start_write : STD_LOGIC;
    signal start_for_xfMat2AXIvideo_8_0_270_480_1_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xfMat2AXIvideo_8_0_270_480_1_U0_full_n : STD_LOGIC;
    signal start_for_xfMat2AXIvideo_8_0_270_480_1_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xfMat2AXIvideo_8_0_270_480_1_U0_empty_n : STD_LOGIC;
    signal xfMat2AXIvideo_8_0_270_480_1_U0_start_full_n : STD_LOGIC;
    signal xfMat2AXIvideo_8_0_270_480_1_U0_start_write : STD_LOGIC;

    component image_accelerator_Block_split1_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        in_rows : IN STD_LOGIC_VECTOR (31 downto 0);
        in_cols : IN STD_LOGIC_VECTOR (31 downto 0);
        out_rows : IN STD_LOGIC_VECTOR (31 downto 0);
        out_cols : IN STD_LOGIC_VECTOR (31 downto 0);
        img_in_rows_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_in_rows_out_full_n : IN STD_LOGIC;
        img_in_rows_out_write : OUT STD_LOGIC;
        img_in_cols_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_in_cols_out_full_n : IN STD_LOGIC;
        img_in_cols_out_write : OUT STD_LOGIC;
        img_gray_rows_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_gray_rows_out_full_n : IN STD_LOGIC;
        img_gray_rows_out_write : OUT STD_LOGIC;
        img_gray_cols_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_gray_cols_out_full_n : IN STD_LOGIC;
        img_gray_cols_out_write : OUT STD_LOGIC;
        img_out_rows_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_out_rows_out_full_n : IN STD_LOGIC;
        img_out_rows_out_write : OUT STD_LOGIC;
        img_out_cols_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_out_cols_out_full_n : IN STD_LOGIC;
        img_out_cols_out_write : OUT STD_LOGIC );
    end component;


    component image_accelerator_AXIvideo2xfMat_24_9_1080_1920_1_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        img_in_432_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        img_in_432_full_n : IN STD_LOGIC;
        img_in_432_write : OUT STD_LOGIC;
        video_in_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
        video_in_TVALID : IN STD_LOGIC;
        video_in_TREADY : OUT STD_LOGIC;
        video_in_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
        video_in_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
        video_in_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        video_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        video_in_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        video_in_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        img_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        img_1_empty_n : IN STD_LOGIC;
        img_1_read : OUT STD_LOGIC;
        img_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        img_2_empty_n : IN STD_LOGIC;
        img_2_read : OUT STD_LOGIC;
        img_1_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_1_out_full_n : IN STD_LOGIC;
        img_1_out_write : OUT STD_LOGIC;
        img_2_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_2_out_full_n : IN STD_LOGIC;
        img_2_out_write : OUT STD_LOGIC );
    end component;


    component image_accelerator_rgb2gray_9_0_1080_1920_1_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_in_432_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        img_in_432_empty_n : IN STD_LOGIC;
        img_in_432_read : OUT STD_LOGIC;
        img_gray_433_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_gray_433_full_n : IN STD_LOGIC;
        img_gray_433_write : OUT STD_LOGIC;
        p_src_rows_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        p_src_rows_empty_n : IN STD_LOGIC;
        p_src_rows_read : OUT STD_LOGIC;
        p_src_cols_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        p_src_cols_empty_n : IN STD_LOGIC;
        p_src_cols_read : OUT STD_LOGIC );
    end component;


    component image_accelerator_resize_2_0_1080_1920_270_480_1_4_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        img_gray_433_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_gray_433_empty_n : IN STD_LOGIC;
        img_gray_433_read : OUT STD_LOGIC;
        img_out_434_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_out_434_full_n : IN STD_LOGIC;
        img_out_434_write : OUT STD_LOGIC;
        p_src_rows_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        p_src_rows_empty_n : IN STD_LOGIC;
        p_src_rows_read : OUT STD_LOGIC;
        p_src_cols_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        p_src_cols_empty_n : IN STD_LOGIC;
        p_src_cols_read : OUT STD_LOGIC;
        p_dst_rows_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        p_dst_rows_empty_n : IN STD_LOGIC;
        p_dst_rows_read : OUT STD_LOGIC;
        p_dst_cols_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        p_dst_cols_empty_n : IN STD_LOGIC;
        p_dst_cols_read : OUT STD_LOGIC;
        p_dst_rows_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_dst_rows_out_full_n : IN STD_LOGIC;
        p_dst_rows_out_write : OUT STD_LOGIC;
        p_dst_cols_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_dst_cols_out_full_n : IN STD_LOGIC;
        p_dst_cols_out_write : OUT STD_LOGIC );
    end component;


    component image_accelerator_xfMat2AXIvideo_8_0_270_480_1_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_out_434_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_out_434_empty_n : IN STD_LOGIC;
        img_out_434_read : OUT STD_LOGIC;
        img_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        img_1_empty_n : IN STD_LOGIC;
        img_1_read : OUT STD_LOGIC;
        img_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        img_2_empty_n : IN STD_LOGIC;
        img_2_read : OUT STD_LOGIC;
        video_out_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        video_out_TVALID : OUT STD_LOGIC;
        video_out_TREADY : IN STD_LOGIC;
        video_out_TKEEP : OUT STD_LOGIC_VECTOR (0 downto 0);
        video_out_TSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        video_out_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        video_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        video_out_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        video_out_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component image_accelerator_fifo_w32_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component image_accelerator_fifo_w32_d4_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component image_accelerator_fifo_w24_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (23 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (23 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component image_accelerator_fifo_w8_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component image_accelerator_start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component image_accelerator_start_for_resize_2_0_1080_1920_270_480_1_4_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component image_accelerator_start_for_rgb2gray_9_0_1080_1920_1_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component image_accelerator_start_for_xfMat2AXIvideo_8_0_270_480_1_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component image_accelerator_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        in_rows : OUT STD_LOGIC_VECTOR (31 downto 0);
        in_cols : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_rows : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_cols : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;



begin
    control_s_axi_U : component image_accelerator_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        in_rows => in_rows,
        in_cols => in_cols,
        out_rows => out_rows,
        out_cols => out_cols,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    Block_split1_proc_U0 : component image_accelerator_Block_split1_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Block_split1_proc_U0_ap_start,
        start_full_n => Block_split1_proc_U0_start_full_n,
        ap_done => Block_split1_proc_U0_ap_done,
        ap_continue => Block_split1_proc_U0_ap_continue,
        ap_idle => Block_split1_proc_U0_ap_idle,
        ap_ready => Block_split1_proc_U0_ap_ready,
        start_out => Block_split1_proc_U0_start_out,
        start_write => Block_split1_proc_U0_start_write,
        in_rows => in_rows,
        in_cols => in_cols,
        out_rows => out_rows,
        out_cols => out_cols,
        img_in_rows_out_din => Block_split1_proc_U0_img_in_rows_out_din,
        img_in_rows_out_full_n => img_in_rows_c_full_n,
        img_in_rows_out_write => Block_split1_proc_U0_img_in_rows_out_write,
        img_in_cols_out_din => Block_split1_proc_U0_img_in_cols_out_din,
        img_in_cols_out_full_n => img_in_cols_c_full_n,
        img_in_cols_out_write => Block_split1_proc_U0_img_in_cols_out_write,
        img_gray_rows_out_din => Block_split1_proc_U0_img_gray_rows_out_din,
        img_gray_rows_out_full_n => img_gray_rows_c_full_n,
        img_gray_rows_out_write => Block_split1_proc_U0_img_gray_rows_out_write,
        img_gray_cols_out_din => Block_split1_proc_U0_img_gray_cols_out_din,
        img_gray_cols_out_full_n => img_gray_cols_c_full_n,
        img_gray_cols_out_write => Block_split1_proc_U0_img_gray_cols_out_write,
        img_out_rows_out_din => Block_split1_proc_U0_img_out_rows_out_din,
        img_out_rows_out_full_n => img_out_rows_c_full_n,
        img_out_rows_out_write => Block_split1_proc_U0_img_out_rows_out_write,
        img_out_cols_out_din => Block_split1_proc_U0_img_out_cols_out_din,
        img_out_cols_out_full_n => img_out_cols_c_full_n,
        img_out_cols_out_write => Block_split1_proc_U0_img_out_cols_out_write);

    AXIvideo2xfMat_24_9_1080_1920_1_U0 : component image_accelerator_AXIvideo2xfMat_24_9_1080_1920_1_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_start,
        start_full_n => start_for_rgb2gray_9_0_1080_1920_1_U0_full_n,
        ap_done => AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_done,
        ap_continue => AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_continue,
        ap_idle => AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_idle,
        ap_ready => AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready,
        start_out => AXIvideo2xfMat_24_9_1080_1920_1_U0_start_out,
        start_write => AXIvideo2xfMat_24_9_1080_1920_1_U0_start_write,
        img_in_432_din => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_in_432_din,
        img_in_432_full_n => img_in_data_full_n,
        img_in_432_write => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_in_432_write,
        video_in_TDATA => video_in_TDATA,
        video_in_TVALID => video_in_TVALID,
        video_in_TREADY => AXIvideo2xfMat_24_9_1080_1920_1_U0_video_in_TREADY,
        video_in_TKEEP => video_in_TKEEP,
        video_in_TSTRB => video_in_TSTRB,
        video_in_TUSER => video_in_TUSER,
        video_in_TLAST => video_in_TLAST,
        video_in_TID => video_in_TID,
        video_in_TDEST => video_in_TDEST,
        img_1_dout => img_in_rows_c_dout,
        img_1_empty_n => img_in_rows_c_empty_n,
        img_1_read => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_read,
        img_2_dout => img_in_cols_c_dout,
        img_2_empty_n => img_in_cols_c_empty_n,
        img_2_read => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_read,
        img_1_out_din => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_out_din,
        img_1_out_full_n => img_in_rows_c11_full_n,
        img_1_out_write => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_out_write,
        img_2_out_din => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_out_din,
        img_2_out_full_n => img_in_cols_c12_full_n,
        img_2_out_write => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_out_write);

    rgb2gray_9_0_1080_1920_1_U0 : component image_accelerator_rgb2gray_9_0_1080_1920_1_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => rgb2gray_9_0_1080_1920_1_U0_ap_start,
        ap_done => rgb2gray_9_0_1080_1920_1_U0_ap_done,
        ap_continue => rgb2gray_9_0_1080_1920_1_U0_ap_continue,
        ap_idle => rgb2gray_9_0_1080_1920_1_U0_ap_idle,
        ap_ready => rgb2gray_9_0_1080_1920_1_U0_ap_ready,
        img_in_432_dout => img_in_data_dout,
        img_in_432_empty_n => img_in_data_empty_n,
        img_in_432_read => rgb2gray_9_0_1080_1920_1_U0_img_in_432_read,
        img_gray_433_din => rgb2gray_9_0_1080_1920_1_U0_img_gray_433_din,
        img_gray_433_full_n => img_gray_data_full_n,
        img_gray_433_write => rgb2gray_9_0_1080_1920_1_U0_img_gray_433_write,
        p_src_rows_dout => img_in_rows_c11_dout,
        p_src_rows_empty_n => img_in_rows_c11_empty_n,
        p_src_rows_read => rgb2gray_9_0_1080_1920_1_U0_p_src_rows_read,
        p_src_cols_dout => img_in_cols_c12_dout,
        p_src_cols_empty_n => img_in_cols_c12_empty_n,
        p_src_cols_read => rgb2gray_9_0_1080_1920_1_U0_p_src_cols_read);

    resize_2_0_1080_1920_270_480_1_4_U0 : component image_accelerator_resize_2_0_1080_1920_270_480_1_4_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => resize_2_0_1080_1920_270_480_1_4_U0_ap_start,
        start_full_n => start_for_xfMat2AXIvideo_8_0_270_480_1_U0_full_n,
        ap_done => resize_2_0_1080_1920_270_480_1_4_U0_ap_done,
        ap_continue => resize_2_0_1080_1920_270_480_1_4_U0_ap_continue,
        ap_idle => resize_2_0_1080_1920_270_480_1_4_U0_ap_idle,
        ap_ready => resize_2_0_1080_1920_270_480_1_4_U0_ap_ready,
        start_out => resize_2_0_1080_1920_270_480_1_4_U0_start_out,
        start_write => resize_2_0_1080_1920_270_480_1_4_U0_start_write,
        img_gray_433_dout => img_gray_data_dout,
        img_gray_433_empty_n => img_gray_data_empty_n,
        img_gray_433_read => resize_2_0_1080_1920_270_480_1_4_U0_img_gray_433_read,
        img_out_434_din => resize_2_0_1080_1920_270_480_1_4_U0_img_out_434_din,
        img_out_434_full_n => img_out_data_full_n,
        img_out_434_write => resize_2_0_1080_1920_270_480_1_4_U0_img_out_434_write,
        p_src_rows_dout => img_gray_rows_c_dout,
        p_src_rows_empty_n => img_gray_rows_c_empty_n,
        p_src_rows_read => resize_2_0_1080_1920_270_480_1_4_U0_p_src_rows_read,
        p_src_cols_dout => img_gray_cols_c_dout,
        p_src_cols_empty_n => img_gray_cols_c_empty_n,
        p_src_cols_read => resize_2_0_1080_1920_270_480_1_4_U0_p_src_cols_read,
        p_dst_rows_dout => img_out_rows_c_dout,
        p_dst_rows_empty_n => img_out_rows_c_empty_n,
        p_dst_rows_read => resize_2_0_1080_1920_270_480_1_4_U0_p_dst_rows_read,
        p_dst_cols_dout => img_out_cols_c_dout,
        p_dst_cols_empty_n => img_out_cols_c_empty_n,
        p_dst_cols_read => resize_2_0_1080_1920_270_480_1_4_U0_p_dst_cols_read,
        p_dst_rows_out_din => resize_2_0_1080_1920_270_480_1_4_U0_p_dst_rows_out_din,
        p_dst_rows_out_full_n => img_out_rows_c13_full_n,
        p_dst_rows_out_write => resize_2_0_1080_1920_270_480_1_4_U0_p_dst_rows_out_write,
        p_dst_cols_out_din => resize_2_0_1080_1920_270_480_1_4_U0_p_dst_cols_out_din,
        p_dst_cols_out_full_n => img_out_cols_c14_full_n,
        p_dst_cols_out_write => resize_2_0_1080_1920_270_480_1_4_U0_p_dst_cols_out_write);

    xfMat2AXIvideo_8_0_270_480_1_U0 : component image_accelerator_xfMat2AXIvideo_8_0_270_480_1_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => xfMat2AXIvideo_8_0_270_480_1_U0_ap_start,
        ap_done => xfMat2AXIvideo_8_0_270_480_1_U0_ap_done,
        ap_continue => xfMat2AXIvideo_8_0_270_480_1_U0_ap_continue,
        ap_idle => xfMat2AXIvideo_8_0_270_480_1_U0_ap_idle,
        ap_ready => xfMat2AXIvideo_8_0_270_480_1_U0_ap_ready,
        img_out_434_dout => img_out_data_dout,
        img_out_434_empty_n => img_out_data_empty_n,
        img_out_434_read => xfMat2AXIvideo_8_0_270_480_1_U0_img_out_434_read,
        img_1_dout => img_out_rows_c13_dout,
        img_1_empty_n => img_out_rows_c13_empty_n,
        img_1_read => xfMat2AXIvideo_8_0_270_480_1_U0_img_1_read,
        img_2_dout => img_out_cols_c14_dout,
        img_2_empty_n => img_out_cols_c14_empty_n,
        img_2_read => xfMat2AXIvideo_8_0_270_480_1_U0_img_2_read,
        video_out_TDATA => xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TDATA,
        video_out_TVALID => xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TVALID,
        video_out_TREADY => video_out_TREADY,
        video_out_TKEEP => xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TKEEP,
        video_out_TSTRB => xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TSTRB,
        video_out_TUSER => xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TUSER,
        video_out_TLAST => xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TLAST,
        video_out_TID => xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TID,
        video_out_TDEST => xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TDEST);

    img_in_rows_c_U : component image_accelerator_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_split1_proc_U0_img_in_rows_out_din,
        if_full_n => img_in_rows_c_full_n,
        if_write => Block_split1_proc_U0_img_in_rows_out_write,
        if_dout => img_in_rows_c_dout,
        if_empty_n => img_in_rows_c_empty_n,
        if_read => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_read);

    img_in_cols_c_U : component image_accelerator_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_split1_proc_U0_img_in_cols_out_din,
        if_full_n => img_in_cols_c_full_n,
        if_write => Block_split1_proc_U0_img_in_cols_out_write,
        if_dout => img_in_cols_c_dout,
        if_empty_n => img_in_cols_c_empty_n,
        if_read => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_read);

    img_gray_rows_c_U : component image_accelerator_fifo_w32_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_split1_proc_U0_img_gray_rows_out_din,
        if_full_n => img_gray_rows_c_full_n,
        if_write => Block_split1_proc_U0_img_gray_rows_out_write,
        if_dout => img_gray_rows_c_dout,
        if_empty_n => img_gray_rows_c_empty_n,
        if_read => resize_2_0_1080_1920_270_480_1_4_U0_p_src_rows_read);

    img_gray_cols_c_U : component image_accelerator_fifo_w32_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_split1_proc_U0_img_gray_cols_out_din,
        if_full_n => img_gray_cols_c_full_n,
        if_write => Block_split1_proc_U0_img_gray_cols_out_write,
        if_dout => img_gray_cols_c_dout,
        if_empty_n => img_gray_cols_c_empty_n,
        if_read => resize_2_0_1080_1920_270_480_1_4_U0_p_src_cols_read);

    img_out_rows_c_U : component image_accelerator_fifo_w32_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_split1_proc_U0_img_out_rows_out_din,
        if_full_n => img_out_rows_c_full_n,
        if_write => Block_split1_proc_U0_img_out_rows_out_write,
        if_dout => img_out_rows_c_dout,
        if_empty_n => img_out_rows_c_empty_n,
        if_read => resize_2_0_1080_1920_270_480_1_4_U0_p_dst_rows_read);

    img_out_cols_c_U : component image_accelerator_fifo_w32_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_split1_proc_U0_img_out_cols_out_din,
        if_full_n => img_out_cols_c_full_n,
        if_write => Block_split1_proc_U0_img_out_cols_out_write,
        if_dout => img_out_cols_c_dout,
        if_empty_n => img_out_cols_c_empty_n,
        if_read => resize_2_0_1080_1920_270_480_1_4_U0_p_dst_cols_read);

    img_in_data_U : component image_accelerator_fifo_w24_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_in_432_din,
        if_full_n => img_in_data_full_n,
        if_write => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_in_432_write,
        if_dout => img_in_data_dout,
        if_empty_n => img_in_data_empty_n,
        if_read => rgb2gray_9_0_1080_1920_1_U0_img_in_432_read);

    img_in_rows_c11_U : component image_accelerator_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_out_din,
        if_full_n => img_in_rows_c11_full_n,
        if_write => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_out_write,
        if_dout => img_in_rows_c11_dout,
        if_empty_n => img_in_rows_c11_empty_n,
        if_read => rgb2gray_9_0_1080_1920_1_U0_p_src_rows_read);

    img_in_cols_c12_U : component image_accelerator_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_out_din,
        if_full_n => img_in_cols_c12_full_n,
        if_write => AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_out_write,
        if_dout => img_in_cols_c12_dout,
        if_empty_n => img_in_cols_c12_empty_n,
        if_read => rgb2gray_9_0_1080_1920_1_U0_p_src_cols_read);

    img_gray_data_U : component image_accelerator_fifo_w8_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => rgb2gray_9_0_1080_1920_1_U0_img_gray_433_din,
        if_full_n => img_gray_data_full_n,
        if_write => rgb2gray_9_0_1080_1920_1_U0_img_gray_433_write,
        if_dout => img_gray_data_dout,
        if_empty_n => img_gray_data_empty_n,
        if_read => resize_2_0_1080_1920_270_480_1_4_U0_img_gray_433_read);

    img_out_data_U : component image_accelerator_fifo_w8_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => resize_2_0_1080_1920_270_480_1_4_U0_img_out_434_din,
        if_full_n => img_out_data_full_n,
        if_write => resize_2_0_1080_1920_270_480_1_4_U0_img_out_434_write,
        if_dout => img_out_data_dout,
        if_empty_n => img_out_data_empty_n,
        if_read => xfMat2AXIvideo_8_0_270_480_1_U0_img_out_434_read);

    img_out_rows_c13_U : component image_accelerator_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => resize_2_0_1080_1920_270_480_1_4_U0_p_dst_rows_out_din,
        if_full_n => img_out_rows_c13_full_n,
        if_write => resize_2_0_1080_1920_270_480_1_4_U0_p_dst_rows_out_write,
        if_dout => img_out_rows_c13_dout,
        if_empty_n => img_out_rows_c13_empty_n,
        if_read => xfMat2AXIvideo_8_0_270_480_1_U0_img_1_read);

    img_out_cols_c14_U : component image_accelerator_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => resize_2_0_1080_1920_270_480_1_4_U0_p_dst_cols_out_din,
        if_full_n => img_out_cols_c14_full_n,
        if_write => resize_2_0_1080_1920_270_480_1_4_U0_p_dst_cols_out_write,
        if_dout => img_out_cols_c14_dout,
        if_empty_n => img_out_cols_c14_empty_n,
        if_read => xfMat2AXIvideo_8_0_270_480_1_U0_img_2_read);

    start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_U : component image_accelerator_start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_din,
        if_full_n => start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_full_n,
        if_write => Block_split1_proc_U0_start_write,
        if_dout => start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_dout,
        if_empty_n => start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_empty_n,
        if_read => AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready);

    start_for_resize_2_0_1080_1920_270_480_1_4_U0_U : component image_accelerator_start_for_resize_2_0_1080_1920_270_480_1_4_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_resize_2_0_1080_1920_270_480_1_4_U0_din,
        if_full_n => start_for_resize_2_0_1080_1920_270_480_1_4_U0_full_n,
        if_write => Block_split1_proc_U0_start_write,
        if_dout => start_for_resize_2_0_1080_1920_270_480_1_4_U0_dout,
        if_empty_n => start_for_resize_2_0_1080_1920_270_480_1_4_U0_empty_n,
        if_read => resize_2_0_1080_1920_270_480_1_4_U0_ap_ready);

    start_for_rgb2gray_9_0_1080_1920_1_U0_U : component image_accelerator_start_for_rgb2gray_9_0_1080_1920_1_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_rgb2gray_9_0_1080_1920_1_U0_din,
        if_full_n => start_for_rgb2gray_9_0_1080_1920_1_U0_full_n,
        if_write => AXIvideo2xfMat_24_9_1080_1920_1_U0_start_write,
        if_dout => start_for_rgb2gray_9_0_1080_1920_1_U0_dout,
        if_empty_n => start_for_rgb2gray_9_0_1080_1920_1_U0_empty_n,
        if_read => rgb2gray_9_0_1080_1920_1_U0_ap_ready);

    start_for_xfMat2AXIvideo_8_0_270_480_1_U0_U : component image_accelerator_start_for_xfMat2AXIvideo_8_0_270_480_1_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_xfMat2AXIvideo_8_0_270_480_1_U0_din,
        if_full_n => start_for_xfMat2AXIvideo_8_0_270_480_1_U0_full_n,
        if_write => resize_2_0_1080_1920_270_480_1_4_U0_start_write,
        if_dout => start_for_xfMat2AXIvideo_8_0_270_480_1_U0_dout,
        if_empty_n => start_for_xfMat2AXIvideo_8_0_270_480_1_U0_empty_n,
        if_read => xfMat2AXIvideo_8_0_270_480_1_U0_ap_ready);




    AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_continue <= ap_const_logic_1;
    AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_start <= start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_empty_n;
    Block_split1_proc_U0_ap_continue <= ap_const_logic_1;
    Block_split1_proc_U0_ap_start <= ap_start;
    Block_split1_proc_U0_start_full_n <= (start_for_resize_2_0_1080_1920_270_480_1_4_U0_full_n and start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_full_n);
    ap_done <= xfMat2AXIvideo_8_0_270_480_1_U0_ap_done;
    ap_idle <= (xfMat2AXIvideo_8_0_270_480_1_U0_ap_idle and rgb2gray_9_0_1080_1920_1_U0_ap_idle and resize_2_0_1080_1920_270_480_1_4_U0_ap_idle and Block_split1_proc_U0_ap_idle and AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_idle);
    ap_ready <= Block_split1_proc_U0_ap_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_continue <= ap_const_logic_1;
    ap_sync_done <= xfMat2AXIvideo_8_0_270_480_1_U0_ap_done;
    ap_sync_ready <= Block_split1_proc_U0_ap_ready;
    resize_2_0_1080_1920_270_480_1_4_U0_ap_continue <= ap_const_logic_1;
    resize_2_0_1080_1920_270_480_1_4_U0_ap_start <= start_for_resize_2_0_1080_1920_270_480_1_4_U0_empty_n;
    rgb2gray_9_0_1080_1920_1_U0_ap_continue <= ap_const_logic_1;
    rgb2gray_9_0_1080_1920_1_U0_ap_start <= start_for_rgb2gray_9_0_1080_1920_1_U0_empty_n;
    rgb2gray_9_0_1080_1920_1_U0_start_full_n <= ap_const_logic_1;
    rgb2gray_9_0_1080_1920_1_U0_start_write <= ap_const_logic_0;
    start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_resize_2_0_1080_1920_270_480_1_4_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_rgb2gray_9_0_1080_1920_1_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_xfMat2AXIvideo_8_0_270_480_1_U0_din <= (0=>ap_const_logic_1, others=>'-');
    video_in_TREADY <= AXIvideo2xfMat_24_9_1080_1920_1_U0_video_in_TREADY;
    video_out_TDATA <= xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TDATA;
    video_out_TDEST <= xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TDEST;
    video_out_TID <= xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TID;
    video_out_TKEEP <= xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TKEEP;
    video_out_TLAST <= xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TLAST;
    video_out_TSTRB <= xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TSTRB;
    video_out_TUSER <= xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TUSER;
    video_out_TVALID <= xfMat2AXIvideo_8_0_270_480_1_U0_video_out_TVALID;
    xfMat2AXIvideo_8_0_270_480_1_U0_ap_continue <= ap_const_logic_1;
    xfMat2AXIvideo_8_0_270_480_1_U0_ap_start <= start_for_xfMat2AXIvideo_8_0_270_480_1_U0_empty_n;
    xfMat2AXIvideo_8_0_270_480_1_U0_start_full_n <= ap_const_logic_1;
    xfMat2AXIvideo_8_0_270_480_1_U0_start_write <= ap_const_logic_0;
end behav;
