-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity image_accelerator_xfMat2AXIvideo_8_0_270_480_1_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    img_out_434_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    img_out_434_empty_n : IN STD_LOGIC;
    img_out_434_read : OUT STD_LOGIC;
    img_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    img_1_empty_n : IN STD_LOGIC;
    img_1_read : OUT STD_LOGIC;
    img_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    img_2_empty_n : IN STD_LOGIC;
    img_2_read : OUT STD_LOGIC;
    video_out_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    video_out_TVALID : OUT STD_LOGIC;
    video_out_TREADY : IN STD_LOGIC;
    video_out_TKEEP : OUT STD_LOGIC_VECTOR (0 downto 0);
    video_out_TSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    video_out_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    video_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    video_out_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    video_out_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of image_accelerator_xfMat2AXIvideo_8_0_270_480_1_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal img_out_434_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln197_reg_271 : STD_LOGIC_VECTOR (0 downto 0);
    signal img_1_blk_n : STD_LOGIC;
    signal img_2_blk_n : STD_LOGIC;
    signal video_out_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal icmp_ln197_reg_271_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal j_reg_141 : STD_LOGIC_VECTOR (8 downto 0);
    signal sof_3_reg_152 : STD_LOGIC_VECTOR (0 downto 0);
    signal rows_reg_233 : STD_LOGIC_VECTOR (31 downto 0);
    signal cols_reg_238 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_i_fu_166_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_i_reg_243 : STD_LOGIC_VECTOR (31 downto 0);
    signal cmp71_i_fu_172_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp71_i_reg_248 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_1_fu_183_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal i_1_reg_252 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal regslice_both_AXI_video_strm_V_data_V_U_apdone_blk : STD_LOGIC;
    signal icmp_ln195_fu_196_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_1_fu_201_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_state3_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_io : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state5_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln197_fu_211_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_last_V_fu_216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_last_V_reg_275 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_flush_enable : STD_LOGIC;
    signal ap_condition_pp0_exit_iter1_state4 : STD_LOGIC;
    signal i_reg_130 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_phi_mux_sof_3_phi_fu_157_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal sof_fu_78 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln195_fu_192_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln197_fu_207_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal video_out_TVALID_int_regslice : STD_LOGIC;
    signal video_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_dest_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component image_accelerator_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_AXI_video_strm_V_data_V_U : component image_accelerator_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => img_out_434_dout,
        vld_in => video_out_TVALID_int_regslice,
        ack_in => video_out_TREADY_int_regslice,
        data_out => video_out_TDATA,
        vld_out => regslice_both_AXI_video_strm_V_data_V_U_vld_out,
        ack_out => video_out_TREADY,
        apdone_blk => regslice_both_AXI_video_strm_V_data_V_U_apdone_blk);

    regslice_both_AXI_video_strm_V_keep_V_U : component image_accelerator_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_const_lv1_1,
        vld_in => video_out_TVALID_int_regslice,
        ack_in => regslice_both_AXI_video_strm_V_keep_V_U_ack_in_dummy,
        data_out => video_out_TKEEP,
        vld_out => regslice_both_AXI_video_strm_V_keep_V_U_vld_out,
        ack_out => video_out_TREADY,
        apdone_blk => regslice_both_AXI_video_strm_V_keep_V_U_apdone_blk);

    regslice_both_AXI_video_strm_V_strb_V_U : component image_accelerator_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_const_lv1_0,
        vld_in => video_out_TVALID_int_regslice,
        ack_in => regslice_both_AXI_video_strm_V_strb_V_U_ack_in_dummy,
        data_out => video_out_TSTRB,
        vld_out => regslice_both_AXI_video_strm_V_strb_V_U_vld_out,
        ack_out => video_out_TREADY,
        apdone_blk => regslice_both_AXI_video_strm_V_strb_V_U_apdone_blk);

    regslice_both_AXI_video_strm_V_user_V_U : component image_accelerator_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_phi_mux_sof_3_phi_fu_157_p4,
        vld_in => video_out_TVALID_int_regslice,
        ack_in => regslice_both_AXI_video_strm_V_user_V_U_ack_in_dummy,
        data_out => video_out_TUSER,
        vld_out => regslice_both_AXI_video_strm_V_user_V_U_vld_out,
        ack_out => video_out_TREADY,
        apdone_blk => regslice_both_AXI_video_strm_V_user_V_U_apdone_blk);

    regslice_both_AXI_video_strm_V_last_V_U : component image_accelerator_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => axi_last_V_reg_275,
        vld_in => video_out_TVALID_int_regslice,
        ack_in => regslice_both_AXI_video_strm_V_last_V_U_ack_in_dummy,
        data_out => video_out_TLAST,
        vld_out => regslice_both_AXI_video_strm_V_last_V_U_vld_out,
        ack_out => video_out_TREADY,
        apdone_blk => regslice_both_AXI_video_strm_V_last_V_U_apdone_blk);

    regslice_both_AXI_video_strm_V_id_V_U : component image_accelerator_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_const_lv1_0,
        vld_in => video_out_TVALID_int_regslice,
        ack_in => regslice_both_AXI_video_strm_V_id_V_U_ack_in_dummy,
        data_out => video_out_TID,
        vld_out => regslice_both_AXI_video_strm_V_id_V_U_vld_out,
        ack_out => video_out_TREADY,
        apdone_blk => regslice_both_AXI_video_strm_V_id_V_U_apdone_blk);

    regslice_both_AXI_video_strm_V_dest_V_U : component image_accelerator_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_const_lv1_0,
        vld_in => video_out_TVALID_int_regslice,
        ack_in => regslice_both_AXI_video_strm_V_dest_V_U_ack_in_dummy,
        data_out => video_out_TDEST,
        vld_out => regslice_both_AXI_video_strm_V_dest_V_U_vld_out,
        ack_out => video_out_TREADY,
        apdone_blk => regslice_both_AXI_video_strm_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((regslice_both_AXI_video_strm_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln195_fu_196_p2 = ap_const_lv1_0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_pp0_flush_enable)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((regslice_both_AXI_video_strm_V_data_V_U_apdone_blk = ap_const_logic_0) and (cmp71_i_reg_248 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln195_fu_196_p2 = ap_const_lv1_1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter1_state4) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0)) or ((regslice_both_AXI_video_strm_V_data_V_U_apdone_blk = ap_const_logic_0) and (cmp71_i_reg_248 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln195_fu_196_p2 = ap_const_lv1_1)))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter1_state4))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif (((regslice_both_AXI_video_strm_V_data_V_U_apdone_blk = ap_const_logic_0) and (cmp71_i_reg_248 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln195_fu_196_p2 = ap_const_lv1_1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_reg_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                i_reg_130 <= i_1_reg_252;
            elsif ((not(((ap_start = ap_const_logic_0) or (img_2_empty_n = ap_const_logic_0) or (img_1_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_reg_130 <= ap_const_lv9_0;
            end if; 
        end if;
    end process;

    j_reg_141_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((regslice_both_AXI_video_strm_V_data_V_U_apdone_blk = ap_const_logic_0) and (cmp71_i_reg_248 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln195_fu_196_p2 = ap_const_lv1_1))) then 
                j_reg_141 <= ap_const_lv9_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln197_fu_211_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                j_reg_141 <= j_1_fu_201_p2;
            end if; 
        end if;
    end process;

    sof_3_reg_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((regslice_both_AXI_video_strm_V_data_V_U_apdone_blk = ap_const_logic_0) and (cmp71_i_reg_248 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln195_fu_196_p2 = ap_const_lv1_1))) then 
                sof_3_reg_152 <= sof_fu_78;
            elsif (((icmp_ln197_reg_271_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                sof_3_reg_152 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    sof_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start = ap_const_logic_0) or (img_2_empty_n = ap_const_logic_0) or (img_1_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                sof_fu_78 <= ap_const_lv1_1;
            elsif (((cmp71_i_reg_248 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                sof_fu_78 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln197_fu_211_p2 = ap_const_lv1_0))) then
                axi_last_V_reg_275 <= axi_last_V_fu_216_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                cmp71_i_reg_248 <= cmp71_i_fu_172_p2;
                cols_reg_238 <= img_2_dout;
                rows_reg_233 <= img_1_dout;
                sub_i_reg_243 <= sub_i_fu_166_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((regslice_both_AXI_video_strm_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                i_1_reg_252 <= i_1_fu_183_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln197_reg_271 <= icmp_ln197_fu_211_p2;
                icmp_ln197_reg_271_pp0_iter1_reg <= icmp_ln197_reg_271;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, img_1_empty_n, img_2_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, cmp71_i_reg_248, ap_CS_fsm_state2, regslice_both_AXI_video_strm_V_data_V_U_apdone_blk, icmp_ln195_fu_196_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (img_2_empty_n = ap_const_logic_0) or (img_1_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((regslice_both_AXI_video_strm_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln195_fu_196_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((regslice_both_AXI_video_strm_V_data_V_U_apdone_blk = ap_const_logic_0) and (cmp71_i_reg_248 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln195_fu_196_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((regslice_both_AXI_video_strm_V_data_V_U_apdone_blk = ap_const_logic_0) and (cmp71_i_reg_248 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln195_fu_196_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state6 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(img_out_434_empty_n, ap_enable_reg_pp0_iter1, icmp_ln197_reg_271, ap_enable_reg_pp0_iter2, icmp_ln197_reg_271_pp0_iter1_reg, video_out_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_01001 <= (((icmp_ln197_reg_271_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (video_out_TREADY_int_regslice = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((icmp_ln197_reg_271 = ap_const_lv1_0) and (video_out_TREADY_int_regslice = ap_const_logic_0)) or ((icmp_ln197_reg_271 = ap_const_lv1_0) and (img_out_434_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(img_out_434_empty_n, ap_enable_reg_pp0_iter1, icmp_ln197_reg_271, ap_enable_reg_pp0_iter2, icmp_ln197_reg_271_pp0_iter1_reg, ap_block_state4_io, ap_block_state5_io, video_out_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state5_io) or ((icmp_ln197_reg_271_pp0_iter1_reg = ap_const_lv1_0) and (video_out_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state4_io) or ((icmp_ln197_reg_271 = ap_const_lv1_0) and (video_out_TREADY_int_regslice = ap_const_logic_0)) or ((icmp_ln197_reg_271 = ap_const_lv1_0) and (img_out_434_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(img_out_434_empty_n, ap_enable_reg_pp0_iter1, icmp_ln197_reg_271, ap_enable_reg_pp0_iter2, icmp_ln197_reg_271_pp0_iter1_reg, ap_block_state4_io, ap_block_state5_io, video_out_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state5_io) or ((icmp_ln197_reg_271_pp0_iter1_reg = ap_const_lv1_0) and (video_out_TREADY_int_regslice = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state4_io) or ((icmp_ln197_reg_271 = ap_const_lv1_0) and (video_out_TREADY_int_regslice = ap_const_logic_0)) or ((icmp_ln197_reg_271 = ap_const_lv1_0) and (img_out_434_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, img_1_empty_n, img_2_empty_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (img_2_empty_n = ap_const_logic_0) or (img_1_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state3_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state4_io_assign_proc : process(icmp_ln197_reg_271, video_out_TREADY_int_regslice)
    begin
                ap_block_state4_io <= ((icmp_ln197_reg_271 = ap_const_lv1_0) and (video_out_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage0_iter1_assign_proc : process(img_out_434_empty_n, icmp_ln197_reg_271, video_out_TREADY_int_regslice)
    begin
                ap_block_state4_pp0_stage0_iter1 <= (((icmp_ln197_reg_271 = ap_const_lv1_0) and (video_out_TREADY_int_regslice = ap_const_logic_0)) or ((icmp_ln197_reg_271 = ap_const_lv1_0) and (img_out_434_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state5_io_assign_proc : process(icmp_ln197_reg_271_pp0_iter1_reg, video_out_TREADY_int_regslice)
    begin
                ap_block_state5_io <= ((icmp_ln197_reg_271_pp0_iter1_reg = ap_const_lv1_0) and (video_out_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state5_pp0_stage0_iter2_assign_proc : process(icmp_ln197_reg_271_pp0_iter1_reg, video_out_TREADY_int_regslice)
    begin
                ap_block_state5_pp0_stage0_iter2 <= ((icmp_ln197_reg_271_pp0_iter1_reg = ap_const_lv1_0) and (video_out_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_condition_pp0_exit_iter1_state4_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_condition_pp0_exit_iter1_state4 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter1_state4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp0_flush_enable_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln197_fu_211_p2, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln197_fu_211_p2 = ap_const_lv1_1))) then 
            ap_condition_pp0_flush_enable <= ap_const_logic_1;
        else 
            ap_condition_pp0_flush_enable <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, regslice_both_AXI_video_strm_V_data_V_U_apdone_blk, icmp_ln195_fu_196_p2)
    begin
        if (((regslice_both_AXI_video_strm_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln195_fu_196_p2 = ap_const_lv1_0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_sof_3_phi_fu_157_p4_assign_proc : process(ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln197_reg_271_pp0_iter1_reg, sof_3_reg_152)
    begin
        if (((icmp_ln197_reg_271_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_sof_3_phi_fu_157_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_sof_3_phi_fu_157_p4 <= sof_3_reg_152;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, regslice_both_AXI_video_strm_V_data_V_U_apdone_blk, icmp_ln195_fu_196_p2)
    begin
        if (((regslice_both_AXI_video_strm_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln195_fu_196_p2 = ap_const_lv1_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    axi_last_V_fu_216_p2 <= "1" when (zext_ln197_fu_207_p1 = sub_i_reg_243) else "0";
    cmp71_i_fu_172_p2 <= "1" when (signed(img_2_dout) > signed(ap_const_lv32_0)) else "0";
    i_1_fu_183_p2 <= std_logic_vector(unsigned(i_reg_130) + unsigned(ap_const_lv9_1));
    icmp_ln195_fu_196_p2 <= "1" when (signed(zext_ln195_fu_192_p1) < signed(rows_reg_233)) else "0";
    icmp_ln197_fu_211_p2 <= "1" when (zext_ln197_fu_207_p1 = cols_reg_238) else "0";

    img_1_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, img_1_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_1_blk_n <= img_1_empty_n;
        else 
            img_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_1_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, img_1_empty_n, img_2_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (img_2_empty_n = ap_const_logic_0) or (img_1_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_1_read <= ap_const_logic_1;
        else 
            img_1_read <= ap_const_logic_0;
        end if; 
    end process;


    img_2_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, img_2_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_2_blk_n <= img_2_empty_n;
        else 
            img_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_2_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, img_1_empty_n, img_2_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (img_2_empty_n = ap_const_logic_0) or (img_1_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_2_read <= ap_const_logic_1;
        else 
            img_2_read <= ap_const_logic_0;
        end if; 
    end process;


    img_out_434_blk_n_assign_proc : process(img_out_434_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln197_reg_271)
    begin
        if (((icmp_ln197_reg_271 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            img_out_434_blk_n <= img_out_434_empty_n;
        else 
            img_out_434_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_out_434_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln197_reg_271, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln197_reg_271 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            img_out_434_read <= ap_const_logic_1;
        else 
            img_out_434_read <= ap_const_logic_0;
        end if; 
    end process;

    j_1_fu_201_p2 <= std_logic_vector(unsigned(j_reg_141) + unsigned(ap_const_lv9_1));
    sub_i_fu_166_p2 <= std_logic_vector(unsigned(img_2_dout) + unsigned(ap_const_lv32_FFFFFFFF));

    video_out_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln197_reg_271, ap_enable_reg_pp0_iter2, icmp_ln197_reg_271_pp0_iter1_reg, video_out_TREADY_int_regslice)
    begin
        if ((((icmp_ln197_reg_271_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((icmp_ln197_reg_271 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            video_out_TDATA_blk_n <= video_out_TREADY_int_regslice;
        else 
            video_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    video_out_TVALID <= regslice_both_AXI_video_strm_V_data_V_U_vld_out;

    video_out_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln197_reg_271, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln197_reg_271 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            video_out_TVALID_int_regslice <= ap_const_logic_1;
        else 
            video_out_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln195_fu_192_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_130),32));
    zext_ln197_fu_207_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_reg_141),32));
end behav;
