-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity image_accelerator_resize_2_0_1080_1920_270_480_1_4_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    img_gray_433_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    img_gray_433_empty_n : IN STD_LOGIC;
    img_gray_433_read : OUT STD_LOGIC;
    img_out_434_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_out_434_full_n : IN STD_LOGIC;
    img_out_434_write : OUT STD_LOGIC;
    p_src_rows_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    p_src_rows_empty_n : IN STD_LOGIC;
    p_src_rows_read : OUT STD_LOGIC;
    p_src_cols_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    p_src_cols_empty_n : IN STD_LOGIC;
    p_src_cols_read : OUT STD_LOGIC;
    p_dst_rows_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    p_dst_rows_empty_n : IN STD_LOGIC;
    p_dst_rows_read : OUT STD_LOGIC;
    p_dst_cols_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    p_dst_cols_empty_n : IN STD_LOGIC;
    p_dst_cols_read : OUT STD_LOGIC;
    p_dst_rows_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_dst_rows_out_full_n : IN STD_LOGIC;
    p_dst_rows_out_write : OUT STD_LOGIC;
    p_dst_cols_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_dst_cols_out_full_n : IN STD_LOGIC;
    p_dst_cols_out_write : OUT STD_LOGIC );
end;


architecture behav of image_accelerator_resize_2_0_1080_1920_270_480_1_4_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal p_src_rows_blk_n : STD_LOGIC;
    signal p_src_cols_blk_n : STD_LOGIC;
    signal p_dst_rows_blk_n : STD_LOGIC;
    signal p_dst_cols_blk_n : STD_LOGIC;
    signal p_dst_rows_out_blk_n : STD_LOGIC;
    signal p_dst_cols_out_blk_n : STD_LOGIC;
    signal empty_fu_106_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_reg_140 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_50_fu_110_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_50_reg_146 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_51_fu_114_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_51_reg_152 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_52_fu_118_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_52_reg_158 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln50_fu_134_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln50_reg_164 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_ap_start : STD_LOGIC;
    signal grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_ap_done : STD_LOGIC;
    signal grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_ap_idle : STD_LOGIC;
    signal grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_ap_ready : STD_LOGIC;
    signal grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_img_gray_433_read : STD_LOGIC;
    signal grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_img_out_434_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_img_out_434_write : STD_LOGIC;
    signal grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_ap_start : STD_LOGIC;
    signal grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_ap_done : STD_LOGIC;
    signal grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_ap_idle : STD_LOGIC;
    signal grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_ap_ready : STD_LOGIC;
    signal grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_img_gray_433_read : STD_LOGIC;
    signal grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_img_out_434_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_img_out_434_write : STD_LOGIC;
    signal grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_block_state1 : BOOLEAN;
    signal icmp_ln50_fu_122_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_1_fu_128_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_on_subcall_done : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component image_accelerator_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_gray_433_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_gray_433_empty_n : IN STD_LOGIC;
        img_gray_433_read : OUT STD_LOGIC;
        img_out_434_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_out_434_full_n : IN STD_LOGIC;
        img_out_434_write : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component image_accelerator_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_gray_433_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_gray_433_empty_n : IN STD_LOGIC;
        img_gray_433_read : OUT STD_LOGIC;
        img_out_434_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_out_434_full_n : IN STD_LOGIC;
        img_out_434_write : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82 : component image_accelerator_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_ap_start,
        ap_done => grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_ap_done,
        ap_idle => grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_ap_idle,
        ap_ready => grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_ap_ready,
        img_gray_433_dout => img_gray_433_dout,
        img_gray_433_empty_n => img_gray_433_empty_n,
        img_gray_433_read => grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_img_gray_433_read,
        img_out_434_din => grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_img_out_434_din,
        img_out_434_full_n => img_out_434_full_n,
        img_out_434_write => grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_img_out_434_write,
        p_read => empty_reg_140,
        p_read1 => empty_50_reg_146,
        p_read2 => empty_51_reg_152,
        p_read3 => empty_52_reg_158);

    grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94 : component image_accelerator_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_ap_start,
        ap_done => grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_ap_done,
        ap_idle => grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_ap_idle,
        ap_ready => grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_ap_ready,
        img_gray_433_dout => img_gray_433_dout,
        img_gray_433_empty_n => img_gray_433_empty_n,
        img_gray_433_read => grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_img_gray_433_read,
        img_out_434_din => grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_img_out_434_din,
        img_out_434_full_n => img_out_434_full_n,
        img_out_434_write => grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_img_out_434_write,
        p_read => empty_reg_140,
        p_read1 => empty_50_reg_146,
        p_read2 => empty_51_reg_152,
        p_read3 => empty_52_reg_158);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_on_subcall_done))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_ap_ready = ap_const_logic_1)) then 
                    grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_ap_ready = ap_const_logic_1)) then 
                    grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                and_ln50_reg_164 <= and_ln50_fu_134_p2;
                empty_50_reg_146 <= empty_50_fu_110_p1;
                empty_51_reg_152 <= empty_51_fu_114_p1;
                empty_52_reg_158 <= empty_52_fu_118_p1;
                empty_reg_140 <= empty_fu_106_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, p_src_rows_empty_n, p_src_cols_empty_n, p_dst_rows_empty_n, p_dst_cols_empty_n, p_dst_rows_out_full_n, p_dst_cols_out_full_n, and_ln50_fu_134_p2, ap_CS_fsm_state3, ap_block_state3_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((p_dst_cols_out_full_n = ap_const_logic_0) or (p_dst_rows_out_full_n = ap_const_logic_0) or (p_dst_cols_empty_n = ap_const_logic_0) or (p_dst_rows_empty_n = ap_const_logic_0) or (p_src_cols_empty_n = ap_const_logic_0) or (p_src_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_1 = and_ln50_fu_134_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                elsif ((not(((p_dst_cols_out_full_n = ap_const_logic_0) or (p_dst_rows_out_full_n = ap_const_logic_0) or (p_dst_cols_empty_n = ap_const_logic_0) or (p_dst_rows_empty_n = ap_const_logic_0) or (p_src_cols_empty_n = ap_const_logic_0) or (p_src_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_lv1_0 = and_ln50_fu_134_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_on_subcall_done))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    and_ln50_fu_134_p2 <= (icmp_ln50_fu_122_p2 and icmp_ln50_1_fu_128_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_block_state1_assign_proc : process(real_start, ap_done_reg, p_src_rows_empty_n, p_src_cols_empty_n, p_dst_rows_empty_n, p_dst_cols_empty_n, p_dst_rows_out_full_n, p_dst_cols_out_full_n)
    begin
                ap_block_state1 <= ((p_dst_cols_out_full_n = ap_const_logic_0) or (p_dst_rows_out_full_n = ap_const_logic_0) or (p_dst_cols_empty_n = ap_const_logic_0) or (p_dst_rows_empty_n = ap_const_logic_0) or (p_src_cols_empty_n = ap_const_logic_0) or (p_src_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state3_on_subcall_done_assign_proc : process(and_ln50_reg_164, grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_ap_done, grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_ap_done)
    begin
                ap_block_state3_on_subcall_done <= (((grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_ap_done = ap_const_logic_0) and (ap_const_lv1_1 = and_ln50_reg_164)) or ((ap_const_lv1_0 = and_ln50_reg_164) and (grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_ap_done = ap_const_logic_0)));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state3, ap_block_state3_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_on_subcall_done))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    empty_50_fu_110_p1 <= p_src_cols_dout(16 - 1 downto 0);
    empty_51_fu_114_p1 <= p_dst_rows_dout(16 - 1 downto 0);
    empty_52_fu_118_p1 <= p_dst_cols_dout(16 - 1 downto 0);
    empty_fu_106_p1 <= p_src_rows_dout(16 - 1 downto 0);
    grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_ap_start <= grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_ap_start_reg;
    grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_ap_start <= grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_ap_start_reg;
    icmp_ln50_1_fu_128_p2 <= "1" when (signed(p_src_cols_dout) < signed(p_dst_cols_dout)) else "0";
    icmp_ln50_fu_122_p2 <= "1" when (signed(p_src_rows_dout) < signed(p_dst_rows_dout)) else "0";

    img_gray_433_read_assign_proc : process(and_ln50_reg_164, grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_img_gray_433_read, grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_img_gray_433_read, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((ap_const_lv1_0 = and_ln50_reg_164)) then 
                img_gray_433_read <= grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_img_gray_433_read;
            elsif ((ap_const_lv1_1 = and_ln50_reg_164)) then 
                img_gray_433_read <= grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_img_gray_433_read;
            else 
                img_gray_433_read <= ap_const_logic_0;
            end if;
        else 
            img_gray_433_read <= ap_const_logic_0;
        end if; 
    end process;


    img_out_434_din_assign_proc : process(and_ln50_reg_164, grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_img_out_434_din, grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_img_out_434_din, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((ap_const_lv1_0 = and_ln50_reg_164)) then 
                img_out_434_din <= grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_img_out_434_din;
            elsif ((ap_const_lv1_1 = and_ln50_reg_164)) then 
                img_out_434_din <= grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_img_out_434_din;
            else 
                img_out_434_din <= grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_img_out_434_din;
            end if;
        else 
            img_out_434_din <= grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_img_out_434_din;
        end if; 
    end process;


    img_out_434_write_assign_proc : process(and_ln50_reg_164, grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_img_out_434_write, grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_img_out_434_write, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((ap_const_lv1_0 = and_ln50_reg_164)) then 
                img_out_434_write <= grp_xFResizeAreaDownScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_94_img_out_434_write;
            elsif ((ap_const_lv1_1 = and_ln50_reg_164)) then 
                img_out_434_write <= grp_xFResizeAreaUpScale_1080_1920_1_0_1_1_270_480_1920_480_s_fu_82_img_out_434_write;
            else 
                img_out_434_write <= ap_const_logic_0;
            end if;
        else 
            img_out_434_write <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(ap_CS_fsm_state3, ap_block_state3_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3_on_subcall_done))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    p_dst_cols_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, p_dst_cols_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_dst_cols_blk_n <= p_dst_cols_empty_n;
        else 
            p_dst_cols_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_dst_cols_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, p_dst_cols_out_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_dst_cols_out_blk_n <= p_dst_cols_out_full_n;
        else 
            p_dst_cols_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    p_dst_cols_out_din <= p_dst_cols_dout;

    p_dst_cols_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, p_src_rows_empty_n, p_src_cols_empty_n, p_dst_rows_empty_n, p_dst_cols_empty_n, p_dst_rows_out_full_n, p_dst_cols_out_full_n)
    begin
        if ((not(((p_dst_cols_out_full_n = ap_const_logic_0) or (p_dst_rows_out_full_n = ap_const_logic_0) or (p_dst_cols_empty_n = ap_const_logic_0) or (p_dst_rows_empty_n = ap_const_logic_0) or (p_src_cols_empty_n = ap_const_logic_0) or (p_src_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_dst_cols_out_write <= ap_const_logic_1;
        else 
            p_dst_cols_out_write <= ap_const_logic_0;
        end if; 
    end process;


    p_dst_cols_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, p_src_rows_empty_n, p_src_cols_empty_n, p_dst_rows_empty_n, p_dst_cols_empty_n, p_dst_rows_out_full_n, p_dst_cols_out_full_n)
    begin
        if ((not(((p_dst_cols_out_full_n = ap_const_logic_0) or (p_dst_rows_out_full_n = ap_const_logic_0) or (p_dst_cols_empty_n = ap_const_logic_0) or (p_dst_rows_empty_n = ap_const_logic_0) or (p_src_cols_empty_n = ap_const_logic_0) or (p_src_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_dst_cols_read <= ap_const_logic_1;
        else 
            p_dst_cols_read <= ap_const_logic_0;
        end if; 
    end process;


    p_dst_rows_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, p_dst_rows_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_dst_rows_blk_n <= p_dst_rows_empty_n;
        else 
            p_dst_rows_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_dst_rows_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, p_dst_rows_out_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_dst_rows_out_blk_n <= p_dst_rows_out_full_n;
        else 
            p_dst_rows_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    p_dst_rows_out_din <= p_dst_rows_dout;

    p_dst_rows_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, p_src_rows_empty_n, p_src_cols_empty_n, p_dst_rows_empty_n, p_dst_cols_empty_n, p_dst_rows_out_full_n, p_dst_cols_out_full_n)
    begin
        if ((not(((p_dst_cols_out_full_n = ap_const_logic_0) or (p_dst_rows_out_full_n = ap_const_logic_0) or (p_dst_cols_empty_n = ap_const_logic_0) or (p_dst_rows_empty_n = ap_const_logic_0) or (p_src_cols_empty_n = ap_const_logic_0) or (p_src_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_dst_rows_out_write <= ap_const_logic_1;
        else 
            p_dst_rows_out_write <= ap_const_logic_0;
        end if; 
    end process;


    p_dst_rows_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, p_src_rows_empty_n, p_src_cols_empty_n, p_dst_rows_empty_n, p_dst_cols_empty_n, p_dst_rows_out_full_n, p_dst_cols_out_full_n)
    begin
        if ((not(((p_dst_cols_out_full_n = ap_const_logic_0) or (p_dst_rows_out_full_n = ap_const_logic_0) or (p_dst_cols_empty_n = ap_const_logic_0) or (p_dst_rows_empty_n = ap_const_logic_0) or (p_src_cols_empty_n = ap_const_logic_0) or (p_src_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_dst_rows_read <= ap_const_logic_1;
        else 
            p_dst_rows_read <= ap_const_logic_0;
        end if; 
    end process;


    p_src_cols_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, p_src_cols_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_src_cols_blk_n <= p_src_cols_empty_n;
        else 
            p_src_cols_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_src_cols_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, p_src_rows_empty_n, p_src_cols_empty_n, p_dst_rows_empty_n, p_dst_cols_empty_n, p_dst_rows_out_full_n, p_dst_cols_out_full_n)
    begin
        if ((not(((p_dst_cols_out_full_n = ap_const_logic_0) or (p_dst_rows_out_full_n = ap_const_logic_0) or (p_dst_cols_empty_n = ap_const_logic_0) or (p_dst_rows_empty_n = ap_const_logic_0) or (p_src_cols_empty_n = ap_const_logic_0) or (p_src_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_src_cols_read <= ap_const_logic_1;
        else 
            p_src_cols_read <= ap_const_logic_0;
        end if; 
    end process;


    p_src_rows_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, p_src_rows_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_src_rows_blk_n <= p_src_rows_empty_n;
        else 
            p_src_rows_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_src_rows_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, p_src_rows_empty_n, p_src_cols_empty_n, p_dst_rows_empty_n, p_dst_cols_empty_n, p_dst_rows_out_full_n, p_dst_cols_out_full_n)
    begin
        if ((not(((p_dst_cols_out_full_n = ap_const_logic_0) or (p_dst_rows_out_full_n = ap_const_logic_0) or (p_dst_cols_empty_n = ap_const_logic_0) or (p_dst_rows_empty_n = ap_const_logic_0) or (p_src_cols_empty_n = ap_const_logic_0) or (p_src_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_src_rows_read <= ap_const_logic_1;
        else 
            p_src_rows_read <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
