-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity image_accelerator_CoreProcessUpArea is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    A0 : IN STD_LOGIC_VECTOR (7 downto 0);
    B0 : IN STD_LOGIC_VECTOR (7 downto 0);
    A1 : IN STD_LOGIC_VECTOR (7 downto 0);
    B1 : IN STD_LOGIC_VECTOR (7 downto 0);
    Wx : IN STD_LOGIC_VECTOR (31 downto 0);
    Wy : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of image_accelerator_CoreProcessUpArea is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";

attribute shreg_extract : string;
    signal Wy_read_reg_212 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal Wy_read_reg_212_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal Wx_read_reg_217 : STD_LOGIC_VECTOR (31 downto 0);
    signal Wx_read_reg_217_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal B1_read_reg_222 : STD_LOGIC_VECTOR (7 downto 0);
    signal A1_read_reg_227 : STD_LOGIC_VECTOR (7 downto 0);
    signal B0_read_reg_233 : STD_LOGIC_VECTOR (7 downto 0);
    signal A0_read_reg_238 : STD_LOGIC_VECTOR (7 downto 0);
    signal A0_read_reg_238_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal A0_read_reg_238_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal A0_read_reg_238_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal A0_read_reg_238_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal val0_fu_117_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal val0_reg_254 : STD_LOGIC_VECTOR (9 downto 0);
    signal val1_fu_123_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal val1_reg_259 : STD_LOGIC_VECTOR (8 downto 0);
    signal val2_fu_129_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal val2_reg_264 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln_reg_269 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_157_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal mul_ln40_reg_304 : STD_LOGIC_VECTOR (39 downto 0);
    signal grp_fu_166_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal mul_ln40_1_reg_309 : STD_LOGIC_VECTOR (39 downto 0);
    signal mul_ln40_1_reg_309_pp0_iter4_reg : STD_LOGIC_VECTOR (39 downto 0);
    signal grp_fu_175_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal mul_ln40_2_reg_314 : STD_LOGIC_VECTOR (39 downto 0);
    signal add_ln52_1_fu_181_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal add_ln52_1_reg_319 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal grp_fu_80_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_80_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln43_fu_86_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln43_2_fu_92_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln43_fu_101_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln43_fu_107_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln43_4_fu_98_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln43_1_fu_111_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln43_1_fu_89_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln43_3_fu_95_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_80_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_157_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_166_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_175_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal P4_fu_185_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal add_ln52_fu_192_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal add_ln52_2_fu_197_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal grp_fu_80_ce : STD_LOGIC;
    signal grp_fu_157_ce : STD_LOGIC;
    signal grp_fu_166_ce : STD_LOGIC;
    signal grp_fu_175_ce : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;
    signal A0_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal B0_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal A1_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal B1_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal Wx_int_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal Wy_int_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_return_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_157_p00 : STD_LOGIC_VECTOR (39 downto 0);
    signal grp_fu_166_p00 : STD_LOGIC_VECTOR (39 downto 0);
    signal grp_fu_175_p00 : STD_LOGIC_VECTOR (39 downto 0);
    signal grp_fu_80_p00 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_80_p10 : STD_LOGIC_VECTOR (63 downto 0);

    component image_accelerator_mul_32ns_32ns_64_2_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component image_accelerator_mul_32ns_10s_40_2_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (39 downto 0) );
    end component;


    component image_accelerator_mul_32ns_9s_40_2_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (39 downto 0) );
    end component;



begin
    mul_32ns_32ns_64_2_0_U68 : component image_accelerator_mul_32ns_32ns_64_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_80_p0,
        din1 => grp_fu_80_p1,
        ce => grp_fu_80_ce,
        dout => grp_fu_80_p2);

    mul_32ns_10s_40_2_0_U69 : component image_accelerator_mul_32ns_10s_40_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 10,
        dout_WIDTH => 40)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_157_p0,
        din1 => val0_reg_254,
        ce => grp_fu_157_ce,
        dout => grp_fu_157_p2);

    mul_32ns_9s_40_2_0_U70 : component image_accelerator_mul_32ns_9s_40_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 9,
        dout_WIDTH => 40)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_166_p0,
        din1 => val1_reg_259,
        ce => grp_fu_166_ce,
        dout => grp_fu_166_p2);

    mul_32ns_9s_40_2_0_U71 : component image_accelerator_mul_32ns_9s_40_2_0
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 9,
        dout_WIDTH => 40)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_175_p0,
        din1 => val2_reg_264,
        ce => grp_fu_175_ce,
        dout => grp_fu_175_p2);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                A0_int_reg <= A0;
                A1_int_reg <= A1;
                B0_int_reg <= B0;
                B1_int_reg <= B1;
                Wx_int_reg <= Wx;
                Wy_int_reg <= Wy;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                A0_read_reg_238 <= A0_int_reg;
                A0_read_reg_238_pp0_iter1_reg <= A0_read_reg_238;
                A0_read_reg_238_pp0_iter2_reg <= A0_read_reg_238_pp0_iter1_reg;
                A0_read_reg_238_pp0_iter3_reg <= A0_read_reg_238_pp0_iter2_reg;
                A0_read_reg_238_pp0_iter4_reg <= A0_read_reg_238_pp0_iter3_reg;
                A1_read_reg_227 <= A1_int_reg;
                B0_read_reg_233 <= B0_int_reg;
                B1_read_reg_222 <= B1_int_reg;
                Wx_read_reg_217 <= Wx_int_reg;
                Wx_read_reg_217_pp0_iter1_reg <= Wx_read_reg_217;
                Wy_read_reg_212 <= Wy_int_reg;
                Wy_read_reg_212_pp0_iter1_reg <= Wy_read_reg_212;
                add_ln52_1_reg_319 <= add_ln52_1_fu_181_p2;
                mul_ln40_1_reg_309 <= grp_fu_166_p2;
                mul_ln40_1_reg_309_pp0_iter4_reg <= mul_ln40_1_reg_309;
                mul_ln40_2_reg_314 <= grp_fu_175_p2;
                mul_ln40_reg_304 <= grp_fu_157_p2;
                trunc_ln_reg_269 <= grp_fu_80_p2(63 downto 32);
                val0_reg_254 <= val0_fu_117_p2;
                val1_reg_259 <= val1_fu_123_p2;
                val2_reg_264 <= val2_fu_129_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_int_reg <= add_ln52_2_fu_197_p2(39 downto 32);
            end if;
        end if;
    end process;
    P4_fu_185_p3 <= (A0_read_reg_238_pp0_iter4_reg & ap_const_lv32_0);
    add_ln52_1_fu_181_p2 <= std_logic_vector(unsigned(mul_ln40_2_reg_314) + unsigned(mul_ln40_reg_304));
    add_ln52_2_fu_197_p2 <= std_logic_vector(unsigned(add_ln52_1_reg_319) + unsigned(add_ln52_fu_192_p2));
    add_ln52_fu_192_p2 <= std_logic_vector(unsigned(mul_ln40_1_reg_309_pp0_iter4_reg) + unsigned(P4_fu_185_p3));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_assign_proc : process(add_ln52_2_fu_197_p2, ap_ce_reg, ap_return_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return <= ap_return_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return <= add_ln52_2_fu_197_p2(39 downto 32);
        end if; 
    end process;


    grp_fu_157_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_157_ce <= ap_const_logic_1;
        else 
            grp_fu_157_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_157_p0 <= grp_fu_157_p00(32 - 1 downto 0);
    grp_fu_157_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln_reg_269),40));

    grp_fu_166_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_166_ce <= ap_const_logic_1;
        else 
            grp_fu_166_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_166_p0 <= grp_fu_166_p00(32 - 1 downto 0);
    grp_fu_166_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Wx_read_reg_217_pp0_iter1_reg),40));

    grp_fu_175_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_175_ce <= ap_const_logic_1;
        else 
            grp_fu_175_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_175_p0 <= grp_fu_175_p00(32 - 1 downto 0);
    grp_fu_175_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Wy_read_reg_212_pp0_iter1_reg),40));

    grp_fu_80_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_80_ce <= ap_const_logic_1;
        else 
            grp_fu_80_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_80_p0 <= grp_fu_80_p00(32 - 1 downto 0);
    grp_fu_80_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Wy_int_reg),64));
    grp_fu_80_p1 <= grp_fu_80_p10(32 - 1 downto 0);
    grp_fu_80_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Wx_int_reg),64));
        sext_ln43_fu_107_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln43_fu_101_p2),10));

    sub_ln43_1_fu_111_p2 <= std_logic_vector(signed(sext_ln43_fu_107_p1) - signed(zext_ln43_4_fu_98_p1));
    sub_ln43_fu_101_p2 <= std_logic_vector(unsigned(zext_ln43_fu_86_p1) - unsigned(zext_ln43_2_fu_92_p1));
    val0_fu_117_p2 <= std_logic_vector(unsigned(sub_ln43_1_fu_111_p2) + unsigned(zext_ln43_1_fu_89_p1));
    val1_fu_123_p2 <= std_logic_vector(unsigned(zext_ln43_2_fu_92_p1) - unsigned(zext_ln43_fu_86_p1));
    val2_fu_129_p2 <= std_logic_vector(unsigned(zext_ln43_3_fu_95_p1) - unsigned(zext_ln43_fu_86_p1));
    zext_ln43_1_fu_89_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(B1_read_reg_222),10));
    zext_ln43_2_fu_92_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(B0_read_reg_233),9));
    zext_ln43_3_fu_95_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(A1_read_reg_227),9));
    zext_ln43_4_fu_98_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(A1_read_reg_227),10));
    zext_ln43_fu_86_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(A0_read_reg_238),9));
end behav;
