# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/hdmi_constraints.xdc

# Block Designs: bd/hdmi_in_bd/hdmi_in_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_in_bd || ORIG_REF_NAME==hdmi_in_bd} -quiet] -quiet

# IP: bd/hdmi_in_bd/ip/hdmi_in_bd_dvi2rgb_0_0/hdmi_in_bd_dvi2rgb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_in_bd_dvi2rgb_0_0 || ORIG_REF_NAME==hdmi_in_bd_dvi2rgb_0_0} -quiet] -quiet

# IP: bd/hdmi_in_bd/ip/hdmi_in_bd_v_vid_in_axi4s_0_0/hdmi_in_bd_v_vid_in_axi4s_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_in_bd_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==hdmi_in_bd_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/hdmi_in_bd/ip/hdmi_in_bd_processing_system7_0_0/hdmi_in_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_in_bd_processing_system7_0_0 || ORIG_REF_NAME==hdmi_in_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/hdmi_in_bd/ip/hdmi_in_bd_clk_wiz_0_0/hdmi_in_bd_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_in_bd_clk_wiz_0_0 || ORIG_REF_NAME==hdmi_in_bd_clk_wiz_0_0} -quiet] -quiet

# IP: bd/hdmi_in_bd/ip/hdmi_in_bd_proc_sys_reset_0_0/hdmi_in_bd_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_in_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==hdmi_in_bd_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/hdmi_in_bd/ip/hdmi_in_bd_proc_sys_reset_1_0/hdmi_in_bd_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_in_bd_proc_sys_reset_1_0 || ORIG_REF_NAME==hdmi_in_bd_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/hdmi_in_bd/ip/hdmi_in_bd_axi_vdma_0_0/hdmi_in_bd_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_in_bd_axi_vdma_0_0 || ORIG_REF_NAME==hdmi_in_bd_axi_vdma_0_0} -quiet] -quiet

# IP: bd/hdmi_in_bd/ip/hdmi_in_bd_xbar_0/hdmi_in_bd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_in_bd_xbar_0 || ORIG_REF_NAME==hdmi_in_bd_xbar_0} -quiet] -quiet

# IP: bd/hdmi_in_bd/ip/hdmi_in_bd_ps7_0_axi_periph_0/hdmi_in_bd_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_in_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==hdmi_in_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/hdmi_in_bd/ip/hdmi_in_bd_xbar_1/hdmi_in_bd_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_in_bd_xbar_1 || ORIG_REF_NAME==hdmi_in_bd_xbar_1} -quiet] -quiet

# IP: bd/hdmi_in_bd/ip/hdmi_in_bd_axi_mem_intercon_0/hdmi_in_bd_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_in_bd_axi_mem_intercon_0 || ORIG_REF_NAME==hdmi_in_bd_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/hdmi_in_bd/ip/hdmi_in_bd_xlconstant_0_0/hdmi_in_bd_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_in_bd_xlconstant_0_0 || ORIG_REF_NAME==hdmi_in_bd_xlconstant_0_0} -quiet] -quiet

# IP: bd/hdmi_in_bd/ip/hdmi_in_bd_xlconstant_1_0/hdmi_in_bd_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_in_bd_xlconstant_1_0 || ORIG_REF_NAME==hdmi_in_bd_xlconstant_1_0} -quiet] -quiet

# IP: bd/hdmi_in_bd/ip/hdmi_in_bd_xlconstant_2_0/hdmi_in_bd_xlconstant_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_in_bd_xlconstant_2_0 || ORIG_REF_NAME==hdmi_in_bd_xlconstant_2_0} -quiet] -quiet

# IP: bd/hdmi_in_bd/ip/hdmi_in_bd_axi_vdma_1_0/hdmi_in_bd_axi_vdma_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_in_bd_axi_vdma_1_0 || ORIG_REF_NAME==hdmi_in_bd_axi_vdma_1_0} -quiet] -quiet

# IP: bd/hdmi_in_bd/ip/hdmi_in_bd_xbar_2/hdmi_in_bd_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_in_bd_xbar_2 || ORIG_REF_NAME==hdmi_in_bd_xbar_2} -quiet] -quiet

# IP: bd/hdmi_in_bd/ip/hdmi_in_bd_axi_interconnect_0_0/hdmi_in_bd_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_in_bd_axi_interconnect_0_0 || ORIG_REF_NAME==hdmi_in_bd_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/hdmi_in_bd/ip/hdmi_in_bd_axis_data_fifo_1_0/hdmi_in_bd_axis_data_fifo_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_in_bd_axis_data_fifo_1_0 || ORIG_REF_NAME==hdmi_in_bd_axis_data_fifo_1_0} -quiet] -quiet

# IP: bd/hdmi_in_bd/ip/hdmi_in_bd_xlconcat_0_0/hdmi_in_bd_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_in_bd_xlconcat_0_0 || ORIG_REF_NAME==hdmi_in_bd_xlconcat_0_0} -quiet] -quiet

# IP: bd/hdmi_in_bd/ip/hdmi_in_bd_image_accelerator_0_1/hdmi_in_bd_image_accelerator_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_in_bd_image_accelerator_0_1 || ORIG_REF_NAME==hdmi_in_bd_image_accelerator_0_1} -quiet] -quiet

# IP: bd/hdmi_in_bd/ip/hdmi_in_bd_auto_pc_0/hdmi_in_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_in_bd_auto_pc_0 || ORIG_REF_NAME==hdmi_in_bd_auto_pc_0} -quiet] -quiet

# IP: bd/hdmi_in_bd/ip/hdmi_in_bd_auto_pc_1/hdmi_in_bd_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_in_bd_auto_pc_1 || ORIG_REF_NAME==hdmi_in_bd_auto_pc_1} -quiet] -quiet

# IP: bd/hdmi_in_bd/ip/hdmi_in_bd_auto_pc_2/hdmi_in_bd_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_in_bd_auto_pc_2 || ORIG_REF_NAME==hdmi_in_bd_auto_pc_2} -quiet] -quiet

# XDC: c:/imgProc/attempt4/hdmi_input/hdmi_input.gen/sources_1/bd/hdmi_in_bd/hdmi_in_bd_ooc.xdc
